'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { AlertTriangle, ArrowLeft, CheckCircle2, Save, Search, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Textarea } from '@/components/ui/textarea';
import type { Question } from '@/lib/course';

export default function QuestionBankReview({ initialQuestions }: { initialQuestions: Question[] }) {
  const [questions, setQuestions] = useState(initialQuestions); const [activeId, setActiveId] = useState(initialQuestions[0]?.id); const [query, setQuery] = useState(''); const [module, setModule] = useState('ALL'); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState('');
  const active = questions.find((q) => q.id === activeId)!;
  const filtered = useMemo(() => questions.filter((q) => (module === 'ALL' || q.module === module) && `${q.questionNumber} ${q.title} ${q.question} ${q.contentTags.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [questions, module, query]);
  const approved = questions.filter((q) => q.status === 'approved').length;
  const update = <K extends keyof Question>(key: K, value: Question[K]) => setQuestions((current) => current.map((q) => q.id === activeId ? { ...q, [key]: value } : q));
  async function save() { setSaving(true); setNotice(''); try { const response = await fetch('/api/admin/questions', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(active) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error); setNotice('Saved to the question bank and audit log.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to save this question.'); } finally { setSaving(false); } }
  return <main className="review-shell"><header className="review-header"><div><Link href="/admin" className="back-link"><ArrowLeft /> Training overview</Link><p className="tiny-eyebrow mt-5">Safeguarding team review</p><h1>Question bank</h1><p>{approved} approved • {30 - approved} awaiting review • SY2026–27</p></div><div className="review-warning"><AlertTriangle /><p><strong>AI-generated does not mean approved.</strong><br />Confirm every policy interpretation against the handbook before approval.</p></div></header>
    <div className="review-workspace"><aside className="question-list"><div className="question-list-controls"><div className="search-box"><Search /><Input aria-label="Search questions" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search question bank" /></div><NativeSelect aria-label="Filter questions by module" value={module} onChange={(e) => setModule(e.target.value)}><NativeSelectOption value="ALL">All modules</NativeSelectOption>{[1,2,3,4,5,6].map((n) => <NativeSelectOption key={n} value={`M${n}`}>Module {n}</NativeSelectOption>)}</NativeSelect></div><div className="question-list-scroll">{filtered.map((q) => <button key={q.id} className={`question-list-item ${q.id === activeId ? 'question-list-active' : ''}`} onClick={() => { setActiveId(q.id); setNotice(''); }}><span>{String(q.questionNumber).padStart(2,'0')}</span><span><strong>{q.title}</strong><small>{q.handbookSection} • p. {q.handbookPage}</small></span>{q.status === 'approved' ? <CheckCircle2 className="approved-icon" /> : q.criticalSafeguarding ? <ShieldCheck className="critical-icon" /> : null}</button>)}</div></aside>
      {active && <section className="question-editor"><div className="editor-heading"><div><span className="editor-id">Question {active.questionNumber} • {active.module}</span><h2>{active.title}</h2></div><NativeSelect aria-label="Question review status" value={active.status} onChange={(e) => update('status', e.target.value)}><NativeSelectOption value="draft_for_safeguarding_team_review">Draft for review</NativeSelectOption><NativeSelectOption value="needs_revision">Needs revision</NativeSelectOption><NativeSelectOption value="approved">Approved</NativeSelectOption></NativeSelect></div>
        <div className="editor-grid"><EditorField label="Title"><Input value={active.title} onChange={(e) => update('title', e.target.value)} /></EditorField><EditorField label="Learning objective"><Textarea value={active.learningObjective} onChange={(e) => update('learningObjective', e.target.value)} /></EditorField><EditorField label="Scenario"><Textarea value={active.scenario} onChange={(e) => update('scenario', e.target.value)} /></EditorField><EditorField label="Question"><Textarea value={active.question} onChange={(e) => update('question', e.target.value)} /></EditorField>
          <fieldset className="editor-field"><legend>Answer options and correct answer</legend><div className="space-y-2">{active.answerOptions.map((option, index) => <div className="option-editor" key={option.id}><Checkbox aria-label={`Mark option ${option.id} correct`} checked={active.correctAnswer?.includes(option.id)} onCheckedChange={(checked) => update('correctAnswer', checked ? [...(active.correctAnswer ?? []), option.id] : (active.correctAnswer ?? []).filter((id) => id !== option.id))} /><span>{option.id.toUpperCase()}</span><Input value={option.text} onChange={(e) => update('answerOptions', active.answerOptions.map((item, i) => i === index ? { ...item, text: e.target.value } : item))} /></div>)}</div><small>Checked options are scored as correct. Sequence questions use the displayed order.</small></fieldset>
          <EditorField label="Correct feedback"><Textarea value={active.correctFeedback} onChange={(e) => update('correctFeedback', e.target.value)} /></EditorField><EditorField label="Incorrect feedback"><Textarea value={active.incorrectFeedback} onChange={(e) => update('incorrectFeedback', e.target.value)} /></EditorField>
          <div className="editor-split"><EditorField label="Handbook section"><Input value={active.handbookSection} onChange={(e) => update('handbookSection', e.target.value)} /></EditorField><EditorField label="Handbook page"><Input type="number" min={1} max={39} value={active.handbookPage} onChange={(e) => update('handbookPage', Number(e.target.value))} /></EditorField></div>
          <EditorField label="Content tags"><Input value={active.contentTags.join(', ')} onChange={(e) => update('contentTags', e.target.value.split(',').map((value) => value.trim()).filter(Boolean))} /></EditorField><div className="critical-toggle"><Checkbox aria-label="Critical safeguarding question" checked={active.criticalSafeguarding} onCheckedChange={(value) => update('criticalSafeguarding', Boolean(value))} /><span><strong>Critical safeguarding question</strong><small>An incorrect answer triggers remediation before the learner continues. It does not automatically fail the assessment.</small></span></div>
        </div><div className="editor-footer"><p className={notice ? 'save-notice' : ''}>{notice || `Last source check required: ${active.handbookSection}, page ${active.handbookPage}.`}</p><Button className="primary-pill" size="lg" onClick={save} disabled={saving}><Save /> {saving ? 'Saving…' : 'Save question'}</Button></div>
      </section>}
    </div></main>;
}

function EditorField({ label, children }: { label: string; children: React.ReactNode }) { return <div className="editor-field"><span>{label}</span>{children}</div>; }
