'use client';
import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, Lightbulb, Save } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { aiQuestions, aiSections, AI_COURSE_VERSION, type AiQuestion } from '@/lib/ai-course';
import { teamsQuestions, teamsSections, TEAMS_COURSE_VERSION } from '@/lib/teams-course';
import { mtssQuestions, mtssSections, MTSS_COURSE_VERSION } from '@/lib/mtss-course';
type State={position:number;completedSections:string[];responses:Record<string,{answer:string;correct:boolean}>;completedAt?:number;practice?:string;commitment?:string};
const blank:State={position:0,completedSections:[],responses:{}};
const configs={ai:{key:'my-courses-ai-progress-v1',title:'AI in Education',version:AI_COURSE_VERSION,sections:aiSections,questions:aiQuestions,practice:['Be more deliberate about what student information I share with AI.','Keep the human in the loop when using AI for feedback.','Verify AI-generated information before using it.','Consider bias and representation more carefully.','Redesign an assessment to make student thinking more visible.','Something else']},teams:{key:'my-courses-teams-progress-v1',title:'Microsoft Teams for Communication',version:TEAMS_COURSE_VERSION,sections:teamsSections,questions:teamsQuestions,practice:['Choose the right audience for student communication.','Share only necessary support information.','Describe observations rather than labels.','Keep confidential records out of Teams.','Write as though messages may be reviewed.','Something else']},mtss:{key:'my-courses-mtss-progress-v1',title:'Multi-Tiered System of Supports (MTSS)',version:MTSS_COURSE_VERSION,sections:mtssSections,questions:mtssQuestions,practice:['Use the complete MTSS decision cycle.','Bring multiple evidence sources to decisions.','Check Tier 1 before intensifying support.','Set measurable goals and decision rules.','Monitor fidelity and equity.','Invite learner and family perspectives.','Something else']}} as const;
function read(key:string):State{try{const v=JSON.parse(localStorage.getItem(key)||'null');return v&&typeof v==='object'?{...blank,...v}:blank}catch{return blank}}
function write(key:string,v:State){try{localStorage.setItem(key,JSON.stringify(v))}catch{}}
export default function AiTrainingApp({onExit,course='ai'}:{onExit:()=>void;course?:keyof typeof configs}){const c=configs[course];const [state,setState]=useState(()=>read(c.key));const [stage,setStage]=useState<'learn'|'question'|'practice'|'complete'>(()=>read(c.key).completedAt?'complete':'learn');const [qi,setQi]=useState(()=>Math.min(c.questions.length-1,read(c.key).position));const [si,setSi]=useState(()=>Math.min(c.sections.length-1,Math.floor(read(c.key).position/2)));const [selected,setSelected]=useState('');const [feedback,setFeedback]=useState<string|null>(null);const [correct,setCorrect]=useState<boolean|null>(null);const [practice,setPractice]=useState(state.practice||'');const [commitment,setCommitment]=useState(state.commitment||'');const q=c.questions[qi];const s=c.sections[si];const answered=useMemo(()=>state.responses[q.id],[state.responses,q.id]);const pct=Math.round((Object.keys(state.responses).length+state.completedSections.length)/(c.questions.length+c.sections.length)*100);function update(v:State){setState(v);write(c.key,v)}function completeLearn(){update({...state,completedSections:state.completedSections.includes(s.id)?state.completedSections:[...state.completedSections,s.id],position:Math.max(state.position,qi)});setStage('question')}function submit(){if(!selected||answered)return;const ok=selected===q.answer;update({...state,responses:{...state.responses,[q.id]:{answer:selected,correct:ok}},position:Math.max(state.position,qi+1)});setCorrect(ok);setFeedback(ok?q.correctFeedback:q.incorrectFeedback)}function next(){if(qi===c.questions.length-1){setStage('practice');return}const n=qi+1;setQi(n);setSelected('');setFeedback(null);setCorrect(null);if(Math.floor(n/2)!==si){setSi(Math.floor(n/2));setStage('learn')}else setStage('question')}function finish(){update({...state,practice,commitment,completedAt:Date.now()});setStage('complete')}
if(stage==='complete')return <main className="learning-shell"><section className="results-card"><p className="tiny-eyebrow">My Courses · {c.title}</p><h1>Course complete</h1><p className="results-lead">You completed the learning and applied the principles to realistic professional decisions.</p><div className="score-grid"><div><span>Score</span><strong>{Object.values(state.responses).filter(r=>r.correct).length}/{c.questions.length}</strong></div><div><span>Version</span><strong>{c.version}</strong></div><div><span>Status</span><strong>Completed</strong></div></div><div className="principle-card"><CheckCircle2/><div><strong>Take it into practice</strong><p>{practice||'No practice idea selected.'}</p>{commitment&&<p className="mt-2"><strong>My commitment:</strong> {commitment}</p>}</div></div><Button className="primary-pill mt-8" size="lg" onClick={onExit}><ArrowLeft/> Back to My Courses</Button></section></main>;
if(stage==='practice')return <main className="learning-shell"><section className="intro-card"><p className="tiny-eyebrow">Apply · Take it into practice</p><h1>What is one practice from this course that you want to strengthen?</h1><div className="answers practice-options">{c.practice.map(o=><label key={o} className={`answer-option ${practice===o?'answer-selected':''}`}><input type="radio" name="practice" checked={practice===o} onChange={()=>setPractice(o)}/><span>{o}</span></label>)}</div>{practice&&<textarea className="mt-6 w-full rounded-xl border p-3" value={commitment} onChange={e=>setCommitment(e.target.value)} placeholder="What is one thing you could try?" rows={3}/>}<Button className="primary-pill mt-8" size="lg" disabled={!practice} onClick={finish}>Save and complete <ArrowRight/></Button></section></main>;
if(stage==='learn')return <main className="learning-shell"><div className="learning-top"><Button variant="ghost" onClick={onExit}><ArrowLeft/> Course home</Button><span className="section-position">Section {s.number} of {c.sections.length}</span></div><div className="dual-progress"><Progress value={pct}/><span className="text-sm text-muted-foreground">{pct}% overall</span></div><section className="intro-card lesson-card"><div className="module-orbit">{String(s.number).padStart(2,'0')}</div><p className="tiny-eyebrow">Learn · {s.title}</p><h1>{s.title}</h1><p className="intro-summary">{s.summary}</p>{s.learn.map(p=><p className="lesson-copy" key={p}>{p}</p>)}<div className="takeaway-list mt-6"><p className="meta-label">Key takeaways</p>{s.takeaways.map(t=><div className="flex items-start gap-3" key={t}><CheckCircle2 className="mt-1 text-red"/><span>{t}</span></div>)}</div><Button className="primary-pill mt-8" size="lg" onClick={completeLearn}>Check your understanding <ArrowRight/></Button></section></main>;
return <main className="learning-shell"><div className="learning-top"><span className="text-sm font-semibold text-navy">Section {s.number} of {c.sections.length} — {s.title}</span><span className="text-sm text-muted-foreground">Check {qi%2+1} of 2</span></div><div className="dual-progress"><Progress value={pct}/><span className="text-sm text-muted-foreground">{pct}% overall</span></div><section className="question-layout"><div className="question-number">{String(qi+1).padStart(2,'0')}</div><article className="question-card"><span className="question-kind">Check your understanding · Choose one</span><h1>{q.question}</h1><div className="scenario"><span>Scenario</span><p>{q.scenario}</p></div><div className="answers">{q.options.map(o=><label key={o.id} className={`answer-option ${selected===o.id?'answer-selected':''}`}><input type="radio" name={q.id} value={o.id} checked={selected===o.id} disabled={Boolean(answered)} onChange={()=>setSelected(o.id)}/><span><b>{o.id.toUpperCase()}</b>{o.text}</span></label>)}</div>{feedback&&<output className={`feedback-card ${correct?'feedback-correct':'feedback-incorrect'}`}><Lightbulb/><div><strong>{correct?'Correct — apply the principle':'Not quite — review the principle'}</strong><p>{feedback}</p></div></output>}<div className="question-actions"><span className="autosave"><Save/> Progress saved in this browser</span>{feedback?<Button className="primary-pill" size="lg" onClick={next}>{qi===c.questions.length-1?'Take it into practice':qi%2===1?'Next section':'Continue'} <ArrowRight/></Button>:<Button className="primary-pill" size="lg" disabled={!selected} onClick={submit}>Check response</Button>}</div></article></section></main>}
