'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, Lightbulb, Save } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { aiQuestions, aiSections, AI_COURSE_VERSION, type AiQuestion } from '@/lib/ai-course';

type AiState = { position: number; completedSections: string[]; responses: Record<string, { answer: string; correct: boolean }>; completedAt?: number; practice?: string; commitment?: string };
const KEY = 'my-courses-ai-progress-v1';
const blank: AiState = { position: 0, completedSections: [], responses: {} };
function read(): AiState { try { const parsed = JSON.parse(localStorage.getItem(KEY) || 'null'); return parsed && typeof parsed === 'object' ? { ...blank, ...parsed } : blank; } catch { return blank; } }
function save(state: AiState) { try { localStorage.setItem(KEY, JSON.stringify(state)); } catch { /* storage may be unavailable */ } }

export default function AiTrainingApp({ onExit }: { onExit: () => void }) {
  const [state, setState] = useState<AiState>(() => read());
  const [stage, setStage] = useState<'learn' | 'question' | 'practice' | 'complete'>(() => read().completedAt ? 'complete' : 'learn');
  const [sectionIndex, setSectionIndex] = useState(() => Math.min(4, Math.floor(read().position / 2)));
  const [questionIndex, setQuestionIndex] = useState(() => Math.min(9, read().position));
  const [selected, setSelected] = useState('');
  const [feedback, setFeedback] = useState<AiQuestion['correctFeedback'] | null>(null);
  const [answeredCorrect, setAnsweredCorrect] = useState<boolean | null>(null);
  const [practice, setPractice] = useState(state.practice || '');
  const [commitment, setCommitment] = useState(state.commitment || '');
  const section = aiSections[sectionIndex];
  const question = aiQuestions[questionIndex];
  const sectionLearned = state.completedSections.includes(section.id);
  const progress = Math.round((Object.keys(state.responses).length + state.completedSections.length) / 15 * 100);
  const answered = useMemo(() => state.responses[question.id], [state.responses, question.id]);

  useEffect(() => { document.title = 'AI in Education | My Courses'; }, []);

  function update(next: AiState) { setState(next); save(next); }
  function completeLearning() { const next = { ...state, completedSections: state.completedSections.includes(section.id) ? state.completedSections : [...state.completedSections, section.id], position: Math.max(state.position, questionIndex) }; update(next); setStage('question'); }
  function submit() { if (!selected || answered) return; const correct = selected === question.answer; const next = { ...state, responses: { ...state.responses, [question.id]: { answer: selected, correct } }, position: Math.max(state.position, questionIndex + 1) }; update(next); setAnsweredCorrect(correct); setFeedback(correct ? question.correctFeedback : question.incorrectFeedback); }
  function nextQuestion() { if (questionIndex === 9) { setStage('practice'); return; } const nextIndex = questionIndex + 1; setQuestionIndex(nextIndex); setSectionIndex(Math.floor(nextIndex / 2)); setSelected(''); setFeedback(null); setAnsweredCorrect(null); setStage('learn'); }
  function finish() { update({ ...state, practice, commitment, completedAt: Date.now() }); setStage('complete'); }
  const sectionQuestion = questionIndex % 2 + 1;
  if (stage === 'complete') return <main className="learning-shell"><section className="results-card"><p className="tiny-eyebrow">My Courses · AI in Education</p><h1>Course complete</h1><p className="results-lead">You completed the learning and applied the principles to ten realistic education decisions.</p><div className="score-grid"><div><span>Score</span><strong>{Object.values(state.responses).filter((r) => r.correct).length}/10</strong></div><div><span>Version</span><strong>{AI_COURSE_VERSION}</strong></div><div><span>Status</span><strong>Completed</strong></div></div><div className="principle-card"><CheckCircle2 aria-hidden="true" /><div><strong>Take it into practice</strong><p>{practice || 'No practice idea selected.'}</p>{commitment && <p className="mt-2"><strong>My commitment:</strong> {commitment}</p>}</div></div><Button className="primary-pill mt-8" size="lg" onClick={onExit}><ArrowLeft /> Back to My Courses</Button></section></main>;
  if (stage === 'practice') return <main className="learning-shell"><section className="intro-card"><p className="tiny-eyebrow">Apply · Take it into practice</p><h1>What is one idea from this course that you want to apply?</h1><div className="answers practice-options">{['Be more deliberate about what student information I share with AI.','Keep the human in the loop when using AI for feedback.','Verify AI-generated information before using it.','Consider bias and representation more carefully.','Redesign an assessment to make student thinking more visible.','Understand an AI tool before introducing it to students.','Use AI to scaffold thinking rather than replace it.','Start with the learning goal before choosing AI.','Something else'].map((option) => <label key={option} className={`answer-option ${practice === option ? 'answer-selected' : ''}`}><input type="radio" name="practice" checked={practice === option} onChange={() => setPractice(option)} /><span>{option}</span></label>)}</div>{practice === 'Something else' && <textarea className="mt-4 w-full rounded-xl border border-navy/15 p-3" value={commitment} onChange={(event) => setCommitment(event.target.value)} placeholder="Share your idea (optional)" rows={3} />}{practice && practice !== 'Something else' && <label className="mt-6 block"><span className="meta-label">My commitment (optional)</span><textarea className="mt-2 w-full rounded-xl border border-navy/15 p-3" value={commitment} onChange={(event) => setCommitment(event.target.value)} placeholder="What is one thing you could try in your practice?" rows={3} /></label>}<Button className="primary-pill mt-8" size="lg" disabled={!practice} onClick={finish}>Save and complete <ArrowRight /></Button></section></main>;
  if (stage === 'learn') return <main className="learning-shell"><div className="learning-top"><Button variant="ghost" onClick={onExit}><ArrowLeft /> My Courses</Button><span className="section-position">Section {section.number} of 5</span></div><div className="dual-progress"><Progress value={progress} aria-label={`Overall course: ${progress}%`} /><span className="text-sm text-muted-foreground">{progress}% overall</span></div><section className="intro-card lesson-card"><div className="module-orbit">{String(section.number).padStart(2, '0')}</div><p className="tiny-eyebrow">Learn · {section.title}</p><h1>{section.title}</h1><p className="intro-summary">{section.summary}</p>{section.learn.map((paragraph) => <p className="lesson-copy" key={paragraph}>{paragraph}</p>)}<div className="takeaway-list mt-6"><p className="meta-label">Key takeaways</p>{section.takeaways.map((item) => <div className="flex items-start gap-3" key={item}><CheckCircle2 className="mt-1 text-red" /><span>{item}</span></div>)}</div><Button className="primary-pill mt-8" size="lg" onClick={completeLearning}>Check your understanding <ArrowRight /></Button></section></main>;
  return <main className="learning-shell"><div className="learning-top"><span className="text-sm font-semibold text-navy">Section {section.number} of 5 — {section.title}</span><span className="text-sm text-muted-foreground">Check {sectionQuestion} of 2</span></div><div className="dual-progress"><Progress value={progress} aria-label={`Overall course: ${progress}%`} /><span className="text-sm text-muted-foreground">{progress}% overall</span></div><section className="question-layout"><div className="question-number">{String(questionIndex + 1).padStart(2, '0')}</div><article className="question-card"><span className="question-kind">Check your understanding · Choose one</span><h1>{question.question}</h1><div className="scenario"><span>Scenario</span><p>{question.scenario}</p></div><div className="answers">{question.options.map((option) => <label key={option.id} className={`answer-option ${selected === option.id ? 'answer-selected' : ''} ${answered && answered.answer === option.id && !answered.correct ? 'answer-wrong' : ''}`}><input type="radio" name={question.id} value={option.id} checked={selected === option.id} disabled={Boolean(answered)} onChange={() => setSelected(option.id)} /><span><b>{option.id.toUpperCase()}</b>{option.text}</span></label>)}</div>{feedback && <output className={`feedback-card ${answeredCorrect ? 'feedback-correct' : 'feedback-incorrect'}`}><div><Lightbulb /></div><div><strong>{answeredCorrect ? 'Correct — apply the principle' : 'Not quite — review the principle'}</strong><p>{feedback}</p></div></output>}<div className="question-actions"><span className="autosave"><Save /> Progress saved in this browser</span>{feedback ? <Button className="primary-pill" size="lg" onClick={nextQuestion}>{questionIndex === 9 ? 'Take it into practice' : sectionQuestion === 2 ? 'Next section' : 'Continue'} <ArrowRight /></Button> : <Button className="primary-pill" size="lg" disabled={!selected} onClick={submit}>Check response</Button>}</div></article></section></main>;
}
