import type { AiQuestion, AiSection } from '@/lib/ai-course';

export const ASSESSMENT_FOR_LEARNING_COURSE_VERSION = 'SY2026-27';

const shared = {
  courseVersion: ASSESSMENT_FOR_LEARNING_COURSE_VERSION,
  contentOwner: 'Learning & Teaching',
  reviewStatus: 'draft_for_learning_and_teaching_review',
} as const;

export const assessmentForLearningSections: AiSection[] = [
  {
    id: 'afl-purpose',
    number: 1,
    title: 'Assessment Is Part of Learning — Not Just the End of It',
    summary: 'Use assessment evidence while learning is still happening so teachers and learners can decide what to do next.',
    learn: [
      'Assessment for Learning is less about a particular tool and more about what happens with evidence. A quiz, conversation, draft, observation, exit ticket or student explanation becomes formative when the evidence is used to improve the learning that follows. An activity can be called “formative” and still add little value if nobody changes what they do because of it.',
      'At AISG, our Teacher Growth and Reflection Framework describes stronger assessment practice as varied and formative, with timely feedback that students use to improve learning. At the most developed end, assessment becomes a continuous process in which students self-assess, set goals and adapt learning in real time. The practical question is therefore not simply “What will I assess?” but “What decision will this evidence help us make?”',
    ],
    takeaways: [
      'Formative assessment is defined by how evidence is used, not by the name of the task.',
      'Assessment should inform a next move for the teacher, the learner, or both.',
      'Frequent checking is only useful when it changes what happens next.',
      'Assessment for learning happens during learning, while there is still time to improve.',
    ],
    questions: [
      {
        ...shared,
        id: 'afl-1', section: 'afl-purpose', questionNumber: 1, assessmentLevel: 'Foundation',
        learningObjective: 'Recognise formative assessment as a use of evidence rather than a task label.',
        scenario: 'A teacher gives an exit ticket at the end of every lesson, records the scores, and begins the next lesson exactly as planned regardless of the responses.',
        question: 'What is the main Assessment for Learning issue?',
        options: [
          { id: 'a', text: 'Exit tickets should only be used once per unit.' },
          { id: 'b', text: 'The evidence is being collected, but it is not being used to adjust learning or teaching.' },
          { id: 'c', text: 'Exit tickets are summative assessments by definition.' },
          { id: 'd', text: 'Every exit ticket should receive a grade.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. A check becomes formative through its use. The key question is what the teacher or learner does differently because of the evidence.',
        incorrectFeedback: 'The format is not the issue. Assessment for Learning depends on using evidence to shape a next step while learning can still improve.',
        contentTags: ['Assessment for Learning', 'Formative Assessment', 'Evidence'],
      },
      {
        ...shared,
        id: 'afl-2', section: 'afl-purpose', questionNumber: 2, assessmentLevel: 'Application',
        learningObjective: 'Use assessment evidence to identify an instructional next step.',
        scenario: 'During a lesson, most students can calculate the answer correctly but cannot explain why the method works.',
        question: 'Which response best uses the evidence formatively?',
        options: [
          { id: 'a', text: 'Move on because most answers are correct.' },
          { id: 'b', text: 'Give the same calculation for homework and check completion tomorrow.' },
          { id: 'c', text: 'Pause to surface student reasoning, model or compare explanations, then check whether understanding has changed.' },
          { id: 'd', text: 'Record the result as a low summative grade.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. The evidence reveals a gap between procedural success and conceptual understanding, so the next move should target that gap and then re-check it.',
        incorrectFeedback: 'Assessment for Learning uses evidence to decide what learners need next, not simply to record performance or repeat the same task.',
        contentTags: ['Responsive Teaching', 'Conceptual Understanding', 'Next Steps'],
      },
    ],
  },
  {
    id: 'afl-clarity',
    number: 2,
    title: 'Make the Learning and Success Visible',
    summary: 'Separate the learning intention from the activity and make quality visible through useful success criteria.',
    learn: [
      'Learners are better able to monitor progress when they understand what they are learning and what stronger work looks like. A learning intention describes the learning; an activity describes what students will do. “Create a poster” is a task. “Explain how evidence supports a scientific claim” describes learning that can be demonstrated through different tasks or modes.',
      'Success criteria make quality visible. Strong criteria focus attention on the features of successful learning rather than on compliance such as number of slides, colours or decorative features. Criteria can be clarified through examples, modelling, co-construction or comparison of work. This connects strongly with TLF Agency: learners are more able to make meaningful decisions, use feedback and monitor progress when the destination is understandable.',
    ],
    takeaways: [
      'Learning intentions describe what students are learning, not merely what they are doing.',
      'Success criteria make quality and progress more visible.',
      'Avoid criteria that reward compliance more than the intended learning.',
      'Clarity supports Agency because learners can make better decisions about their own next steps.',
    ],
    questions: [
      {
        ...shared,
        id: 'afl-3', section: 'afl-clarity', questionNumber: 3, assessmentLevel: 'Application',
        learningObjective: 'Distinguish a learning intention from an activity.',
        scenario: 'A teacher writes the lesson objective as: “Complete a three-slide presentation about migration.”',
        question: 'Which revision better expresses the intended learning?',
        options: [
          { id: 'a', text: 'Finish all three slides before the end of class.' },
          { id: 'b', text: 'Use at least two images and one transition.' },
          { id: 'c', text: 'Explain how push and pull factors influence migration, using relevant evidence.' },
          { id: 'd', text: 'Work independently and stay on task.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. The learning is the explanation and use of evidence; the presentation is only one possible means of demonstrating it.',
        incorrectFeedback: 'A useful learning intention names the understanding or capability learners are developing rather than the product, behaviour or format.',
        contentTags: ['Learning Intentions', 'Clarity', 'Success Criteria'],
      },
      {
        ...shared,
        id: 'afl-4', section: 'afl-clarity', questionNumber: 4, assessmentLevel: 'Analysis',
        learningObjective: 'Evaluate success criteria for alignment with intended learning.',
        scenario: 'Students are learning to build a convincing historical argument. The draft success criteria are: “five paragraphs, a title, two images, correct font, submitted on time.”',
        question: 'What is the strongest improvement?',
        options: [
          { id: 'a', text: 'Add more formatting requirements so expectations are clearer.' },
          { id: 'b', text: 'Replace most compliance criteria with features such as a defensible claim, relevant evidence, reasoning and consideration of perspective.' },
          { id: 'c', text: 'Remove all criteria so students have complete freedom.' },
          { id: 'd', text: 'Keep the criteria and increase the grade weighting.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Success criteria should make the quality of the intended learning visible. Format can matter when it is part of the construct, but it should not crowd out the learning itself.',
        incorrectFeedback: 'The criteria need to point learners toward the quality of the historical reasoning, not mainly toward completion and presentation features.',
        contentTags: ['Success Criteria', 'Alignment', 'Quality'],
      },
    ],
  },
  {
    id: 'afl-evidence',
    number: 3,
    title: 'Elicit Evidence from More Than the Confident Few',
    summary: 'Use checks that reveal enough learner thinking to make a sound next decision.',
    learn: [
      'A strong check for understanding makes thinking visible. Hands-up questions can be useful for discussion, but they often tell us most about the learners who are already confident enough to volunteer. Assessment for Learning needs evidence from enough of the class to support a decision: short written responses, mini-whiteboards, selected-response hinge questions, student explanations, drafts, demonstrations, observation, conferences or other quick evidence matched to the learning.',
      'Good evidence collection is also an inclusion issue. If the goal is conceptual understanding, unnecessary barriers in language, speed, handwriting or response format can distort what the evidence tells us. Where the intended construct allows it, multiple ways to demonstrate understanding can strengthen Personalisation and produce more valid evidence. The aim is not endless choice; it is to see the learning more accurately.',
    ],
    takeaways: [
      'Plan checks that reveal thinking from enough learners to inform a decision.',
      'Ask questions that expose misconceptions, not only recall correct answers.',
      'Match the evidence method to the learning you actually need to see.',
      'Remove irrelevant barriers when they would distort the evidence of learning.',
    ],
    questions: [
      {
        ...shared,
        id: 'afl-5', section: 'afl-evidence', questionNumber: 5, assessmentLevel: 'Application',
        learningObjective: 'Select a check that provides representative evidence of class understanding.',
        scenario: 'A teacher asks, “Does everyone understand?” Three confident students say yes and the lesson moves on.',
        question: 'Which alternative would provide stronger evidence for the next teaching decision?',
        options: [
          { id: 'a', text: 'Ask the same three students to explain again.' },
          { id: 'b', text: 'Use a brief prompt that requires every learner to respond, then inspect the pattern before deciding whether to move on.' },
          { id: 'c', text: 'Assume silence means understanding.' },
          { id: 'd', text: 'Wait until the summative assessment.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The goal is not more questioning for its own sake; it is enough useful evidence to decide what the class needs next.',
        incorrectFeedback: 'Volunteer responses can hide the distribution of understanding. A stronger check makes more learners’ thinking visible before the decision is made.',
        contentTags: ['Checks for Understanding', 'Eliciting Evidence', 'Participation'],
      },
      {
        ...shared,
        id: 'afl-6', section: 'afl-evidence', questionNumber: 6, assessmentLevel: 'Analysis',
        learningObjective: 'Use a hinge question to identify a misconception that should shape instruction.',
        scenario: 'Before moving from fractions to adding unlike denominators, a teacher wants one quick question that will reveal whether students understand equivalence rather than simply follow a memorised procedure.',
        question: 'What makes a strong hinge question for this purpose?',
        options: [
          { id: 'a', text: 'It is easy enough that nearly everyone gets it right.' },
          { id: 'b', text: 'It can be answered quickly, each option reflects a plausible line of thinking, and the response pattern tells the teacher whether to move on or respond.' },
          { id: 'c', text: 'It contains as many calculations as possible.' },
          { id: 'd', text: 'It is graded so students take it seriously.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. A hinge question is useful because the response pattern reveals thinking at a decision point in the lesson.',
        incorrectFeedback: 'The power of a hinge question is diagnostic: it distinguishes lines of thinking quickly enough to influence what the teacher does next.',
        contentTags: ['Hinge Questions', 'Misconceptions', 'Responsive Teaching'],
      },
      {
        ...shared,
        id: 'afl-7', section: 'afl-evidence', questionNumber: 7, assessmentLevel: 'Analysis',
        learningObjective: 'Preserve the intended construct while removing an irrelevant barrier to demonstrating learning.',
        scenario: 'The learning goal is to explain the causes of erosion. A multilingual learner understands the science in discussion but writes very slowly in English. The teacher wants evidence of conceptual understanding today.',
        question: 'Which response is most aligned with Assessment for Learning and TLF Personalisation?',
        options: [
          { id: 'a', text: 'Require the same timed written response because fairness means identical conditions.' },
          { id: 'b', text: 'Allow an oral or supported multimodal explanation if the mode is not part of the science construct, while continuing to support academic language development separately.' },
          { id: 'c', text: 'Excuse the student from showing understanding.' },
          { id: 'd', text: 'Lower the science expectation.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. When response mode is not the target, removing an irrelevant barrier can produce more valid evidence without lowering the conceptual expectation.',
        incorrectFeedback: 'Equal treatment is not always equivalent access. Preserve the science goal while choosing a valid way for the learner to demonstrate it.',
        contentTags: ['Personalisation', 'Validity', 'Learner Variability'],
      },
    ],
  },
  {
    id: 'afl-feedback',
    number: 4,
    title: 'Feedback Should Create a Next Move',
    summary: 'Make feedback timely, specific and usable — then give learners an opportunity to act on it.',
    learn: [
      'Feedback is useful when it helps close the gap between current work and the intended learning. Effective feedback is usually connected to the learning intention or success criteria, specific enough to guide action, and manageable enough for the learner to use. Comments that only praise, judge or correct everything can leave learners unsure what to do next.',
      'The feedback cycle is incomplete until there is an opportunity to respond. Revision, a second attempt, a short follow-up problem, a conference, peer discussion or immediate practice can turn information into learning. Feedback also works in both directions: student responses tell the teacher what to reteach, model, vary or stop doing. At AISG, our growth framework emphasises timely feedback that informs next steps immediately and is used by students during learning.',
    ],
    takeaways: [
      'Connect feedback to the intended learning and criteria for quality.',
      'Prioritise a manageable next step rather than commenting on everything.',
      'Build in time for learners to use feedback.',
      'Treat learner responses as feedback on teaching too.',
    ],
    questions: [
      {
        ...shared,
        id: 'afl-8', section: 'afl-feedback', questionNumber: 8, assessmentLevel: 'Application',
        learningObjective: 'Identify feedback that is specific and actionable.',
        scenario: 'A student receives one of four comments on a draft.',
        question: 'Which comment is most likely to move the learning forward?',
        options: [
          { id: 'a', text: 'Good job!' },
          { id: 'b', text: '7/10.' },
          { id: 'c', text: 'Your claim is clear. Now choose one piece of evidence and add a sentence explaining how it supports that claim.' },
          { id: 'd', text: 'Needs more detail.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. It identifies what is working and gives a specific next action connected to the learning.',
        incorrectFeedback: 'Useful feedback should make the next move clearer. Praise, scores or vague comments alone provide limited direction for improvement.',
        contentTags: ['Feedback', 'Actionable Feedback', 'Revision'],
      },
      {
        ...shared,
        id: 'afl-9', section: 'afl-feedback', questionNumber: 9, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Design a feedback process that results in learner action.',
        scenario: 'A teacher spends hours writing detailed comments on final essays. Students read the grade, glance at the comments and file the work away.',
        question: 'What is the strongest redesign?',
        options: [
          { id: 'a', text: 'Write even longer comments so students understand their mistakes.' },
          { id: 'b', text: 'Move some feedback earlier in the process, prioritise the most important next step, and require time for students to use it in revision or a subsequent task.' },
          { id: 'c', text: 'Stop giving feedback entirely.' },
          { id: 'd', text: 'Add more points to the rubric.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Feedback is more powerful when it arrives while improvement is possible and learners are expected to act on it.',
        incorrectFeedback: 'The issue is not the quantity of teacher effort. The process needs to create a meaningful learner response while learning is still developing.',
        contentTags: ['Feedback Cycle', 'Timing', 'Learner Action'],
      },
    ],
  },
  {
    id: 'afl-agency',
    number: 5,
    title: 'Help Learners Use Evidence for Themselves',
    summary: 'Move from teacher-owned assessment toward shared criteria, self-assessment, peer learning and learner-owned next steps.',
    learn: [
      'Assessment for Learning becomes more powerful when learners can interpret evidence too. Self-assessment is not simply asking, “How do you think you did?” It means comparing work or understanding with clear criteria, identifying evidence, and deciding on a next step. Peer feedback is strongest when learners understand the criteria, the culture is psychologically safe, and the purpose is to improve work rather than rank one another.',
      'This is where assessment connects most directly with TLF Agency. Learners use feedback, set goals, monitor progress and make meaningful decisions about what to try next. It can also support Collaboration when students become useful learning resources for one another, and Personalisation when evidence helps learners and teachers respond to individual strengths and needs. A simple cycle is: Where are we going? Where are we now? What is the next move? Then gather new evidence and repeat.',
    ],
    takeaways: [
      'Teach learners how to interpret criteria and evidence, not just receive scores.',
      'Self-assessment should lead to a specific next step.',
      'Peer feedback needs shared criteria, purpose and psychological safety.',
      'Assessment can strengthen Agency when learners increasingly monitor and direct their own improvement.',
    ],
    questions: [
      {
        ...shared,
        id: 'afl-10', section: 'afl-agency', questionNumber: 10, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Use self-assessment to strengthen learner ownership of improvement.',
        scenario: 'Before submitting a project, students are asked to rate themselves from 1–5 for “effort” and then submit immediately.',
        question: 'Which change would make the self-assessment more useful for learning?',
        options: [
          { id: 'a', text: 'Ask students to give themselves a predicted grade only.' },
          { id: 'b', text: 'Have students compare their work with shared success criteria, identify evidence for one strength and one gap, then make a revision before submission.' },
          { id: 'c', text: 'Remove self-assessment because only teachers can judge quality.' },
          { id: 'd', text: 'Ask students whether they enjoyed the task.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Self-assessment becomes formative when learners use criteria and evidence to make an actual improvement decision.',
        incorrectFeedback: 'Reflection is strongest when it is anchored in evidence and leads to action, rather than simply producing a rating or feeling.',
        contentTags: ['Self Assessment', 'Agency', 'Success Criteria'],
      },
      {
        ...shared,
        id: 'afl-11', section: 'afl-agency', questionNumber: 11, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Use peer feedback as a structured learning process rather than peer grading.',
        scenario: 'Students exchange drafts, but their comments are mostly “looks good” or corrections to spelling.',
        question: 'What is the strongest next design move?',
        options: [
          { id: 'a', text: 'Have students assign each other grades.' },
          { id: 'b', text: 'Model feedback using one or two shared criteria, provide a focused protocol, and require the author to decide what feedback to use in revision.' },
          { id: 'c', text: 'Ask for more comments without changing the structure.' },
          { id: 'd', text: 'Only allow feedback from the highest-achieving students.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Peer feedback is a learned practice. Shared criteria, modelling and an author-owned revision decision make it more purposeful and more aligned with Agency and Collaboration.',
        incorrectFeedback: 'More comments or peer grading do not automatically improve learning. Learners need a clear lens for quality and a meaningful way to act on the feedback.',
        contentTags: ['Peer Feedback', 'Collaboration', 'Agency'],
      },
      {
        ...shared,
        id: 'afl-12', section: 'afl-agency', questionNumber: 12, assessmentLevel: 'Synthesis',
        learningObjective: 'Integrate learning intentions, evidence, feedback and learner agency in an Assessment for Learning cycle.',
        scenario: 'A Grade 7 science class is learning to construct explanations from evidence. Students know the success criteria. A quick whole-class check shows that most can select relevant evidence, but many only restate it instead of explaining how it supports the claim. A smaller group is already explaining the connection clearly.',
        question: 'Which sequence best represents Assessment for Learning at AISG?',
        options: [
          { id: 'a', text: 'Give everyone another identical worksheet, grade it, and record the average.' },
          { id: 'b', text: 'Use the evidence to make the reasoning gap visible, model or compare strong explanations, give targeted practice or support based on need, ask students to use the criteria to revise, then gather new evidence before deciding the next move.' },
          { id: 'c', text: 'Move on because students can already select evidence.' },
          { id: 'd', text: 'Give the advanced group free time while the teacher reteaches the whole lesson to everyone else.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The cycle keeps the learning goal visible, uses evidence to personalise the response, gives learners an active role in revision, and then checks whether the next move worked.',
        incorrectFeedback: 'Assessment for Learning is a cycle of clarity, evidence, response and re-checking. The evidence should change what teachers and learners do next.',
        contentTags: ['Synthesis', 'Assessment Cycle', 'Agency', 'Personalisation'],
      },
    ],
  },
];

export const assessmentForLearningQuestions: AiQuestion[] = assessmentForLearningSections.flatMap((section) => section.questions);
