import type { AiQuestion, AiSection } from '@/lib/ai-course';

export const DATA_TO_ACTION_COURSE_VERSION = 'SY2026-27';

const shared = {
  courseVersion: DATA_TO_ACTION_COURSE_VERSION,
  contentOwner: 'Learning & Teaching',
  reviewStatus: 'draft_for_learning_and_teaching_review',
} as const;

export const dataToActionSections: AiSection[] = [
  {
    id: 'data-gap',
    number: 1,
    title: 'Start with the Gap — Not the Solution',
    summary: 'Use evidence to understand where learners are now, where you want them to be, and the gap worth working on.',
    learn: [
      'Data becomes useful when it helps you make a better teaching decision. Start with two questions: What is happening now? and What do we want to be happening? The current state should be described with evidence. The desired state should describe meaningful learner success. The distance between them is the gap. This keeps us from jumping straight to a favourite strategy before we understand the learning need.',
      'A strategy is not a goal. “Use exit tickets three times a week” is an action. “Students can explain and justify their reasoning using evidence” is closer to a desired learner state. Once the gap is clear, choose a manageable action that could plausibly influence it. The point is disciplined curiosity: evidence first, action second.',
    ],
    takeaways: [
      'Start with current state and desired learner state before choosing an action.',
      'Describe the gap with evidence, not assumptions.',
      'A strategy is an action, not the desired state.',
      'Keep the problem small enough to learn from.',
    ],
    questions: [
      {
        ...shared,
        id: 'data-1', section: 'data-gap', questionNumber: 1, assessmentLevel: 'Foundation',
        learningObjective: 'Distinguish evidence-informed problem definition from solution-first thinking.',
        scenario: 'A teacher notices weaker-than-expected writing results and immediately decides to add a new writing app.',
        question: 'What would be the stronger first move?',
        options: [
          { id: 'a', text: 'Choose the app first so students can begin practising immediately.' },
          { id: 'b', text: 'Clarify the current evidence, define the desired learner outcome, and identify the specific gap before selecting an action.' },
          { id: 'c', text: 'Wait until the next reporting cycle so there is more data.' },
          { id: 'd', text: 'Assume the issue is student motivation and add incentives.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Defining the current state, desired state and gap makes the action more likely to address the real learning need.',
        incorrectFeedback: 'Starting with a tool, waiting passively or assuming a cause skips the inquiry step. First make the gap specific enough to act on.',
        contentTags: ['Current State', 'Desired State', 'Gap', 'Inquiry'],
      },
      {
        ...shared,
        id: 'data-2', section: 'data-gap', questionNumber: 2, assessmentLevel: 'Application',
        learningObjective: 'Distinguish a desired state from an action.',
        scenario: 'A team writes its desired state as: “Teachers will use retrieval practice at least twice each week.”',
        question: 'What is the main problem with this statement?',
        options: [
          { id: 'a', text: 'It describes an adult action rather than the learner success the team ultimately wants to see.' },
          { id: 'b', text: 'It is too ambitious because strategies should only be used once a month.' },
          { id: 'c', text: 'It should name a digital tool instead.' },
          { id: 'd', text: 'Desired states should never be measurable.' },
        ],
        answer: 'a',
        correctFeedback: 'Correct. The desired state should describe what meaningful learner success looks like. The strategy belongs in the action plan.',
        incorrectFeedback: 'The key distinction is learner outcome versus adult action. The strategy may be useful, but it is not the end state.',
        contentTags: ['Desired State', 'Action', 'Learner Outcomes'],
      },
    ],
  },
  {
    id: 'data-big-small',
    number: 2,
    title: 'Big Data + Small Data',
    summary: 'Combine broader patterns over time with close evidence of learner experience now.',
    learn: [
      'At AISG, big data helps us see broader patterns over time: common assessments, MAP, report cards, attendance, survey trends, screening information, cohort movement and other repeated measures. Small data helps us understand the learner experience now: student work, demonstrations, exit tickets, conferences, observations, learner voice and targeted progress checks. “Big” and “small” describe different kinds of usefulness, not importance.',
      'Big data can tell you where to look. Small data can help you understand what the pattern may mean in this classroom, for these learners. Neither should stand alone. A broad pattern without close evidence can lead to vague responses; one vivid classroom moment without a broader pattern can lead to overreaction. Strong decisions connect both.',
    ],
    takeaways: [
      'Big data is useful for patterns, baselines and trends over time.',
      'Small data is useful for understanding access, quality and learner response now.',
      'Use one to direct attention and the other to deepen understanding.',
      'Do not treat one source as the whole story.',
    ],
    questions: [
      {
        ...shared,
        id: 'data-3', section: 'data-big-small', questionNumber: 3, assessmentLevel: 'Application',
        learningObjective: 'Match evidence sources to the questions they are best suited to answer.',
        scenario: 'A grade-level trend shows weaker growth in reading comprehension across two assessment windows.',
        question: 'Which next evidence would best help a classroom teacher understand what may be happening?',
        options: [
          { id: 'a', text: 'Only the grade-level average again.' },
          { id: 'b', text: 'Student work, think-alouds, conferences or observation of how students are approaching comprehension tasks.' },
          { id: 'c', text: 'A list of every digital resource used this term.' },
          { id: 'd', text: 'A single student’s highest score.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The broader pattern points to where to look; close evidence of learner thinking helps interpret the pattern and choose a response.',
        incorrectFeedback: 'Repeating the same broad pattern does not explain it. Add evidence that makes learner thinking and experience visible.',
        contentTags: ['Big Data', 'Small Data', 'Student Work', 'Learner Thinking'],
      },
      {
        ...shared,
        id: 'data-4', section: 'data-big-small', questionNumber: 4, assessmentLevel: 'Analysis',
        learningObjective: 'Use multiple evidence types rather than privileging one source.',
        scenario: 'Assessment scores are improving, but student conferences suggest many learners still feel unsure about when to use the strategy independently.',
        question: 'What is the strongest interpretation?',
        options: [
          { id: 'a', text: 'Ignore the conferences because scores are the more objective evidence.' },
          { id: 'b', text: 'Ignore the scores because learner voice matters more.' },
          { id: 'c', text: 'Hold both pieces of evidence together: performance may be improving while independence or confidence still needs attention.' },
          { id: 'd', text: 'Conclude that the assessment must be invalid.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. Different evidence can illuminate different parts of the learner experience. Improvement in one outcome does not erase another need.',
        incorrectFeedback: 'Strong inquiry does not force every source to say the same thing. Ask what each source helps you understand.',
        contentTags: ['Multiple Measures', 'Learner Voice', 'Triangulation'],
      },
    ],
  },
  {
    id: 'data-inquiry',
    number: 3,
    title: 'Notice, Question, Connect — Then Act',
    summary: 'Stay curious long enough to understand a pattern before turning it into a conclusion about learners.',
    learn: [
      'Evidence is strongest when it generates better questions. Notice what you can actually see before explaining why it happened: Which learners are experiencing this? When does it happen? Where are the strengths? What is different when learning is more successful? What else would help us understand? This helps keep observations descriptive rather than deficit-based.',
      'One data point is a signal, not a verdict. Connect sources when the decision matters: student work with observation, an assessment pattern with learner voice, a progress check with information about access and instruction. Look for patterns and exceptions. Data often tells you what is happening more readily than why, so professional judgement should remain provisional and open to new evidence.',
    ],
    takeaways: [
      'Notice before you explain.',
      'Ask what else you need to know before making a high-consequence decision.',
      'Look for strengths, patterns, exceptions and access barriers.',
      'Treat interpretations as hypotheses that evidence can strengthen or change.',
    ],
    questions: [
      {
        ...shared,
        id: 'data-5', section: 'data-inquiry', questionNumber: 5, assessmentLevel: 'Analysis',
        learningObjective: 'Avoid overreacting to a single classroom data point.',
        scenario: 'Most students perform poorly on one exit ticket after a new concept is introduced.',
        question: 'What is the strongest next step?',
        options: [
          { id: 'a', text: 'Immediately reteach the entire unit from the beginning.' },
          { id: 'b', text: 'Inspect the responses for the specific misconception, check another source of evidence, and decide what needs reteaching.' },
          { id: 'c', text: 'Record that the class lacks prerequisite knowledge.' },
          { id: 'd', text: 'Lower the learning goal.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The exit ticket is useful because it narrows the next question. Inspect what students actually did, confirm the pattern and respond precisely.',
        incorrectFeedback: 'One low result is not enough to justify a broad conclusion. Use it to investigate the specific learning need.',
        contentTags: ['Formative Evidence', 'Misconception', 'Inquiry'],
      },
      {
        ...shared,
        id: 'data-6', section: 'data-inquiry', questionNumber: 6, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Use an equity and access lens when interpreting patterns.',
        scenario: 'Multilingual learners participate less often in whole-class discussion, while their written work shows strong conceptual understanding.',
        question: 'Which question is most useful before concluding that participation is a motivation problem?',
        options: [
          { id: 'a', text: 'How can we require them to speak more often?' },
          { id: 'b', text: 'What features of the discussion format, language demands, wait time or participation structures may be affecting access?' },
          { id: 'c', text: 'Which students should lose participation marks?' },
          { id: 'd', text: 'Should we stop using discussion as evidence altogether?' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The contrast between strong conceptual work and lower verbal participation should prompt investigation of access and design before deficit explanations.',
        incorrectFeedback: 'A participation pattern needs context. Examine the learning environment and language demands before locating the problem in the learner.',
        contentTags: ['Equity', 'Access', 'Multilingual Learners', 'Professional Judgement'],
      },
    ],
  },
  {
    id: 'data-monitor',
    number: 4,
    title: 'Act Small, Monitor Deliberately',
    summary: 'Choose a manageable teaching move and decide in advance what evidence would show whether it is helping.',
    learn: [
      'Once the gap is clear, choose one action you can actually test in practice. Strong actions are specific enough to implement consistently and close enough to classroom learning that you can see their effect. Before beginning, decide what success would look like and what evidence will help you notice movement. That evidence might be a short work sample, common prompt, observation note, student self-explanation or repeated check tied directly to the goal.',
      'Progress monitoring does not mean testing more. It means collecting enough comparable evidence, often briefly and repeatedly, to judge whether the action is helping. Name the review point in advance. Ask: What will we look at? How often? What change would be meaningful? What will we do if the evidence improves, stays flat or becomes mixed?',
    ],
    takeaways: [
      'Choose one manageable action rather than several changes at once.',
      'Define evidence of success before implementing the action.',
      'Progress monitoring should be proportionate and tied to the learning goal.',
      'Agree when you will review and what different patterns will mean for the next move.',
    ],
    questions: [
      {
        ...shared,
        id: 'data-7', section: 'data-monitor', questionNumber: 7, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Connect an instructional action to explicit evidence of impact.',
        scenario: 'A teacher introduces worked examples to strengthen mathematical reasoning but has not decided how they will know whether the change is helping.',
        question: 'What would strengthen the plan most?',
        options: [
          { id: 'a', text: 'Add two more strategies at the same time.' },
          { id: 'b', text: 'Define the reasoning evidence to look for in student work and explanations, then set a near-term review point.' },
          { id: 'c', text: 'Wait for end-of-year assessment results.' },
          { id: 'd', text: 'Count how many examples the teacher displays.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The monitoring plan should make the intended learner change visible, not merely confirm that the strategy was used.',
        incorrectFeedback: 'Implementation matters, but impact requires learner evidence tied to the original gap and a clear time to review it.',
        contentTags: ['Action', 'Progress Monitoring', 'Evidence of Impact'],
      },
      {
        ...shared,
        id: 'data-8', section: 'data-monitor', questionNumber: 8, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Distinguish useful progress monitoring from unnecessary data collection.',
        scenario: 'To monitor a small improvement goal, a teacher plans a 30-minute test every day for three weeks.',
        question: 'What is the better design principle?',
        options: [
          { id: 'a', text: 'More data is always better, so keep the daily test.' },
          { id: 'b', text: 'Use the least burdensome repeated evidence that is valid for the learning goal, such as a brief common prompt, work sample or observation routine.' },
          { id: 'c', text: 'Do not collect any evidence until the end of the unit.' },
          { id: 'd', text: 'Only ask students whether they liked the lesson.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Useful monitoring is proportionate. Collect enough valid evidence to see change without allowing measurement to overwhelm learning.',
        incorrectFeedback: 'The goal is not maximum data. It is sufficient, meaningful evidence that supports a timely teaching decision.',
        contentTags: ['Progress Monitoring', 'Proportionality', 'Classroom Evidence'],
      },
    ],
  },
  {
    id: 'data-adjust',
    number: 5,
    title: 'Adjust — New Evidence Becomes the Next Starting Point',
    summary: 'Use what you learn to continue, adapt, stop or refine the next teaching move.',
    learn: [
      'Improvement is a cycle rather than a finish line: act, monitor, reflect, adjust. If the evidence improves, ask what seems worth sustaining. If it stays flat, check whether the action was implemented as intended and whether the original hypothesis still makes sense. If results are mixed, look more closely at who benefited, who did not, and what differed in their experience.',
      'New evidence becomes the next starting point. The aim is not to prove that your first idea was right; it is to learn enough to make the next decision better. Classroom data use is therefore less about producing dashboards and more about disciplined professional learning: noticing, trying, checking, listening and adjusting in ways that improve learner experience and outcomes.',
    ],
    takeaways: [
      'Use evidence to continue, adapt, stop or refine an action.',
      'Check implementation before concluding an approach or learner has failed.',
      'Look at who benefited and who did not.',
      'Treat each cycle as a new starting point for professional learning.',
    ],
    questions: [
      {
        ...shared,
        id: 'data-9', section: 'data-adjust', questionNumber: 9, assessmentLevel: 'Synthesis',
        learningObjective: 'Interpret mixed evidence before scaling or abandoning a strategy.',
        scenario: 'After three weeks, a new discussion routine improves the quality of explanations for many students, but a smaller group contributes less than before.',
        question: 'What is the strongest next move?',
        options: [
          { id: 'a', text: 'Declare the strategy successful because the class average improved.' },
          { id: 'b', text: 'Abandon the strategy immediately because it did not help everyone.' },
          { id: 'c', text: 'Examine implementation and the smaller group’s experience, then adjust the routine while preserving what appears to be working.' },
          { id: 'd', text: 'Ignore the difference because subgroup patterns complicate the data.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. Mixed evidence calls for closer inquiry. Improvement for many learners can be retained while barriers for others are investigated and redesigned.',
        incorrectFeedback: 'Averages can hide important differences. Look at who benefited, who did not, and what can be adjusted before making a broad decision.',
        contentTags: ['Adjustment', 'Equity', 'Subgroup Evidence', 'Synthesis'],
      },
      {
        ...shared,
        id: 'data-10', section: 'data-adjust', questionNumber: 10, assessmentLevel: 'Synthesis',
        learningObjective: 'Integrate current state, multiple evidence sources, action, progress monitoring and adjustment.',
        scenario: 'A Grade 5 teacher sees flat fraction growth in a broader assessment pattern. Exit tickets reveal a recurring equivalence misconception. Student conferences suggest visual models help, but several learners find the language in word problems confusing.',
        question: 'Which response best completes an evidence-to-action cycle?',
        options: [
          { id: 'a', text: 'Buy a new maths programme and wait until the next MAP window to see whether it worked.' },
          { id: 'b', text: 'Lower the fraction goal so more students can show success quickly.' },
          { id: 'c', text: 'Teach the equivalence concept with explicit visual and language supports, monitor a short common task plus learner explanations over the next two weeks, then adjust based on the pattern.' },
          { id: 'd', text: 'Focus only on the students with the lowest assessment scores.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. This response connects the broad pattern to close evidence, selects a focused action, defines near-term monitoring and preserves the expectation that the next move will be adjusted from new evidence.',
        incorrectFeedback: 'Strong classroom data use connects evidence to a focused teaching move and a timely way to learn whether the move is helping.',
        contentTags: ['Evidence to Action', 'Progress Monitoring', 'Adjustment', 'Synthesis'],
      },
    ],
  },
];

export const dataToActionQuestions: AiQuestion[] = dataToActionSections.flatMap((section) => section.questions);
