import type { AiSection } from './ai-course';

export const FACULTY_COURSE_VERSION = 'SY2026-27';

const prompts = [
  ['Which response best applies this principle in a realistic AISG situation?', 'Pause, gather context and choose the handbook-grounded action.', 'Apply a convenient rule without checking context.', 'Wait for a problem to become more serious.', 'c'],
  ['A colleague asks what you would do next. Which approach is strongest?', 'Act alone so the process is faster.', 'Use evidence, involve the appropriate people and document as required.', 'Leave the decision to the student.', 'b'],
  ['Which professional judgement is most defensible?', 'Choose the response that protects dignity, learning and safety while following the process.', 'Use a punitive shortcut.', 'Treat every case identically regardless of context.', 'a'],
  ['What should you do when the handbook expectation is unclear?', 'Improvise and hope it works.', 'Ask an appropriate leader or specialist for guidance before acting.', 'Avoid recording the concern.', 'b'],
  ['Which synthesis best reflects AISG practice?', 'Integrate evidence, student voice, collaboration and the relevant handbook procedure.', 'Solve the issue through a single score or consequence.', 'Wait until the end of the year.', 'a'],
] as const;

const secondaryTopics = [
  ['What Guides Us','Mission, core beliefs, language, inclusion and safeguarding responsibility shape every Secondary decision.',['AISG provides inclusive pathways and a secure, healthy, positive environment. Responsibility for learning is shared.','Use common and home languages purposefully. Inclusion removes barriers; safeguarding is everyone’s responsibility.'],['Connect decisions to mission and dignity.','Remove barriers through asset-based thinking.','Follow safeguarding procedures and mandatory reporting expectations.']],
  ['Communication, Contacts & Concerns','Use authorised channels, protect confidential information and escalate unresolved concerns.',['Communication should be clear, purposeful and audience-appropriate. Protect student information and use school-authorised accounts.','Start with the appropriate person closest to the concern, then escalate through Principal/AP, Head of School and Director.'],['Choose the channel for the purpose.','Share the minimum necessary information.','Escalate unresolved concerns respectfully.']],
  ['Professional Growth, Leadership & Collaboration','Leadership is shared, evidence-informed and connected to student impact.',['Leadership can come from anywhere. Faculty contribute to decisions, trust and collective capacity.','Growth and Evaluation uses goals, evidence, review, observations and reflection. Read and follow current PLC procedures.'],['Leadership is broader than job titles.','Use evidence to examine impact.','Do not invent PLC procedures.']],
  ['The Secondary Learning Programme','Understand pathways, support systems and the distinct role of advisory.',['Secondary serves Grades 6–12; Grades 6–10 use the MYP. Upper pathways include Full Diploma, course certificates and AISG courses; the diploma requires 24 credits.','Course changes use a 10-day drop/add period. Learning Support uses equity, plans and accommodations. Advisors connect and advocate but are not counselors or disciplinarians.'],['Know broad pathway differences.','Implement documented adjustments.','Refer beyond your role when needed.']],
  ['Assessment, Homework, Grading & Reporting','Use evidence, best-fit judgement and transparent reporting without punitive grade practices.',['Excused absences receive make-up opportunities. Late or missing work remains expected, but achievement grades are not lowered as punishment.','Homework needs a purpose. Achievement grades represent academic learning; best-fit judgement weighs progress, trajectory and recent evidence.'],['Do not use grades as behaviour penalties.','Best-fit is not simple averaging.','Report current learning from evidence.']],
  ['Learning Beyond the Classroom & Technology','Experiential learning, technology and recommendations require purpose and professional care.',['China Trips connect service or cultural learning, ATL and relationships. Secondary field trips follow their own procedures and Ramsnet forms.','1:1 MacBooks should enhance learning. Recommendation letters are voluntary, confidential, direct-submission and need at least two weeks.'],['Follow Secondary trip procedures.','Make technology purposeful.','Protect recommendation-letter confidentiality.']],
  ['Daily Life, Attendance & Responsibilities','Reliable routines, attendance and leave processes protect learning and safety.',['Students are ready at 7:55; late arrivals report to the Secondary Office. At least 90% attendance is required for course credit; Secondary is closed campus.','Faculty hours are 7:25–15:40. Follow ADP and absence processes, 48-hour fever-free rule, duties, three events and Wednesday professional learning.'],['Document attendance patterns.','Follow the correct leave pathway.','Supervise duties actively.']],
  ['Campus Safety, Visitors & Operations','Security, onboarding, emergency readiness and purchasing depend on shared procedures.',['IDs and visitor registration support campus security; hosting faculty give advance notice. Professional and Guangzhou Social Buddies have distinct roles.','Every faculty member reads the Science Park Emergency Manual. Use approved purchasing routes; unauthorised personal purchases are not automatically reimbursed.'],['Treat access and visitors as safety work.','Know both buddy roles.','Use approved operational processes.']],
  ['Employee Conduct & Professional Standards','Professional judgement, respectful boundaries and good-faith reporting sustain a safe community.',['The Code of Conduct supports a safe, friendly, respectful environment. Ask when unsure. Sensitive topics may be taught objectively, balanced, age-appropriately and professionally.','Dress is professional, neat, safe and context-appropriate. Whistleblowing covers serious risks; avoid gifts that create conflicts.'],['Ask when a boundary is unclear.','Teach sensitive topics with context.','Raise serious concerns in good faith.']],
  ['Student Behaviour, Integrity, AI & Safety','Respond proportionately, distinguish harm from conflict and protect authentic learning.',['CARE FOR SELF, OTHERS, CAMPUS and careful technology use connect behaviour to dignity. Distinguish conflict, mean behaviour, discrimination and abuse; escalate safeguarding concerns.','Academic integrity is shared. Supervised Study is support. Level 1–3 responses are contextual; searches are administrative. AI detectors are not proof—seek evidence and student explanation.'],['Distinguish conflict from abuse.','Use proportionate responses.','Detectors start conversations; they do not prove guilt.']],
] as const;

function makeCourse(id: string, topics: readonly (readonly [string,string,readonly string[],readonly string[]])[], reviewStatus: string) {
  const sections: AiSection[] = topics.map((topic, si) => ({
    id: `${id}-${si + 1}`, number: si + 1, title: topic[0], summary: topic[1], learn: [...topic[2]], takeaways: [...topic[3]],
    questions: prompts.map((p, qi) => ({ id: `${id}-${si * 5 + qi + 1}`, section: `${si + 1}. ${topic[0]}`, question: p[0], scenario: `A faculty member faces a situation related to ${topic[0].toLowerCase()}.`, options: [{id:'a',text:p[1]},{id:'b',text:p[2]},{id:'c',text:p[3]}], answer: p[4], correctFeedback: `Correct. ${topic[1]} This response follows the handbook and keeps professional judgement at the centre.`, incorrectFeedback: `Not quite. Revisit ${topic[0]} and choose the response that follows the handbook, uses evidence and involves the right people.`, assessmentLevel: qi < 1 ? 'Foundation' : qi < 3 ? 'Application' : 'Synthesis', handbookSection: topic[0], handbookPage: 'Handbook source section', reviewStatus, criticalSafeguarding: [2,6,9,14,19,24,29,34,39,44,45,46,47,48,49].includes(si * 5 + qi + 1) }))
  }));
  return { sections, questions: sections.flatMap((s) => s.questions) };
}

export const { sections: secondarySections, questions: secondaryQuestions } = makeCourse('secondary', secondaryTopics, 'draft_for_secondary_leadership_review');
export const { sections: elementarySections, questions: elementaryQuestions } = makeCourse('elementary', secondaryTopics.map((t, i) => [ ['What Guides Us','Communication & Collaboration','Professional Growth','Elementary Learning Programme','Assessment & Reporting','Learning Beyond the Classroom','Daily Life & Routines','Campus Safety & Operations','Employee Conduct','Student Wellbeing & Integrity'][i], t[1].replaceAll('Secondary','Elementary'), t[2].map((x) => x.replaceAll('Secondary','Elementary').replaceAll('Grades 6–12','Pre-K–Grade 5')), t[3] ] as const), 'draft_for_elementary_leadership_review');
