import type { AiQuestion, AiSection } from '@/lib/ai-course';

export const MULTILINGUAL_LEARNERS_COURSE_VERSION = 'SY2026-27';

const shared = {
  courseVersion: MULTILINGUAL_LEARNERS_COURSE_VERSION,
  contentOwner: 'Learning & Teaching / Student Support Services',
  reviewStatus: 'draft_for_learning_and_teaching_and_student_support_review',
} as const;

export const multilingualLearnersSections: AiSection[] = [
  {
    id: 'mll-assets',
    number: 1,
    title: 'Start with Assets — Not Deficits',
    summary: 'See multilingualism as a resource for learning and separate English proficiency from intelligence, knowledge and potential.',
    learn: [
      'AISG describes its English as an Additional Language program as assets-based. Multilingual learners bring knowledge, identities, cultural perspectives, experiences and ways of making meaning across languages. Developing English is one part of a learner profile; it is not a measure of intelligence, motivation or the complexity of thinking a student can do. WIDA’s Can Do Philosophy uses the same starting point: notice what learners can already do and build from those assets.',
      'This shift matters in everyday classroom decisions. If a learner can reason deeply, explain an idea in another language, interpret a diagram, demonstrate a process or contribute through a supported conversation, that evidence should inform what we design next. The goal is not to wait for English to become “good enough” before offering worthwhile learning. It is to maintain meaningful academic expectations while making participation, comprehension and language development more possible.',
      'At AISG, multilingual support is primarily embedded in the core learning environment, with EAL specialists collaborating with classroom and subject teachers. That makes multilingual learner success a shared responsibility. TLF Personalisation is visible when educators understand learner strengths, identity and needs; Agency grows when learners can use appropriate resources and strategies to participate more independently.',
    ],
    takeaways: [
      'Multilingualism is an asset, not a problem to remediate.',
      'English proficiency is not the same as intelligence, content knowledge or potential.',
      'Maintain worthwhile learning while designing access to it.',
      'Supporting multilingual learners is shared classroom practice, strengthened by EAL expertise.',
    ],
    questions: [
      {
        ...shared,
        id: 'mll-1', section: 'mll-assets', questionNumber: 1, assessmentLevel: 'Foundation',
        learningObjective: 'Recognise an asset-based view of multilingual learners.',
        scenario: 'A student is new to English but demonstrates sophisticated mathematical reasoning through diagrams, gestures and discussion in a home language with a peer.',
        question: 'Which interpretation is most aligned with an asset-based approach?',
        options: [
          { id: 'a', text: 'The student should work only on basic English until academic language is stronger.' },
          { id: 'b', text: 'The student already brings mathematical understanding and linguistic resources that can be used while English develops.' },
          { id: 'c', text: 'The mathematical reasoning should not count because it was not first expressed independently in English.' },
          { id: 'd', text: 'The student should be given easier mathematics so language does not become frustrating.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. An asset-based lens recognises the learner’s existing reasoning, languages and strategies as resources for continued content learning and English development.',
        incorrectFeedback: 'Developing English does not erase the learner’s existing knowledge or thinking. The stronger response preserves meaningful learning and builds from the assets already present.',
        contentTags: ['Asset-Based Practice', 'Multilingualism', 'Learner Strengths'],
      },
      {
        ...shared,
        id: 'mll-2', section: 'mll-assets', questionNumber: 2, assessmentLevel: 'Application',
        learningObjective: 'Separate language proficiency from cognitive demand in classroom design.',
        scenario: 'A Grade 8 learner understands a complex science concept when diagrams and discussion are available, but produces short written English responses.',
        question: 'What is the strongest next design move?',
        options: [
          { id: 'a', text: 'Lower the science goal until the learner can write longer English paragraphs.' },
          { id: 'b', text: 'Keep the science goal, support access and expression, and explicitly develop the language needed to explain the science.' },
          { id: 'c', text: 'Grade only the length of the English response because academic language is the main objective in every subject.' },
          { id: 'd', text: 'Excuse the learner from explanations and assess only recall.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The learner needs access to rigorous science and deliberate language development at the same time. Support the means without lowering the worthwhile thinking.',
        incorrectFeedback: 'Language development and content learning should not be treated as sequential stages. Preserve the science expectation while making the language demands visible and supportable.',
        contentTags: ['Cognitive Demand', 'Access', 'Content Learning'],
      },
    ],
  },
  {
    id: 'mll-content-language',
    number: 2,
    title: 'Make the Language of Learning Visible',
    summary: 'Plan for the language learners need to participate in the content, not just the vocabulary they need to recognise.',
    learn: [
      'Every subject has characteristic ways of using language. Learners compare, justify, classify, explain cause and effect, interpret evidence, describe change, negotiate ideas and build arguments. Supporting multilingual learners therefore involves more than pre-teaching a list of vocabulary. A useful planning move is to ask two connected questions: What is the content learning? What language will students need in order to access, discuss and demonstrate that learning?',
      'The language demand might include a few essential words, but it also includes sentence patterns, text structures, ways of organising ideas, disciplinary conventions and the interaction students are expected to manage. For example, “compare two ecosystems” requires language for similarity, difference and evidence. A strong scaffold might combine a visual model, a worked example, selected vocabulary, sentence starters and structured rehearsal before independent explanation.',
      'This is not about scripting every sentence. The purpose of a scaffold is to make participation more possible while the learner develops greater independence. EAL specialists can help teams identify language demands and co-design supports, but classroom and subject teachers know the content, task and evidence they need to see. The strongest planning brings those perspectives together.',
    ],
    takeaways: [
      'Plan for content learning and the language needed to participate in it.',
      'Language demands include functions, structures and discourse — not only vocabulary.',
      'Use models and scaffolds to open access to meaningful disciplinary thinking.',
      'Co-planning is strongest when content and language expertise meet.',
    ],
    questions: [
      {
        ...shared,
        id: 'mll-3', section: 'mll-content-language', questionNumber: 3, assessmentLevel: 'Application',
        learningObjective: 'Identify the language demand within a content learning goal.',
        scenario: 'Students are learning to compare how two historical sources represent the same event.',
        question: 'Which planning question is most useful for supporting multilingual learners?',
        options: [
          { id: 'a', text: 'Which ten difficult words should every learner memorise before seeing the sources?' },
          { id: 'b', text: 'What language will students need to identify similarities, differences, perspective and evidence while comparing the sources?' },
          { id: 'c', text: 'How can the source texts be replaced with a simpler topic?' },
          { id: 'd', text: 'How many English sentences should every learner be required to write?' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The language demand is tied to the disciplinary thinking students must do: compare, interpret perspective and use evidence.',
        incorrectFeedback: 'Vocabulary and output length can matter, but they do not capture the full language learners need to engage in the intended historical thinking.',
        contentTags: ['Language Demands', 'Disciplinary Language', 'Planning'],
      },
      {
        ...shared,
        id: 'mll-4', section: 'mll-content-language', questionNumber: 4, assessmentLevel: 'Analysis',
        learningObjective: 'Select scaffolds that support the intended content and language without over-simplifying the task.',
        scenario: 'A class must explain how changing one variable affects an investigation. Several multilingual learners understand the practical work but need support producing an explanation in English.',
        question: 'Which support is most purposeful?',
        options: [
          { id: 'a', text: 'Replace the explanation with a matching worksheet so less language is required.' },
          { id: 'b', text: 'Provide a model explanation, highlight the cause-and-effect language, allow oral rehearsal with a partner, then have students construct their own explanation.' },
          { id: 'c', text: 'Give students a complete paragraph to copy so the final English is accurate.' },
          { id: 'd', text: 'Remove the investigation and teach vocabulary in isolation for the whole lesson.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The support preserves the explanation goal while making the language pattern visible and giving learners a chance to rehearse before independent use.',
        incorrectFeedback: 'The strongest scaffold supports access to the original thinking rather than replacing, copying or postponing it.',
        contentTags: ['Scaffolding', 'Language Functions', 'Content and Language'],
      },
    ],
  },
  {
    id: 'mll-interaction',
    number: 3,
    title: 'Design for Input, Interaction and Meaningful Output',
    summary: 'Give learners understandable ways into the content, time to process, and repeated opportunities to use language for real thinking.',
    learn: [
      'Language develops through meaningful use. Multilingual learners need access to comprehensible input — through context, visuals, modelling, demonstration, gesture, examples and well-chosen text support — but they also need opportunities to interact and produce language. Listening to a teacher explain for longer is not the same as participating in the language of the subject.',
      'Structured interaction can lower the risk of public performance while increasing the amount of thinking learners express. Think time, partner rehearsal, purposeful grouping, sentence starters, turn-and-talk routines, collaborative annotation and opportunities to revise an oral response before sharing can all help. The aim is not to protect learners from English; it is to create more successful opportunities to use English for increasingly complex purposes.',
      'Home languages can also be legitimate learning resources. Translanguaging means learners strategically use their full linguistic repertoire to make meaning, connect ideas and communicate. A learner might discuss a concept in Mandarin, annotate key ideas bilingually, compare a term across languages, then produce an English explanation for the intended audience. Purposeful use of home language can strengthen comprehension, identity and belonging while English development remains an explicit part of learning.',
    ],
    takeaways: [
      'Comprehensible input is a starting point; learners also need interaction and meaningful output.',
      'Rehearsal and structured talk can increase both participation and language development.',
      'Home languages can support thinking, access, identity and transfer.',
      'Translanguaging is purposeful use of a full linguistic repertoire, not simply translating everything.',
    ],
    questions: [
      {
        ...shared,
        id: 'mll-5', section: 'mll-interaction', questionNumber: 5, assessmentLevel: 'Application',
        learningObjective: 'Increase meaningful language participation through structured interaction.',
        scenario: 'During whole-class discussion, the same fluent English speakers answer quickly while several multilingual learners rarely contribute.',
        question: 'Which change is most likely to widen meaningful participation?',
        options: [
          { id: 'a', text: 'Ask the multilingual learners to speak first without preparation so expectations are equal.' },
          { id: 'b', text: 'Build in think time and partner rehearsal around a focused prompt before inviting wider sharing.' },
          { id: 'c', text: 'Stop discussion and replace it with silent copying.' },
          { id: 'd', text: 'Allow only fluent speakers to answer so the lesson keeps moving.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Processing time and rehearsal create a lower-risk bridge into public participation while keeping the thinking and language demand meaningful.',
        incorrectFeedback: 'Equal opportunity is not created simply by calling on everyone in the same way. Strong design builds access to the interaction itself.',
        contentTags: ['Interaction', 'Rehearsal', 'Participation'],
      },
      {
        ...shared,
        id: 'mll-6', section: 'mll-interaction', questionNumber: 6, assessmentLevel: 'Analysis',
        learningObjective: 'Use home language strategically to support content learning and English development.',
        scenario: 'A student is preparing a complex geography explanation. She uses a bilingual source, talks through the idea in Cantonese with a peer, then drafts the explanation in English using the class success criteria.',
        question: 'How should this be understood?',
        options: [
          { id: 'a', text: 'As inappropriate because all thinking should happen in English if English is the final language of the task.' },
          { id: 'b', text: 'As purposeful use of the learner’s linguistic repertoire to build understanding before communicating in English.' },
          { id: 'c', text: 'As evidence that the student should not yet work with grade-level geography.' },
          { id: 'd', text: 'As acceptable only if the teacher can personally understand Cantonese.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The learner is using existing language resources to deepen meaning and then meeting the English communication expectation of the task.',
        incorrectFeedback: 'Home-language use can be a strategic bridge into understanding and English output. Teachers do not need to speak every language for learners to draw on those resources responsibly.',
        contentTags: ['Translanguaging', 'Home Language', 'Meaning Making'],
      },
      {
        ...shared,
        id: 'mll-7', section: 'mll-interaction', questionNumber: 7, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Design interaction so multilingual learners contribute ideas rather than occupy passive group roles.',
        scenario: 'In group tasks, one multilingual learner is regularly assigned to make the slides while fluent English speakers discuss the ideas and present the reasoning.',
        question: 'What is the strongest redesign?',
        options: [
          { id: 'a', text: 'Keep the roles because the student is contributing through technology.' },
          { id: 'b', text: 'Structure interdependent roles and rehearsal so every student must contribute to the reasoning, while providing language support for participation.' },
          { id: 'c', text: 'Remove group work for multilingual learners.' },
          { id: 'd', text: 'Ask the learner to present alone without preparation to build confidence.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Collaboration should distribute intellectual contribution, not quietly assign multilingual learners to peripheral tasks. Language support should enable participation in the thinking.',
        incorrectFeedback: 'Participation is not only being busy. The learner needs supported access to the reasoning, decision-making and communication at the centre of the task.',
        contentTags: ['Collaboration', 'Equitable Participation', 'TLF'],
      },
    ],
  },
  {
    id: 'mll-scaffolding',
    number: 4,
    title: 'Scaffold Access — Keep the Challenge',
    summary: 'Use temporary, targeted supports that help learners do more of the intended thinking and become increasingly independent.',
    learn: [
      'A scaffold changes access to a task; it should not automatically reduce the quality of thinking expected. Useful scaffolds can include visuals, chunked text, models, bilingual resources, selected vocabulary, graphic organisers, sentence starters, additional processing time, oral rehearsal, audio support or strategic peer interaction. The right scaffold depends on the learner, the task and the language demand.',
      'The strongest supports are purposeful and temporary. A sentence frame that helps a learner explain cause and effect today may become a lighter prompt tomorrow and disappear when it is no longer needed. WIDA proficiency information and Can Do resources can help educators understand what learners may be able to do with language at different stages, but a proficiency level is not a ceiling and should not become a fixed recipe for every task.',
      'TLF Personalisation does not mean designing a different lesson for every learner. It means making informed adjustments so learners can access worthwhile goals through appropriate pathways and supports. Agency increases when students begin to recognise which language resources help them, select strategies independently and advocate for what they need.',
    ],
    takeaways: [
      'Scaffold the route to the learning rather than automatically lowering the learning goal.',
      'Match supports to the learner, task and language demand.',
      'Use proficiency information as evidence, not as a ceiling or label.',
      'Fade support when learner evidence shows growing independence.',
    ],
    questions: [
      {
        ...shared,
        id: 'mll-8', section: 'mll-scaffolding', questionNumber: 8, assessmentLevel: 'Analysis',
        learningObjective: 'Distinguish scaffolding from reducing cognitive demand.',
        scenario: 'The class is evaluating which renewable-energy option best fits a community. A multilingual learner needs support reading the technical information and explaining a recommendation.',
        question: 'Which response best preserves the intended learning?',
        options: [
          { id: 'a', text: 'Give the learner a separate task naming types of renewable energy.' },
          { id: 'b', text: 'Provide accessible representations of the key information, highlight comparison language, allow rehearsal, and keep the same evaluation and justification goal.' },
          { id: 'c', text: 'Give the learner the correct recommendation to copy.' },
          { id: 'd', text: 'Remove the evidence requirement because academic language is difficult.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The supports reduce unnecessary language barriers while preserving the evaluation, evidence and justification at the centre of the learning.',
        incorrectFeedback: 'A scaffold should make the intended thinking more accessible, not substitute a simpler learning goal or provide the thinking for the learner.',
        contentTags: ['Scaffolding', 'Cognitive Demand', 'Personalisation'],
      },
      {
        ...shared,
        id: 'mll-9', section: 'mll-scaffolding', questionNumber: 9, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Use learner evidence to decide when to adjust or fade a scaffold.',
        scenario: 'A student has used a comparison sentence frame successfully for several weeks and is now independently using varied comparison language in discussion and writing.',
        question: 'What is the strongest next move?',
        options: [
          { id: 'a', text: 'Keep the same frame all year because consistency is safest.' },
          { id: 'b', text: 'Reduce or remove the frame, monitor the learner’s independence, and restore or adapt support if new task demands require it.' },
          { id: 'c', text: 'Remove all language supports in every subject immediately.' },
          { id: 'd', text: 'Wait until the student moves to a new formal proficiency level before changing anything.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Scaffolds should respond to evidence. Fade what the learner no longer needs while recognising that a new genre or disciplinary demand may call for different support.',
        incorrectFeedback: 'Support should not become permanent simply because it once helped, nor disappear everywhere at once. Use current evidence and the demands of the next task.',
        contentTags: ['Gradual Release', 'Independence', 'Responsive Support'],
      },
    ],
  },
  {
    id: 'mll-evidence-collaboration',
    number: 5,
    title: 'Use Evidence, Collaborate and Adjust',
    summary: 'Interpret language and learning evidence carefully, work with specialist expertise, and decide the next support move together.',
    learn: [
      'Multilingual learners produce different kinds of evidence across contexts. Formal language-proficiency information can help us understand patterns in listening, speaking, reading and writing, but classroom evidence matters too: student work, conferences, oral explanations, observations, home-language information, content assessments and how performance changes when barriers are reduced. One score or one English task should not carry more meaning than it can support.',
      'This matters when a learner is struggling. Difficulty completing an English reading or writing task may reflect language development, content understanding, task design, a learning need, or several factors interacting. Avoid quick deficit conclusions. Gather evidence across contexts and, where appropriate, collaborate with EAL and Learning Support colleagues so linguistic and learning needs are considered through distinct but connected lenses.',
      'AISG’s inclusion work emphasises stronger shared language, co-planning and coordinated support for multilingual learners. For the classroom teacher, the practical cycle is simple: notice what the learner can do, clarify the content and language demand, choose a support, gather evidence of access and learning, then adjust. Invite the learner into that process. Their perspective on language, identity, confidence and useful strategies is valuable evidence too.',
    ],
    takeaways: [
      'Use multiple sources of language and learning evidence before drawing conclusions.',
      'Do not treat English-language performance as a simple proxy for content understanding or learning need.',
      'Collaborate with EAL and other support colleagues around shared evidence and clear next moves.',
      'Learner voice helps us understand which supports increase access, confidence and independence.',
    ],
    questions: [
      {
        ...shared,
        id: 'mll-10', section: 'mll-evidence-collaboration', questionNumber: 10, assessmentLevel: 'Analysis',
        learningObjective: 'Use language-proficiency information as one source within a wider learner profile.',
        scenario: 'A teacher sees a student’s language-proficiency level and plans to use the same simplified task for the learner in every subject.',
        question: 'What is the main concern with this approach?',
        options: [
          { id: 'a', text: 'Language-proficiency information should never be used by classroom teachers.' },
          { id: 'b', text: 'A proficiency level can inform planning, but it does not define the learner’s content knowledge or prescribe one support for every task.' },
          { id: 'c', text: 'All multilingual learners should receive identical scaffolds regardless of proficiency.' },
          { id: 'd', text: 'Only summative content grades should influence support.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Proficiency information is useful evidence, but planning still requires the specific content goal, language demand, learner strengths and current classroom evidence.',
        incorrectFeedback: 'The issue is not using language data; it is overgeneralising from it. A proficiency level should inform professional judgement rather than replace it.',
        contentTags: ['Language Data', 'Learner Profile', 'Professional Judgement'],
      },
      {
        ...shared,
        id: 'mll-11', section: 'mll-evidence-collaboration', questionNumber: 11, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Avoid premature conclusions when language and learning needs may intersect.',
        scenario: 'A multilingual learner struggles with English reading and written directions. In oral explanations with visuals and in the home language, the learner demonstrates stronger conceptual understanding. A teacher wonders whether there may also be a learning difficulty.',
        question: 'What is the strongest next step?',
        options: [
          { id: 'a', text: 'Assume the difficulty is entirely caused by English development and wait a year.' },
          { id: 'b', text: 'Assume a learning disability because progress in English is slower than classmates.' },
          { id: 'c', text: 'Gather evidence across languages, tasks and contexts, review the effect of appropriate language supports, and collaborate with EAL and Learning Support colleagues before drawing a conclusion.' },
          { id: 'd', text: 'Remove the student from grade-level content until the cause is known.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. A careful dual lens protects against both under-identifying and over-identifying needs. The team needs evidence that distinguishes language demands, learning barriers and their interaction.',
        incorrectFeedback: 'Neither “it is only language” nor “it must be a learning difficulty” is supported by one pattern. Gather cross-context evidence and use specialist collaboration.',
        contentTags: ['EAL and Learning Support', 'Evidence', 'Learner Variability'],
      },
      {
        ...shared,
        id: 'mll-12', section: 'mll-evidence-collaboration', questionNumber: 12, assessmentLevel: 'Synthesis',
        learningObjective: 'Integrate asset-based practice, language-conscious planning, translanguaging, scaffolding and evidence in one classroom design.',
        scenario: 'A Grade 6 science class will investigate how human activity affects local water systems. Several students are developing English at different stages. The final learning requires students to analyse evidence and justify a recommendation to an authentic audience.',
        question: 'Which plan best reflects strong support for multilingual learners at AISG?',
        options: [
          { id: 'a', text: 'Give multilingual learners a separate vocabulary worksheet and a simpler final task while everyone else completes the investigation.' },
          { id: 'b', text: 'Keep the shared analysis goal; identify the language needed to interpret evidence and justify recommendations; use visuals, models and selected vocabulary; allow strategic home-language meaning-making and structured rehearsal; provide targeted temporary scaffolds; gather evidence of both content understanding and language use; then adjust support with the learner and EAL colleagues.' },
          { id: 'c', text: 'Use only English at every stage so the task provides maximum exposure, then grade all learners against the same unsupported writing conditions.' },
          { id: 'd', text: 'Have an EAL specialist take full responsibility for planning and assessing the multilingual learners separately.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The plan keeps rigorous shared learning, integrates content and language, uses learners’ linguistic assets, creates supported interaction, responds to evidence and treats specialist expertise as collaborative rather than separate.',
        incorrectFeedback: 'Strong multilingual support is not a separate easier curriculum, English-only exposure, or specialist-only responsibility. It is inclusive classroom design strengthened by language expertise and evidence.',
        contentTags: ['Synthesis', 'Inclusive Design', 'Collaboration', 'TLF'],
      },
    ],
  },
];

export const multilingualLearnersQuestions: AiQuestion[] = multilingualLearnersSections.flatMap((section) => section.questions);
