import type { AiQuestion, AiSection } from '@/lib/ai-course';
import { TEACHER_GROWTH_DOMAIN_COURSE_VERSION } from '@/lib/teacher-growth-domain-courses';

const shared = {
  courseVersion: TEACHER_GROWTH_DOMAIN_COURSE_VERSION,
  contentOwner: 'Learning & Teaching',
  reviewStatus: 'draft_for_learning_and_teaching_review',
} as const;

export const growthDomain3Sections: AiSection[] = [
  {
    id: 'growth-d3-continuum', number: 1, title: 'Read Transformative Learning Through Student Experience',
    summary: 'Use Domain 3 to notice how thinking, discourse, inquiry and authentic application become deeper, more independent and more consequential.',
    learn: [
      'Domain 3 is Transformative, Culturally Responsive Learning in Action. Across the continuum, practice moves from recall, teacher-led participation and prescribed pathways toward deeper thinking, inclusive knowledge-building, learner-led inquiry and meaningful application. In Domains 1–3, the framework asks us to judge practice primarily through student experience and outcomes: what students say, do, create, justify, transfer and influence.',
      'The continuum is developmental rather than a checklist. Stronger practice is not simply “more difficult” or “more student choice.” The important shifts are cognitive depth, broader and more equitable participation, independent transfer, meaningful learner decisions, diverse perspectives, authenticity and real-world impact. The most useful reflection is: what are learners increasingly able to do without the teacher carrying all of the thinking and direction?',
    ],
    takeaways: ['Look for student thinking and transfer, not only engaging activities.', 'Later levels increase learner independence and ownership.', 'Choice matters when it shapes inquiry and learning decisions.', 'Transformational practice is visible through authentic application and impact.'],
    questions: [
      { ...shared, id: 'growth-d3-1', section: 'growth-d3-continuum', questionNumber: 1, assessmentLevel: 'Foundation', learningObjective: 'Recognise the student-centred evidence base of Domain 3.', scenario: 'A teacher describes a lesson as transformative because students used several digital tools and appeared busy.', question: 'Which evidence would better support a Domain 3 reflection?', options: [{id:'a',text:'The number of tools students opened.'},{id:'b',text:'Whether students explained reasoning, built on ideas, made meaningful decisions and applied learning in relevant contexts.'},{id:'c',text:'How colourful the final products were.'},{id:'d',text:'Whether the teacher used every planned activity.'}], answer:'b', correctFeedback:'Correct. Domain 3 is grounded in observable learner thinking, participation, inquiry, transfer and application rather than the presence of particular activities or tools.', incorrectFeedback:'The framework asks what students were actually thinking, doing and applying. Activity features alone do not demonstrate transformative learning.', contentTags:['Domain 3','Student Evidence','Transformative Learning'] },
      { ...shared, id: 'growth-d3-2', section: 'growth-d3-continuum', questionNumber: 2, assessmentLevel: 'Application', learningObjective: 'Identify a realistic developmental next move.', scenario: 'Students contribute to teacher-led discussion and explain ideas when prompted, but rarely build on one another’s thinking or initiate questions.', question: 'What is the strongest next move?', options: [{id:'a',text:'Ask the teacher to speak for longer so the discussion has more content.'},{id:'b',text:'Use structures and questioning that help students respond to one another, widen participation and increasingly sustain the thinking themselves.'},{id:'c',text:'Remove all teacher guidance immediately.'},{id:'d',text:'Grade students only on how often they speak.'}], answer:'b', correctFeedback:'Correct. The continuum deepens toward broadly distributed participation, students building on ideas and increasingly sustaining discourse independently.', incorrectFeedback:'The next move should deepen learner participation and ownership of thinking rather than simply increase teacher talk or participation pressure.', contentTags:['Domain 3','Next Move','Discourse'] },
    ],
  },
  {
    id: 'growth-d3-thinking', number: 2, title: '3a. Cognitive Demand & Thinking',
    summary: 'Move from recall and guided analysis toward justification, problem-solving, transfer and student-led complex thinking.',
    learn: [
      'In 3a, Exploring practice is dominated by recall or compliance, with surface-level responses. Building introduces structured questioning and modelling so students begin guided analysis and make connections. Embedding requires analysis, problem-solving and creation; students explain and justify reasoning, use multiple strategies and the teacher checks understanding during learning.',
      'Extending is visible when students independently transfer thinking strategies to new or unfamiliar situations, initiate deeper questions and adapt strategies when challenged. Transformational practice enables students to lead complex or interdisciplinary thinking, generate original ideas and design solutions. The developmental shift is from participating in teacher-structured thinking toward increasingly owning, transferring and extending the thinking.',
    ],
    takeaways: ['Rigor is visible in the quality of thinking, not the quantity of work.', 'Embedding includes explanation, justification and multiple strategies.', 'Extending depends on independent transfer to unfamiliar situations.', 'Transformational thinking includes original solutions and student-led complex inquiry.'],
    questions: [
      { ...shared, id:'growth-d3-3', section:'growth-d3-thinking', questionNumber:3, assessmentLevel:'Application', learningObjective:'Distinguish recall from deeper cognitive demand.', scenario:'Students complete twenty questions that all require recalling definitions from the previous lesson.', question:'Which redesign most strongly moves toward Embedding 3a?', options:[{id:'a',text:'Add ten more definitions.'},{id:'b',text:'Ask students to analyse a new situation, justify reasoning and compare more than one possible approach.'},{id:'c',text:'Make the worksheet worth more points.'},{id:'d',text:'Shorten the time limit.'}], answer:'b', correctFeedback:'Correct. Embedding 3a emphasises analysis, problem-solving, creation and students explaining and justifying reasoning.', incorrectFeedback:'More volume, points or speed do not necessarily deepen cognition. The continuum looks for analysis, reasoning and problem-solving.', contentTags:['3a','Cognitive Demand','Embedding'] },
      { ...shared, id:'growth-d3-4', section:'growth-d3-thinking', questionNumber:4, assessmentLevel:'Professional Judgement', learningObjective:'Recognise Extending cognitive transfer.', scenario:'After learning one strategy for analysing evidence, students independently adapt it to a new subject context, explain why they changed it and pose new questions the teacher had not supplied.', question:'What makes this later-continuum evidence?', options:[{id:'a',text:'Students completed the task quickly.'},{id:'b',text:'Students independently transferred and adapted thinking, then initiated deeper questions.'},{id:'c',text:'The teacher did not speak.'},{id:'d',text:'The task used technology.'}], answer:'b', correctFeedback:'Correct. Independent transfer, adaptation and deeper questioning are central Extending indicators in 3a.', incorrectFeedback:'The important evidence is the transfer and adaptation of thinking, not speed, silence or technology use.', contentTags:['3a','Extending','Transfer'] },
    ],
  },
  {
    id: 'growth-d3-discourse', number: 3, title: '3b. Inclusive Discourse & Collaboration',
    summary: 'Move from discussion dominated by a few voices toward collaborative knowledge-building that includes and extends diverse perspectives.',
    learn: [
      'At the Exploring end of 3b, discussion is largely teacher-led and a small number of students dominate. Building introduces routines and prompts that widen participation. Embedding is visible when participation is broadly distributed, students respond to one another and listen respectfully, while teacher questioning extends thinking.',
      'Extending shifts more responsibility to students: they sustain discussion, build on others’ ideas and ensure multiple perspectives are included without prompting. Transformational practice becomes a knowledge-building community in which students facilitate discussion, challenge and extend ideas, and integrate diverse perspectives. Collaboration therefore deepens from turn-taking into collective thinking.',
    ],
    takeaways: ['Participation should become broader and more equitable.', 'Embedding includes students responding to one another, not only to the teacher.', 'Extending includes sustained learner-led collaboration.', 'Transformational discourse integrates diverse perspectives to build knowledge.'],
    questions: [
      { ...shared, id:'growth-d3-5', section:'growth-d3-discourse', questionNumber:5, assessmentLevel:'Analysis', learningObjective:'Distinguish participation from collaborative knowledge-building.', scenario:'Every student speaks once in a discussion, but each response is directed only to the teacher and students do not refer to one another’s ideas.', question:'What is the strongest reflection?', options:[{id:'a',text:'Collaboration is fully embedded because everyone spoke.'},{id:'b',text:'Participation has widened, but the next move is helping students listen, respond to and build on one another’s thinking.'},{id:'c',text:'Only the strongest speakers should continue the discussion.'},{id:'d',text:'The teacher should stop asking questions entirely.'}], answer:'b', correctFeedback:'Correct. 3b deepens beyond distributed participation toward students building on ideas and sustaining collaborative discourse.', incorrectFeedback:'Speaking turns are useful evidence, but later practice depends on learners thinking with one another, not simply taking turns.', contentTags:['3b','Discourse','Collaboration'] },
      { ...shared, id:'growth-d3-6', section:'growth-d3-discourse', questionNumber:6, assessmentLevel:'Professional Judgement', learningObjective:'Recognise Transformational discourse.', scenario:'Students facilitate a seminar, invite missing perspectives, respectfully challenge assumptions and synthesise several viewpoints into a new shared explanation.', question:'Which feature most strongly signals Transformational 3b?', options:[{id:'a',text:'The discussion lasted a long time.'},{id:'b',text:'Students are leading knowledge-building and integrating diverse perspectives.'},{id:'c',text:'The teacher is sitting down.'},{id:'d',text:'Students agree with one another.'}], answer:'b', correctFeedback:'Correct. Transformational 3b describes students leading discourse, extending ideas and integrating diverse perspectives.', incorrectFeedback:'The strongest evidence is learner-led knowledge-building and perspective integration, not duration, teacher position or agreement.', contentTags:['3b','Transformational','Knowledge Building'] },
    ],
  },
  {
    id: 'growth-d3-inquiry', number: 4, title: '3c. Choice, Inquiry & Creativity',
    summary: 'Move from prescribed pathways toward meaningful decisions, learner-generated questions, independent inquiry and authentic creation.',
    learn: [
      'In 3c, Exploring practice offers limited choice and creativity: students follow prescribed pathways. Building introduces guided inquiry and bounded choices. Embedding creates meaningful opportunities for inquiry and creativity; students generate ideas, ask questions and make decisions about their approach with teacher modelling and support.',
      'Extending is visible when students independently initiate and manage inquiry, adapt it as their understanding changes and sustain learning over time. Transformational practice empowers students to design learning pathways, innovate, create authentic products and connect inquiry to real-world contexts. The continuum therefore distinguishes cosmetic choice from choices that influence thinking, inquiry and creation.',
    ],
    takeaways: ['Choice is meaningful when it influences learning decisions.', 'Embedding includes learner-generated questions and original work.', 'Extending includes independently managed inquiry.', 'Transformational practice connects learner-designed pathways with authentic creation.'],
    questions: [
      { ...shared, id:'growth-d3-7', section:'growth-d3-inquiry', questionNumber:7, assessmentLevel:'Application', learningObjective:'Distinguish cosmetic from meaningful choice.', scenario:'Students may choose a font and background colour, but the question, process, resources and final response are identical for everyone.', question:'How does this sit within 3c?', options:[{id:'a',text:'It is Transformational because any choice demonstrates agency.'},{id:'b',text:'The choices are limited and do not yet meaningfully shape inquiry, creativity or approach.'},{id:'c',text:'Choice should be removed completely.'},{id:'d',text:'The task is automatically authentic because students designed the slide.'}], answer:'b', correctFeedback:'Correct. Later 3c practice is visible when learners generate ideas, questions and meaningful decisions about inquiry and creation.', incorrectFeedback:'Choice itself is not the endpoint. The continuum looks for choices that influence learning pathways, inquiry and creative work.', contentTags:['3c','Choice','Inquiry'] },
      { ...shared, id:'growth-d3-8', section:'growth-d3-inquiry', questionNumber:8, assessmentLevel:'Professional Judgement', learningObjective:'Identify Extending inquiry.', scenario:'Students independently refine their inquiry questions as evidence changes, choose appropriate methods and manage the work over several weeks.', question:'What is the strongest continuum interpretation?', options:[{id:'a',text:'This is mainly Building because the teacher originally introduced the topic.'},{id:'b',text:'This reflects Extending because students independently initiate, manage and adapt inquiry over time.'},{id:'c',text:'It is only evidence of time management.'},{id:'d',text:'It cannot be strong practice unless every student studies a different topic.'}], answer:'b', correctFeedback:'Correct. Extending 3c emphasises independent inquiry management and adaptation as understanding develops.', incorrectFeedback:'The key evidence is learner ownership and adaptation of inquiry over time, not complete teacher absence or total topic freedom.', contentTags:['3c','Extending','Learner Inquiry'] },
    ],
  },
  {
    id: 'growth-d3-authentic', number: 5, title: '3d. Authentic Application & Social Impact',
    summary: 'Move from abstract or teacher-provided relevance toward transfer, authentic audiences, meaningful action and visible impact.',
    learn: [
      'The 3d continuum begins with learning that feels disconnected from real life. Building makes structured real-world connections and allows students to apply knowledge to familiar examples. Embedding designs meaningful application: students work for real or simulated audiences, learning has clear purpose, and students can explain its connection to relevant contexts.',
      'Extending is visible when students independently transfer and adapt learning to new and unfamiliar real-world situations. Transformational practice goes further: students take meaningful action on real issues, engage authentic audiences or communities and create visible impact beyond the classroom. Authenticity is therefore more than adding a real-world story to a worksheet; it changes the purpose, audience, application or consequence of the learning.',
    ],
    takeaways: ['Relevance should be meaningful, not decorative.', 'Embedding includes clear purpose and authentic or simulated audiences.', 'Extending includes independent transfer to unfamiliar real-world contexts.', 'Transformational practice includes meaningful action and visible impact.'],
    questions: [
      { ...shared, id:'growth-d3-9', section:'growth-d3-authentic', questionNumber:9, assessmentLevel:'Analysis', learningObjective:'Distinguish decorative context from authentic application.', scenario:'A worksheet uses a fictional “real-world” shopping story, but students still complete isolated calculations with no audience, decision or meaningful application.', question:'What is the strongest reflection?', options:[{id:'a',text:'The task is authentic because it mentions shopping.'},{id:'b',text:'The context may add familiarity, but authenticity remains limited because the learning has little meaningful purpose, audience or consequence.'},{id:'c',text:'All mathematics should involve community action.'},{id:'d',text:'Authentic learning cannot include simulations.'}], answer:'b', correctFeedback:'Correct. 3d distinguishes surface context from meaningful application, purpose, audiences and eventually real-world impact.', incorrectFeedback:'A real-world label does not automatically create authenticity. The continuum asks how learners actually apply knowledge and for what purpose.', contentTags:['3d','Authenticity','Application'] },
      { ...shared, id:'growth-d3-10', section:'growth-d3-authentic', questionNumber:10, assessmentLevel:'Professional Judgement', learningObjective:'Recognise Extending transfer.', scenario:'Students use a concept learned in class to analyse an unfamiliar community problem, adapt the concept to the new constraints and justify their recommendation.', question:'Which feature most strongly reflects Extending 3d?', options:[{id:'a',text:'Students used the same worksheet in a different location.'},{id:'b',text:'Students independently transferred and adapted learning to a new real-world situation.'},{id:'c',text:'The task happened outside the classroom.'},{id:'d',text:'Students worked in groups.'}], answer:'b', correctFeedback:'Correct. Extending 3d is defined by independent transfer and application to new and unfamiliar real-world contexts.', incorrectFeedback:'The strongest evidence is independent transfer and adaptation of learning, not location or grouping.', contentTags:['3d','Extending','Transfer'] },
      { ...shared, id:'growth-d3-11', section:'growth-d3-authentic', questionNumber:11, assessmentLevel:'Professional Judgement', learningObjective:'Recognise Transformational social impact.', scenario:'Students investigate accessibility on campus, consult users, propose changes to relevant decision-makers and revise their solution after feedback. Several changes are adopted.', question:'Why does this move toward Transformational 3d?', options:[{id:'a',text:'The students produced a polished presentation.'},{id:'b',text:'The learning led to meaningful action with authentic stakeholders and visible impact beyond the classroom.'},{id:'c',text:'The project took several weeks.'},{id:'d',text:'Students used digital tools.'}], answer:'b', correctFeedback:'Correct. Transformational 3d includes meaningful action, authentic audiences or communities and visible real-world impact.', incorrectFeedback:'Duration, polish and technology are secondary. The defining evidence is meaningful action and impact.', contentTags:['3d','Transformational','Taking Action'] },
      { ...shared, id:'growth-d3-12', section:'growth-d3-authentic', questionNumber:12, assessmentLevel:'Synthesis', learningObjective:'Identify a coherent next move across Domain 3.', scenario:'Students explain and justify thinking well, but discussion is still teacher-led, inquiry pathways are prescribed and real-world application is mostly simulated.', question:'Which next move is most coherent with the continuum?', options:[{id:'a',text:'Increase the amount of content coverage.'},{id:'b',text:'Preserve the strong cognitive demand while designing one learning experience where students build on one another’s ideas, make meaningful inquiry decisions and apply learning to a more authentic purpose or audience.'},{id:'c',text:'Remove all structure and let students decide everything.'},{id:'d',text:'Add more technology to make the task feel transformative.'}], answer:'b', correctFeedback:'Correct. A strong next move builds from existing strengths and deepens learner ownership, collaboration and authentic application without abandoning purposeful design.', incorrectFeedback:'Continuum-based growth builds from current strengths and targets the next learner-experience gap. More content, technology or complete removal of structure does not necessarily do that.', contentTags:['Domain 3','Synthesis','Next Move'] },
    ],
  },
];

export const growthDomain4Sections: AiSection[] = [
  {
    id:'growth-d4-continuum', number:1, title:'Read Professional Impact Through Growth, Evidence & Influence',
    summary:'Use Domain 4 to connect feedback, evidence, reflection, collaboration and partnership with improving student learning and wider professional impact.',
    learn:[
      'Domain 4 is Collaborative Planning, Reflection & Professional Impact. It differs slightly from Domains 1–3: student experience still matters, but later levels also include increasing professional influence, collaboration and contribution to shared practice across teams and the school. Growth therefore becomes visible both in what students experience and in how educators strengthen collective capacity.',
      'The continuum moves from isolated or reactive practice toward purposeful cycles of feedback, evidence, learner reflection, collaboration and reciprocal partnership. Extending and Transformational practice are not simply “doing more.” They show practices becoming coherent across contexts, shared with others and increasingly owned by learners, teams and the wider learning community.',
    ],
    takeaways:['Domain 4 includes student impact and professional influence.', 'Later levels include greater coherence across teams and contexts.', 'Evidence should lead to adjustment, not only collection.', 'Professional growth is collaborative, reflective and connected to student learning.'],
    questions:[
      { ...shared, id:'growth-d4-1', section:'growth-d4-continuum', questionNumber:1, assessmentLevel:'Foundation', learningObjective:'Recognise what distinguishes Domain 4.', scenario:'A teacher is reflecting on Domain 4 and wants to identify evidence of growth.', question:'Which evidence set is strongest?', options:[{id:'a',text:'Only a list of professional-development sessions attended.'},{id:'b',text:'Changes in student learning plus evidence that feedback, reflection, collaboration or shared practice influenced what happened next.'},{id:'c',text:'How many emails the teacher sent.'},{id:'d',text:'Whether the teacher worked independently.'}], answer:'b', correctFeedback:'Correct. Domain 4 connects professional practice with student impact and, at later levels, increasing influence and coherence beyond one classroom.', incorrectFeedback:'Domain 4 is not about activity volume. It asks how professional reflection, evidence and collaboration improve learning and shared practice.', contentTags:['Domain 4','Professional Impact','Evidence'] },
      { ...shared, id:'growth-d4-2', section:'growth-d4-continuum', questionNumber:2, assessmentLevel:'Application', learningObjective:'Identify a realistic next move in Domain 4.', scenario:'A teacher collects useful student evidence and reflects privately, but does not yet use colleagues, feedback or shared planning to strengthen the response.', question:'What is a strong next move?', options:[{id:'a',text:'Collect more evidence without changing practice.'},{id:'b',text:'Use the evidence in a focused professional dialogue or collaborative planning cycle, then examine whether the shared next move improves student learning.'},{id:'c',text:'Wait until the end of the year to discuss it.'},{id:'d',text:'Replace reflection with a checklist.'}], answer:'b', correctFeedback:'Correct. Domain 4 deepens when evidence and reflection become part of purposeful professional dialogue, collaboration and improvement.', incorrectFeedback:'The next move should connect evidence to action and collaborative learning, not simply increase collection or delay the response.', contentTags:['Domain 4','Collaboration','Next Move'] },
    ],
  },
  {
    id:'growth-d4-feedback', number:2, title:'4a. Feedback & Inclusive Growth Practices',
    summary:'Move from vague or delayed feedback toward timely, reciprocal feedback cultures that learners use to improve independently.',
    learn:[
      'In 4a, Exploring feedback is inconsistent or unclear and students are unsure what to improve. Building makes next steps clearer and students act on feedback with guidance. Embedding makes feedback timely and specific during learning; students independently revise work and improve outcomes without waiting for prompts.',
      'Extending includes consistent feedback practices across contexts, students seeking and applying feedback independently and peer feedback becoming part of learning. Transformational practice is a reciprocal, continuous feedback culture in which learners give and receive feedback, use it to set goals and drive ongoing improvement. The developmental shift is from feedback as teacher information toward feedback as a learning practice students increasingly own.',
    ],
    takeaways:['Useful feedback identifies a next move.', 'Embedding includes students independently acting on feedback.', 'Extending includes transfer of feedback practices across contexts.', 'Transformational practice makes feedback reciprocal and continuous.'],
    questions:[
      { ...shared, id:'growth-d4-3', section:'growth-d4-feedback', questionNumber:3, assessmentLevel:'Application', learningObjective:'Recognise Embedding feedback practice.', scenario:'Students receive specific feedback during drafting, revise independently and can explain how the change improved the quality of their work.', question:'Which continuum evidence is most visible?', options:[{id:'a',text:'Exploring'},{id:'b',text:'Embedding'},{id:'c',text:'Only Transformational'},{id:'d',text:'No continuum evidence because the teacher provided feedback.'}], answer:'b', correctFeedback:'Correct. Timely, specific feedback used during learning, with students independently improving work, closely matches Embedding 4a.', incorrectFeedback:'The teacher can still provide feedback in strong practice. What matters is that students understand and use it independently during learning.', contentTags:['4a','Feedback','Embedding'] },
      { ...shared, id:'growth-d4-4', section:'growth-d4-feedback', questionNumber:4, assessmentLevel:'Professional Judgement', learningObjective:'Recognise movement toward a feedback culture.', scenario:'Across subjects, students routinely seek feedback, give peers specific evidence-based suggestions and use feedback to set their own next goals.', question:'What is most significant?', options:[{id:'a',text:'Students are receiving more comments.'},{id:'b',text:'Feedback practices are transferring across contexts and becoming reciprocal and learner-owned.'},{id:'c',text:'Teachers no longer need to give feedback.'},{id:'d',text:'Every piece of work should now receive peer feedback.'}], answer:'b', correctFeedback:'Correct. Later 4a practice includes consistency across contexts, peer feedback, student goal-setting and reciprocal improvement.', incorrectFeedback:'The key shift is ownership and transfer of feedback practices, not simply a larger volume of comments or removal of teacher feedback.', contentTags:['4a','Extending','Feedback Culture'] },
    ],
  },
  {
    id:'growth-d4-evidence', number:3, title:'4b. Evidence, Data & Responsive Planning',
    summary:'Move from collecting evidence with little impact toward responsive, shared evidence practices that improve learning in real time and across contexts.',
    learn:[
      'At the Exploring end of 4b, evidence is collected but instruction remains largely unchanged. Building introduces periodic changes based on some data and targeted support. Embedding uses multiple sources of evidence so teaching changes during learning and planning responds to student needs.',
      'Extending aligns evidence use across teams and contexts so students experience more consistent adjustments. Transformational practice embeds collaborative data use in learning routines: evidence drives continuous improvement, students use evidence to guide learning and adjust strategies independently. The key question is always what changed because of the evidence — for the teacher, the team or the learner.',
    ],
    takeaways:['Evidence matters when it changes planning or learning.', 'Embedding uses multiple evidence sources responsively.', 'Extending creates consistency across teams and contexts.', 'Transformational practice includes learners using evidence themselves.'],
    questions:[
      { ...shared, id:'growth-d4-5', section:'growth-d4-evidence', questionNumber:5, assessmentLevel:'Analysis', learningObjective:'Distinguish collection from responsive evidence use.', scenario:'A team reviews common assessment data every month but continues teaching the same sequence regardless of patterns in the evidence.', question:'What is the strongest reflection?', options:[{id:'a',text:'The evidence practice is strong because the meeting occurs regularly.'},{id:'b',text:'Evidence is being collected and discussed, but its impact is limited because planning and support are not changing in response.'},{id:'c',text:'The team should collect more spreadsheets.'},{id:'d',text:'Common evidence is not useful in teacher growth.'}], answer:'b', correctFeedback:'Correct. 4b develops from collection toward responsive planning and visible adjustments based on multiple sources of evidence.', incorrectFeedback:'Frequency of review is not enough. The continuum asks what instructional or learning decisions change because of the evidence.', contentTags:['4b','Evidence','Responsive Planning'] },
      { ...shared, id:'growth-d4-6', section:'growth-d4-evidence', questionNumber:6, assessmentLevel:'Professional Judgement', learningObjective:'Recognise Extending evidence practice across teams.', scenario:'A grade-level team uses common student work, observations and learner voice to agree a response, then checks whether students experience the adjustment consistently across classes.', question:'What moves this toward Extending?', options:[{id:'a',text:'The team used a spreadsheet.'},{id:'b',text:'Evidence use is aligned across the team and improves consistency and responsiveness across contexts.'},{id:'c',text:'Every teacher used exactly the same lesson script.'},{id:'d',text:'The meeting lasted more than an hour.'}], answer:'b', correctFeedback:'Correct. Extending 4b explicitly includes aligned evidence use and more consistent adjustment across teams and contexts.', incorrectFeedback:'The important evidence is shared, responsive use of evidence across contexts, not identical teaching or meeting length.', contentTags:['4b','Extending','Team Evidence'] },
    ],
  },
  {
    id:'growth-d4-reflection', number:4, title:'4c. Learner Reflection & Ownership of Growth',
    summary:'Move from surface reflection toward learners independently monitoring, adjusting and connecting growth to identity, purpose and long-term goals.',
    learn:[
      'In 4c, Exploring reflection is brief, surface-level and dependent on prompts. Building introduces structured reflection and simple goal-setting. Embedding makes reflection meaningful: students monitor their own progress, adjust goals independently and use reflection to improve learning.',
      'Extending is visible when students use and adapt reflection strategies across different learning situations. Transformational practice connects reflection with identity, purpose and long-term growth: learners set long-term goals, connect learning to personal purpose and take ownership of their learning journeys. Reflection therefore develops from a teacher-assigned activity into a transferable learner capability.',
    ],
    takeaways:['Reflection should inform improvement, not simply record feelings.', 'Embedding includes learner monitoring and independent goal adjustment.', 'Extending includes transfer of reflection strategies.', 'Transformational reflection connects growth with identity and purpose.'],
    questions:[
      { ...shared, id:'growth-d4-7', section:'growth-d4-reflection', questionNumber:7, assessmentLevel:'Application', learningObjective:'Recognise meaningful learner reflection.', scenario:'Students complete a reflection form after every unit but mostly write “I did well” or “I need to work harder.”', question:'What is the strongest next move?', options:[{id:'a',text:'Require longer reflections.'},{id:'b',text:'Anchor reflection in evidence and criteria so students identify specific strengths, next steps and goals they can monitor.'},{id:'c',text:'Remove reflection because students are not good at it yet.'},{id:'d',text:'Grade the reflection more heavily.'}], answer:'b', correctFeedback:'Correct. 4c deepens when reflection becomes evidence-based, connected to goals and useful for improving learning.', incorrectFeedback:'More length or grading does not necessarily improve reflection. The continuum points toward evidence, goals, monitoring and learner ownership.', contentTags:['4c','Reflection','Goal Setting'] },
      { ...shared, id:'growth-d4-8', section:'growth-d4-reflection', questionNumber:8, assessmentLevel:'Professional Judgement', learningObjective:'Recognise Transformational learner ownership.', scenario:'A student uses evidence from several contexts to revise a long-term goal, explains how the goal connects to personal purpose and selects strategies for the next phase without prompting.', question:'Why is this later-continuum evidence?', options:[{id:'a',text:'The student wrote a long reflection.'},{id:'b',text:'Reflection has transferred across contexts and is connected to identity, purpose, long-term growth and independent action.'},{id:'c',text:'The teacher did not read it.'},{id:'d',text:'The student chose a difficult goal.'}], answer:'b', correctFeedback:'Correct. Transformational 4c describes learner ownership of growth connected to identity, purpose and long-term goals.', incorrectFeedback:'The defining evidence is independent, transferable reflection tied to purpose and growth, not length or difficulty.', contentTags:['4c','Transformational','Learner Ownership'] },
    ],
  },
  {
    id:'growth-d4-collaboration', number:5, title:'4d. Professional Collaboration & Collective Capacity',
    summary:'Move from logistical collaboration toward shared practice, team coherence, distributed expertise and sustained schoolwide improvement.',
    learn:[
      'The 4d continuum begins with limited or logistical collaboration that has little impact on teaching and learning. Building includes planning together and discussing student needs, but practice may remain inconsistently applied. Embedding makes collaboration purposeful and student-centred: shared practice improves outcomes and students experience more consistently high-quality learning.',
      'Extending includes leading collaborative practices and sharing expertise so teaching improves across teams and contexts. Transformational practice builds collective capacity and systems, creating coherent, sustained schoolwide impact. The continuum therefore asks us to judge collaboration by what changes for learners — not by how many meetings or shared documents a team has.',
    ],
    takeaways:['Collaboration should improve student experience and outcomes.', 'Embedding includes purposeful student-centred shared practice.', 'Extending includes sharing expertise and improving practice across teams.', 'Transformational collaboration builds coherent systems and collective capacity.'],
    questions:[
      { ...shared, id:'growth-d4-9', section:'growth-d4-collaboration', questionNumber:9, assessmentLevel:'Analysis', learningObjective:'Distinguish logistical from purposeful collaboration.', scenario:'A PLC meets weekly, shares deadlines and divides resources, but rarely looks at student learning or examines whether shared practice is improving outcomes.', question:'What is the strongest continuum-based reflection?', options:[{id:'a',text:'The PLC is Embedded because it meets every week.'},{id:'b',text:'The collaboration is organised but remains largely logistical; the next move is to centre shared evidence of student learning and the impact of practice.'},{id:'c',text:'The PLC should stop sharing resources.'},{id:'d',text:'Each teacher should work independently instead.'}], answer:'b', correctFeedback:'Correct. 4d becomes stronger when collaboration is student-centred and shared practice demonstrably improves learning.', incorrectFeedback:'Meeting frequency and resource sharing do not by themselves demonstrate collective impact. The continuum centres what changes for learners.', contentTags:['4d','Collaboration','Collective Capacity'] },
      { ...shared, id:'growth-d4-10', section:'growth-d4-collaboration', questionNumber:10, assessmentLevel:'Professional Judgement', learningObjective:'Recognise Extending collective capacity.', scenario:'A teacher develops an effective approach, shares it with colleagues, co-examines student evidence and helps the team adapt the practice across different classes.', question:'What makes this Extending-type evidence?', options:[{id:'a',text:'The teacher created the original idea.'},{id:'b',text:'Expertise is being shared and collaborative practice is improving learning across teams and contexts.'},{id:'c',text:'Every teacher copied the exact same lesson.'},{id:'d',text:'The teacher led the meeting.'}], answer:'b', correctFeedback:'Correct. Extending 4d includes leading collaborative practice, sharing expertise and improving teaching across contexts.', incorrectFeedback:'The important shift is collective improvement across contexts, not ownership of the original idea or identical implementation.', contentTags:['4d','Extending','Shared Expertise'] },
    ],
  },
  {
    id:'growth-d4-partnership', number:6, title:'4e. Communication & Community Partnership',
    summary:'Move from reactive one-way communication toward responsive, reciprocal partnerships that strengthen learning across settings.',
    learn:[
      'In 4e, Exploring communication is inconsistent, reactive and mostly one-way. Building establishes regular, clear and respectful communication structures. Embedding uses communication to build relationships and support learning; communication becomes two-way, stakeholders provide input and teachers respond to feedback.',
      'Extending strengthens partnerships across contexts: communication adapts to different audiences and needs, and collaboration with families or community partners supports learning beyond the classroom. Transformational practice is authentic and reciprocal, with families and community members co-contributing to learning, trust and shared responsibility. The key shift is from sending information toward partnership that influences learning.',
    ],
    takeaways:['Regular communication is a foundation, not the endpoint.', 'Embedding includes two-way communication that informs practice.', 'Extending adapts communication and strengthens learning across settings.', 'Transformational partnerships are reciprocal and co-contribute to learning.'],
    questions:[
      { ...shared, id:'growth-d4-11', section:'growth-d4-partnership', questionNumber:11, assessmentLevel:'Analysis', learningObjective:'Distinguish information sharing from partnership.', scenario:'Families receive polished weekly updates, but there is no meaningful way to ask questions, share context or influence support for learning.', question:'What is the strongest reflection?', options:[{id:'a',text:'Communication is Transformational because it is frequent.'},{id:'b',text:'Regular communication is established, but partnership remains limited because it is still largely one-way.'},{id:'c',text:'Families should make all instructional decisions.'},{id:'d',text:'Weekly communication should stop.'}], answer:'b', correctFeedback:'Correct. 4e deepens from regular information sharing toward two-way, responsive and reciprocal partnership.', incorrectFeedback:'Frequency and polish are useful, but the continuum asks whether communication builds relationships, incorporates stakeholder input and supports learning.', contentTags:['4e','Communication','Partnership'] },
      { ...shared, id:'growth-d4-12', section:'growth-d4-partnership', questionNumber:12, assessmentLevel:'Synthesis', learningObjective:'Identify a coherent Domain 4 next move.', scenario:'A teacher gives timely feedback and uses classroom evidence responsively. Student reflection is mostly prompted, PLC collaboration is logistical, and family communication is regular but largely one-way.', question:'Which next move is most coherent with Domain 4?', options:[{id:'a',text:'Add more individual feedback comments.'},{id:'b',text:'Build one connected improvement cycle in which learners use evidence to reflect and set a next step, colleagues examine the pattern together, and relevant stakeholder input informs the response.'},{id:'c',text:'Join more committees.'},{id:'d',text:'Collect more data before changing anything.'}], answer:'b', correctFeedback:'Correct. This builds from existing strengths while deepening learner ownership, evidence-informed collaboration and partnership — central developmental moves in Domain 4.', incorrectFeedback:'The strongest next move connects existing evidence and feedback strengths to the weaker areas of learner reflection, collaboration and partnership.', contentTags:['Domain 4','Synthesis','Next Move'] },
    ],
  },
];

export const growthDomain3Questions: AiQuestion[] = growthDomain3Sections.flatMap((section) => section.questions);
export const growthDomain4Questions: AiQuestion[] = growthDomain4Sections.flatMap((section) => section.questions);
