import type { AiQuestion, AiSection } from '@/lib/ai-course';

export const TEACHER_GROWTH_DOMAIN_COURSE_VERSION = 'SY2026-27';

const shared = {
  courseVersion: TEACHER_GROWTH_DOMAIN_COURSE_VERSION,
  contentOwner: 'Learning & Teaching',
  reviewStatus: 'draft_for_learning_and_teaching_review',
} as const;

export const growthDomain1Sections: AiSection[] = [
  {
    id: 'growth-d1-continuum',
    number: 1,
    title: 'Read the Continuum Through Student Experience',
    summary: 'Use the continuum as a developmental lens for what students are doing, thinking and experiencing — not as a label for a teacher.',
    learn: [
      'The AISG Teacher Growth Continuum describes growth from Exploring through Building, Embedding, Extending and Transformational. Growth is not presented as a simple linear march. As practice deepens, it becomes more intentional, responsive and impactful, with increasing student ownership and transfer. In Domains 1–3, the strongest evidence sits in student experience: what students say, do, produce, choose and increasingly manage for themselves.',
      'For Domain 1, the useful question is not “Which box am I in?” but “What is the learner evidence telling me about the design?” A teacher may be embedding one practice while still building another. The continuum helps identify a realistic next move: greater clarity, stronger access, deeper thinking, more responsive assessment, or more learner independence — depending on the evidence in front of you.',
    ],
    takeaways: [
      'Use the continuum as a developmental lens, not a fixed label.',
      'Look first for evidence in student experience and outcomes.',
      'Different strands of practice can develop at different rates.',
      'The next move should respond to evidence rather than chase a level name.',
    ],
    questions: [
      {
        ...shared,
        id: 'growth-d1-1', section: 'growth-d1-continuum', questionNumber: 1, assessmentLevel: 'Foundation',
        learningObjective: 'Recognise the student-centred purpose of the continuum.',
        scenario: 'A teacher wants to use Domain 1 for reflection after a learning engagement.',
        question: 'Which starting question is most consistent with the framework?',
        options: [
          { id: 'a', text: 'Which level can I claim based on the activity I planned?' },
          { id: 'b', text: 'What were students actually doing, thinking and experiencing as a result of the design?' },
          { id: 'c', text: 'How many strategies from the framework did I include?' },
          { id: 'd', text: 'Did the lesson look similar to another teacher’s lesson?' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Domains 1–3 are grounded primarily in observable student experience and outcomes, so reflection begins with evidence of learning rather than a checklist of teacher actions.',
        incorrectFeedback: 'The continuum is designed to connect instructional decisions to student experience. Start with what students were actually doing, thinking and experiencing.',
        contentTags: ['Teacher Growth Continuum', 'Student-Centred Evidence', 'Reflection'],
      },
      {
        ...shared,
        id: 'growth-d1-2', section: 'growth-d1-continuum', questionNumber: 2, assessmentLevel: 'Application',
        learningObjective: 'Use the continuum to identify a realistic next move.',
        scenario: 'Students can explain the learning goal and success criteria, but still rely on the teacher to decide how to use those criteria during learning.',
        question: 'What is the strongest reflection?',
        options: [
          { id: 'a', text: 'The practice is complete because students can repeat the goal.' },
          { id: 'b', text: 'The next move is to create conditions for students to monitor progress and make more independent learning decisions using the criteria.' },
          { id: 'c', text: 'Remove the success criteria so students become independent.' },
          { id: 'd', text: 'Add more teacher explanation at the start of every task.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The continuum deepens from clarity toward student monitoring, transfer and independent use of goals and criteria.',
        incorrectFeedback: 'The evidence already shows emerging clarity. The next developmental move is greater student ownership and use of the criteria, not simply more teacher explanation.',
        contentTags: ['Growth', 'Next Move', 'Student Ownership'],
      },
    ],
  },
  {
    id: 'growth-d1-purpose',
    number: 2,
    title: '1a. Learning Purpose & Outcomes',
    summary: 'Move from activity completion toward learning purpose, visible success and increasing student ownership of goals.',
    learn: [
      'At the Exploring end of 1a, intentions are often framed around activities and students focus on what to do rather than what they are learning. Building practice makes learning goals clearer and introduces success criteria. Embedding means goals and criteria are meaningful and aligned, expectations are modelled, understanding is checked, and students can explain what success looks like and monitor progress.',
      'Extending and Transformational practice shift more of the work to learners. Students independently apply and transfer goals across learning engagements, use goals to guide decisions, and eventually set, revise and adapt goals in authentic contexts. This does not mean the teacher disappears. The design increasingly enables students to understand purpose and exercise informed ownership.',
    ],
    takeaways: [
      'Learning goals should clarify purpose rather than simply name an activity.',
      'Success criteria help students understand and monitor quality.',
      'Embedding is visible when students can explain success and use criteria during learning.',
      'Extending and Transformational practice increase independent transfer and goal ownership.',
    ],
    questions: [
      {
        ...shared,
        id: 'growth-d1-3', section: 'growth-d1-purpose', questionNumber: 3, assessmentLevel: 'Application',
        learningObjective: 'Distinguish activity-focused intentions from learning-focused outcomes.',
        scenario: 'The posted intention says, “Complete a three-slide presentation about ecosystems.” Students immediately ask how many pictures they need.',
        question: 'Which redesign most strongly moves toward the continuum’s description of purposeful learning?',
        options: [
          { id: 'a', text: 'Add a fourth slide so students have more to do.' },
          { id: 'b', text: 'Clarify the learning, such as explaining relationships within an ecosystem, and make the evidence of success visible.' },
          { id: 'c', text: 'Provide a stricter template.' },
          { id: 'd', text: 'Remove all guidance and let students choose any topic.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. 1a develops from activity completion toward clear learning purpose, aligned success criteria and student monitoring.',
        incorrectFeedback: 'The issue is not the number of slides or amount of freedom. The design needs to make the intended learning and success clearer.',
        contentTags: ['1a', 'Learning Purpose', 'Success Criteria'],
      },
      {
        ...shared,
        id: 'growth-d1-4', section: 'growth-d1-purpose', questionNumber: 4, assessmentLevel: 'Analysis',
        learningObjective: 'Recognise evidence of Extending practice in learning purpose.',
        scenario: 'Students use shared criteria independently to check progress in a new task and adjust their approach without waiting for teacher prompts.',
        question: 'Why is this evidence significant in the continuum?',
        options: [
          { id: 'a', text: 'It shows students can complete a routine faster.' },
          { id: 'b', text: 'It shows transfer and independent use of goals or criteria across learning engagements.' },
          { id: 'c', text: 'It proves every student should now set completely different goals.' },
          { id: 'd', text: 'It removes the need for teacher observation and feedback.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Extending is characterised by students independently applying, adapting and transferring learning across contexts.',
        incorrectFeedback: 'The important shift is not speed or teacher absence. It is students independently transferring and using the learning framework to guide decisions.',
        contentTags: ['1a', 'Extending', 'Transfer'],
      },
    ],
  },
  {
    id: 'growth-d1-learners',
    number: 3,
    title: '1b. Understanding Learners & Identity',
    summary: 'Design with identities, strengths and needs in mind so access becomes more responsive, inclusive and learner-owned.',
    learn: [
      'In 1b, Exploring practice recognises learner differences but integrates them inconsistently into planning. Students may experience the same learning regardless of need, limited representation, or exclusion. Building practice begins to use learner data and identity to inform planning, with scaffolds and supports that improve access. Embedding anticipates barriers and designs learning that reflects identities, strengths and needs so students experience equitable access and multiple pathways.',
      'As practice extends, learners increasingly choose and adapt strategies that support their own strengths and needs across learning situations. At the Transformational end, learner identity becomes an asset: students contribute perspectives, shape pathways, suggest adaptations and advocate for inclusion. The continuum therefore moves beyond teachers knowing learners toward learners increasingly knowing and advocating for themselves.',
    ],
    takeaways: [
      'Knowing learners should shape planning, not remain background information.',
      'Embedding includes anticipating barriers and monitoring access for all learners.',
      'Multiple pathways can strengthen equitable access without lowering the learning goal.',
      'Deeper practice includes learners selecting strategies and advocating for inclusion.',
    ],
    questions: [
      {
        ...shared,
        id: 'growth-d1-5', section: 'growth-d1-learners', questionNumber: 5, assessmentLevel: 'Application',
        learningObjective: 'Recognise planning that uses learner identity and needs meaningfully.',
        scenario: 'A teacher knows several students are multilingual and that the class includes varied cultural perspectives, but every task uses the same text, response mode and examples.',
        question: 'Which next move best aligns with 1b?',
        options: [
          { id: 'a', text: 'Keep the design identical because fairness requires everyone to access learning in the same way.' },
          { id: 'b', text: 'Use learner information to anticipate barriers, strengthen representation and create valid pathways into the same worthwhile learning.' },
          { id: 'c', text: 'Lower the learning expectations for students who need support.' },
          { id: 'd', text: 'Wait until a student fails before changing the design.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Embedding practice reflects identities, strengths and needs, anticipates barriers and supports equitable access.',
        incorrectFeedback: 'The continuum moves toward proactive, responsive design. Access can vary while the intended learning remains worthwhile and coherent.',
        contentTags: ['1b', 'Learner Identity', 'Access'],
      },
      {
        ...shared,
        id: 'growth-d1-6', section: 'growth-d1-learners', questionNumber: 6, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Identify evidence of learner ownership within responsive design.',
        scenario: 'Students can explain which strategies help them learn, independently choose among appropriate supports, and suggest adaptations when a new task creates a barrier.',
        question: 'What does this most strongly indicate?',
        options: [
          { id: 'a', text: 'Students are avoiding common expectations.' },
          { id: 'b', text: 'Practice is moving toward Extending or Transformational because learners are applying strategies and influencing access.' },
          { id: 'c', text: 'The teacher should remove all shared structures.' },
          { id: 'd', text: 'The class no longer needs to consider identity or inclusion.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The later continuum descriptors emphasise learners independently selecting strategies, shaping pathways and advocating for inclusion.',
        incorrectFeedback: 'The evidence is about growing learner ownership of access and strategy use, not the removal of shared expectations.',
        contentTags: ['1b', 'Learner Ownership', 'Advocacy'],
      },
    ],
  },
  {
    id: 'growth-d1-engagements',
    number: 4,
    title: '1c. Inclusive Learning Engagements & Materials Design',
    summary: 'Move beyond completion and recall toward accessible, cognitively engaging learning with multiple entry points and authentic learner ownership.',
    learn: [
      'At the Exploring end of 1c, learning engagements may focus on completion, recall or repetition, with limited accessibility, representation or deeper thinking. Building introduces some engagement and access supports. Embedding combines inclusion with cognitive demand: multiple entry points, modelling and questioning support students to analyse, create, problem-solve and engage with diverse perspectives.',
      'Extending asks whether students can independently transfer thinking and strategies to new situations and adapt when learning changes. Transformational design goes further: learning is culturally sustaining and increasingly co-designed, with students driving inquiry, creativity and authentic problem-solving. The continuum is therefore not a move from “easy” to “hard”; it is a move toward access, depth, transfer and ownership working together.',
    ],
    takeaways: [
      'Completion and recall alone do not demonstrate deep learning engagement.',
      'Embedding combines accessibility with cognitive engagement and multiple entry points.',
      'Extending is visible through independent transfer and adaptation of thinking.',
      'Transformational learning includes student-driven inquiry, creativity and authentic problems.',
    ],
    questions: [
      {
        ...shared,
        id: 'growth-d1-7', section: 'growth-d1-engagements', questionNumber: 7, assessmentLevel: 'Analysis',
        learningObjective: 'Recognise the combination of inclusion and cognitive demand in Embedding practice.',
        scenario: 'A lesson includes several access supports, but every learner completes the same low-level recall worksheet and there is little evidence of analysis, creation or problem-solving.',
        question: 'Which reflection is strongest?',
        options: [
          { id: 'a', text: 'The learning is fully embedded because supports are visible.' },
          { id: 'b', text: 'Access has improved, but the design still needs stronger cognitive engagement and opportunities for deeper thinking.' },
          { id: 'c', text: 'Remove the supports to make the task more rigorous.' },
          { id: 'd', text: 'Add more recall questions to increase challenge.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. In 1c, Embedding joins inclusion and access with cognitively engaging learning, questioning, problem-solving and diverse perspectives.',
        incorrectFeedback: 'Access and cognitive demand are not opposites. The continuum expects both to strengthen together.',
        contentTags: ['1c', 'Cognitive Engagement', 'Accessibility'],
      },
      {
        ...shared,
        id: 'growth-d1-8', section: 'growth-d1-engagements', questionNumber: 8, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Distinguish authentic learner ownership from superficial choice.',
        scenario: 'Students choose the colour of a template and one of three teacher-selected examples, but the inquiry question, pathway and final product remain fully prescribed.',
        question: 'What is the strongest continuum-based interpretation?',
        options: [
          { id: 'a', text: 'This is Transformational because students made choices.' },
          { id: 'b', text: 'The choices may support engagement, but they do not yet show students driving inquiry, creativity or authentic problem-solving.' },
          { id: 'c', text: 'Any teacher structure prevents higher-level practice.' },
          { id: 'd', text: 'The task should become completely unstructured.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Transformational 1c describes students helping design learning engagements, pursuing self-directed pathways and engaging with authentic problems.',
        incorrectFeedback: 'Choice alone is not the endpoint. The later descriptors emphasise meaningful ownership of inquiry, pathways, creativity and authentic problem-solving.',
        contentTags: ['1c', 'Transformational', 'Inquiry'],
      },
    ],
  },
  {
    id: 'growth-d1-assessment',
    number: 5,
    title: '1d. Assessment Planning for Equity & Growth',
    summary: 'Use assessment as a continuous learning process that moves from teacher-provided feedback toward student monitoring, goal-setting and adaptation.',
    learn: [
      'The 1d continuum begins with assessment used mainly for summative purposes, limited feedback, grade focus and little evidence of revision. Building introduces formative checks and feedback, with students improving when prompted. Embedding makes formative assessment varied and timely: teachers adjust instruction from evidence, and students use feedback during learning to improve outcomes.',
      'Extending shifts toward students independently tracking progress with shared criteria, adjusting strategies and explaining improvement over time. Transformational practice treats assessment as a continuous process in which students self-assess, set goals from evidence and adapt learning in real time. A useful reflection is therefore: Who is using the evidence, and what changes because of it?',
    ],
    takeaways: [
      'Assessment should create opportunities for improvement while learning is still happening.',
      'Embedding is visible when evidence changes teaching and students use feedback during learning.',
      'Extending includes independent progress monitoring and strategy adjustment.',
      'Transformational assessment is increasingly continuous and learner-owned.',
    ],
    questions: [
      {
        ...shared,
        id: 'growth-d1-9', section: 'growth-d1-assessment', questionNumber: 9, assessmentLevel: 'Application',
        learningObjective: 'Recognise evidence of Building assessment practice.',
        scenario: 'A teacher now uses checks for understanding and gives feedback. Students revise when the teacher tells them exactly what to change.',
        question: 'What is the strongest interpretation?',
        options: [
          { id: 'a', text: 'This reflects Building practice because formative checks and guided improvement are becoming visible.' },
          { id: 'b', text: 'This is automatically Transformational because feedback is present.' },
          { id: 'c', text: 'This remains Exploring because all feedback is teacher-generated.' },
          { id: 'd', text: 'Assessment levels cannot be reflected on through student evidence.' },
        ],
        answer: 'a',
        correctFeedback: 'Correct. Building includes formative checks, feedback and student improvement with guidance.',
        incorrectFeedback: 'The evidence shows a meaningful move beyond summative-only assessment, while learner independence is still developing.',
        contentTags: ['1d', 'Building', 'Formative Assessment'],
      },
      {
        ...shared,
        id: 'growth-d1-10', section: 'growth-d1-assessment', questionNumber: 10, assessmentLevel: 'Analysis',
        learningObjective: 'Recognise Embedding assessment practice.',
        scenario: 'During a unit, the teacher uses several sources of evidence to change instruction. Students receive specific feedback, revise during learning and can explain how the feedback improved their work.',
        question: 'Which continuum description is most closely represented?',
        options: [
          { id: 'a', text: 'Exploring' },
          { id: 'b', text: 'Building' },
          { id: 'c', text: 'Embedding' },
          { id: 'd', text: 'Transformational only' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. Embedding 1d includes varied formative assessment, timely feedback, teacher adjustment and students using feedback during learning.',
        incorrectFeedback: 'The combination of teacher responsiveness and student use of feedback during learning closely matches the Embedding descriptor.',
        contentTags: ['1d', 'Embedding', 'Feedback'],
      },
      {
        ...shared,
        id: 'growth-d1-11', section: 'growth-d1-assessment', questionNumber: 11, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Identify a next move from Embedding toward Extending.',
        scenario: 'Students regularly use feedback to revise, but they still wait for the teacher to tell them when they are ready to move on or which strategy to try next.',
        question: 'Which next move best reflects Extending?',
        options: [
          { id: 'a', text: 'Add more summative grades so progress is clearer.' },
          { id: 'b', text: 'Strengthen shared criteria and routines that help students independently monitor progress and adjust strategies.' },
          { id: 'c', text: 'Stop giving feedback completely.' },
          { id: 'd', text: 'Let students choose whether they want to learn the intended outcomes.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Extending describes students independently tracking progress and adjusting strategies using shared criteria.',
        incorrectFeedback: 'The next developmental move is greater learner independence with evidence and criteria, not more grading or less clarity.',
        contentTags: ['1d', 'Extending', 'Self-Monitoring'],
      },
      {
        ...shared,
        id: 'growth-d1-12', section: 'growth-d1-assessment', questionNumber: 12, assessmentLevel: 'Synthesis',
        learningObjective: 'Synthesize Domain 1 through student-centred evidence and a focused next move.',
        scenario: 'Students understand the learning purpose, access tasks through several valid pathways and engage in meaningful problem-solving. They use teacher feedback to revise, but few independently monitor progress or adapt strategies across new learning situations.',
        question: 'Which Domain 1 next move is most strongly supported by the evidence?',
        options: [
          { id: 'a', text: 'Replace the learning design because no strand is working.' },
          { id: 'b', text: 'Focus on structures that help students transfer goals, criteria and learning strategies more independently across contexts.' },
          { id: 'c', text: 'Reduce choice and access so the teacher can control progress more closely.' },
          { id: 'd', text: 'Add more content coverage before considering learner ownership.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The evidence suggests several Domain 1 practices are already strong. The clearest next move is increasing independent monitoring, strategy use and transfer.',
        incorrectFeedback: 'A continuum-based reflection builds from strengths and identifies the next developmental gap visible in student experience. Here, learner transfer and independence are the clearest opportunity.',
        contentTags: ['Domain 1', 'Synthesis', 'Next Move'],
      },
    ],
  },
];

export const growthDomain2Sections: AiSection[] = [
  {
    id: 'growth-d2-continuum',
    number: 1,
    title: 'Read Culture Through Learner Experience',
    summary: 'Notice how belonging, voice, routines and environments shift from teacher-managed conditions toward student ownership and collective responsibility.',
    learn: [
      'Domain 2 focuses on the learning culture and environment students experience. Across the continuum, the pattern is developmental: teacher-established structures become more inclusive and consistent, then students increasingly sustain, adapt and influence those conditions for themselves and others. Evidence is visible in participation, relationships, voice, routines, use of time and tools, and the degree of learner independence.',
      'The continuum is not asking for constant student control of everything. It asks whether the environment increasingly enables learners to participate safely, contribute meaningfully, manage routines, advocate for needs and use resources strategically. Reflection should therefore distinguish between a classroom that is orderly because the teacher manages every move and one where students increasingly understand, sustain and improve the conditions for learning.',
    ],
    takeaways: [
      'Domain 2 is visible in belonging, participation, voice, routines and learner independence.',
      'Order and compliance are not the same as an inclusive learning culture.',
      'Later continuum levels show students sustaining and adapting conditions for learning.',
      'Look for who is carrying responsibility for the learning environment.',
    ],
    questions: [
      {
        ...shared,
        id: 'growth-d2-1', section: 'growth-d2-continuum', questionNumber: 1, assessmentLevel: 'Foundation',
        learningObjective: 'Recognise the developmental pattern in Domain 2.',
        scenario: 'A classroom runs smoothly, but students wait for the teacher to manage transitions, decide who speaks, distribute every resource and solve minor participation issues.',
        question: 'Which reflection best fits the Domain 2 continuum?',
        options: [
          { id: 'a', text: 'Smooth routines prove learner autonomy is already strong.' },
          { id: 'b', text: 'The environment may be organised, but student independence and shared responsibility are still developing.' },
          { id: 'c', text: 'The teacher should stop managing the class immediately.' },
          { id: 'd', text: 'Domain 2 only concerns behaviour expectations.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The later Domain 2 descriptors are increasingly visible through students independently sustaining, adapting and improving the conditions for learning.',
        incorrectFeedback: 'Organisation matters, but the continuum also asks whether learners increasingly participate, self-manage and share responsibility for the environment.',
        contentTags: ['Domain 2', 'Learner Independence', 'Culture'],
      },
      {
        ...shared,
        id: 'growth-d2-2', section: 'growth-d2-continuum', questionNumber: 2, assessmentLevel: 'Application',
        learningObjective: 'Use student evidence to identify a Domain 2 next move.',
        scenario: 'Most students participate respectfully when prompted, but a small group still rarely contributes and students do not yet notice or respond to participation imbalance themselves.',
        question: 'What is the strongest next move?',
        options: [
          { id: 'a', text: 'Assume respectful behaviour is enough and keep the same structures.' },
          { id: 'b', text: 'Strengthen structures that broaden participation and help students increasingly notice, include and support one another.' },
          { id: 'c', text: 'Only call on the quietest students without changing the environment.' },
          { id: 'd', text: 'Grade participation more heavily.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The continuum deepens from prompted participation toward broadly distributed contribution and students sustaining inclusive behaviours themselves.',
        incorrectFeedback: 'The next move should improve the learning culture and distribution of participation, not simply increase pressure on individual students.',
        contentTags: ['Domain 2', 'Participation', 'Next Move'],
      },
    ],
  },
  {
    id: 'growth-d2-belonging',
    number: 2,
    title: '2a. Belonging, Respect & Psychological Safety',
    summary: 'Move from basic expectations toward a culture where students take risks, support one another and actively sustain inclusion.',
    learn: [
      'In 2a, Exploring practice establishes basic expectations but belonging and participation are inconsistent. Building creates a more respectful environment where most students participate with guidance. Embedding is visible when students feel safe to take risks, contribute without prompting, participate broadly and support one another respectfully.',
      'Extending and Transformational practice shift responsibility further. Students include and support peers without prompting, adapt to maintain belonging across situations, address minor exclusion or imbalance, and eventually take responsibility for promoting inclusive community practices and responding to exclusion or bias. Psychological safety becomes something the group helps sustain, not only something the teacher provides.',
    ],
    takeaways: [
      'Belonging is reflected in who participates, takes risks and feels included.',
      'Embedding includes broadly distributed participation and respectful peer support.',
      'Extending includes students maintaining inclusion across changing situations.',
      'Transformational practice includes collective responsibility for inclusive community culture.',
    ],
    questions: [
      {
        ...shared,
        id: 'growth-d2-3', section: 'growth-d2-belonging', questionNumber: 3, assessmentLevel: 'Application',
        learningObjective: 'Recognise evidence of Embedding belonging and psychological safety.',
        scenario: 'During discussion, students contribute without being individually called on, participation is broadly distributed and students respond respectfully to one another’s ideas.',
        question: 'Which descriptor is most closely represented?',
        options: [
          { id: 'a', text: 'Exploring' },
          { id: 'b', text: 'Building' },
          { id: 'c', text: 'Embedding' },
          { id: 'd', text: 'Only Transformational' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. These are explicit indicators within the Embedding description for 2a.',
        incorrectFeedback: 'Broad participation, unprompted contribution and respectful peer support closely match the Embedding evidence in 2a.',
        contentTags: ['2a', 'Embedding', 'Psychological Safety'],
      },
      {
        ...shared,
        id: 'growth-d2-4', section: 'growth-d2-belonging', questionNumber: 4, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Recognise movement from teacher-created safety toward collective responsibility.',
        scenario: 'In group work, students notice that one voice is being excluded, pause the process, invite that perspective and adjust how the group works without teacher prompting.',
        question: 'Why is this significant in the continuum?',
        options: [
          { id: 'a', text: 'It shows students are replacing the teacher.' },
          { id: 'b', text: 'It shows students independently sustaining inclusion and addressing imbalance, which reflects later continuum practice.' },
          { id: 'c', text: 'It proves conflict should never require adult support.' },
          { id: 'd', text: 'It is only evidence of task completion.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Extending and Transformational descriptors include students supporting peers, addressing exclusion or imbalance and taking responsibility for inclusive culture.',
        incorrectFeedback: 'The important evidence is the learner-owned maintenance of inclusion, not the absence of a teacher role.',
        contentTags: ['2a', 'Extending', 'Inclusion'],
      },
    ],
  },
  {
    id: 'growth-d2-voice',
    number: 3,
    title: '2b. Student Voice, Representation & Advocacy',
    summary: 'Move from invited participation toward student voice that influences learning, supports advocacy and shapes wider experiences.',
    learn: [
      'At the Exploring end of 2b, student voice is limited and participation is passive. Building introduces planned structures where students contribute with prompts. Embedding goes further: student perspectives are actively drawn out, shared independently and used to influence learning engagements.',
      'Extending is visible when students independently use voice to adapt and improve learning, explain how their input shaped learning and advocate for their needs. Transformational practice includes student-led advocacy, students advocating for others, and student voice shaping broader learning experiences. Voice therefore becomes more than being heard; it increasingly has influence and consequence.',
    ],
    takeaways: [
      'Having opportunities to speak is not the same as having meaningful influence.',
      'Embedding includes student input genuinely shaping learning.',
      'Extending includes independent advocacy and visible response to student input.',
      'Transformational voice can shape broader learning environments and systems.',
    ],
    questions: [
      {
        ...shared,
        id: 'growth-d2-5', section: 'growth-d2-voice', questionNumber: 5, assessmentLevel: 'Analysis',
        learningObjective: 'Distinguish tokenistic voice from voice that influences learning.',
        scenario: 'Students complete a weekly “voice” survey, but the teacher never refers to the responses and the learning design does not change.',
        question: 'What is the strongest reflection?',
        options: [
          { id: 'a', text: 'The survey proves student voice is embedded.' },
          { id: 'b', text: 'A structure for voice exists, but influence is limited because student input is not yet shaping learning.' },
          { id: 'c', text: 'Student voice should only be collected at the end of the year.' },
          { id: 'd', text: 'Students should make every instructional decision instead.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. In the continuum, stronger student voice increasingly influences, adapts and improves learning experiences.',
        incorrectFeedback: 'The presence of a survey is only a structure. The later descriptors depend on student input having meaningful influence.',
        contentTags: ['2b', 'Student Voice', 'Influence'],
      },
      {
        ...shared,
        id: 'growth-d2-6', section: 'growth-d2-voice', questionNumber: 6, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Recognise evidence of Extending student voice.',
        scenario: 'Students identify that one discussion format limits contribution, propose a different structure, explain why it would improve access, and the class adopts the change.',
        question: 'Which continuum feature is most visible?',
        options: [
          { id: 'a', text: 'Students are responding when called on.' },
          { id: 'b', text: 'Students are independently using voice to influence and improve the learning experience.' },
          { id: 'c', text: 'The teacher has stopped planning.' },
          { id: 'd', text: 'Students are only advocating for easier work.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Extending 2b includes students suggesting changes that are acted upon and advocating for needs independently.',
        incorrectFeedback: 'The key evidence is meaningful student influence on the learning environment, not teacher withdrawal.',
        contentTags: ['2b', 'Extending', 'Advocacy'],
      },
    ],
  },
  {
    id: 'growth-d2-routines',
    number: 4,
    title: '2c. Routines that Support Equity & Autonomy',
    summary: 'Design routines that move from teacher dependence toward learner independence, adaptation and shared improvement.',
    learn: [
      'In 2c, Exploring practice is inconsistent or teacher-directed: students wait for instructions, transitions are inefficient and the teacher manages most routines. Building introduces clearer structures and developing independence. Embedding means inclusive routines promote autonomy, transitions are smooth and students manage time, materials and expected processes consistently.',
      'Extending asks whether students can adapt routines in new or changing situations and suggest improvements without prompting. Transformational practice is increasingly co-created: students sustain and refine equitable routines independently and adapt systems to support others. The goal is not routine for routine’s sake; it is a learning environment in which students can use structures to participate, self-manage and support equitable access.',
    ],
    takeaways: [
      'Effective routines should reduce unnecessary dependence on the teacher.',
      'Embedding is visible when students initiate and manage routines consistently.',
      'Extending includes adapting routines across changing situations.',
      'Transformational routines are increasingly co-created, sustained and refined by learners.',
    ],
    questions: [
      {
        ...shared,
        id: 'growth-d2-7', section: 'growth-d2-routines', questionNumber: 7, assessmentLevel: 'Application',
        learningObjective: 'Recognise Embedding routines that support autonomy.',
        scenario: 'Students enter, access materials, transition into learning and manage time without repeated reminders. The teacher monitors but does not direct every step.',
        question: 'Which interpretation is strongest?',
        options: [
          { id: 'a', text: 'This is evidence of Embedding because routines support consistent learner autonomy.' },
          { id: 'b', text: 'This remains Exploring because the teacher is still present.' },
          { id: 'c', text: 'This is Transformational because routines are efficient.' },
          { id: 'd', text: 'Routines are unrelated to learning culture.' },
        ],
        answer: 'a',
        correctFeedback: 'Correct. Embedding 2c describes students initiating routines independently, managing time and materials, and moving through smooth transitions.',
        incorrectFeedback: 'The continuum does not require teacher absence. It looks for increasing learner independence within effective, inclusive structures.',
        contentTags: ['2c', 'Embedding', 'Autonomy'],
      },
      {
        ...shared,
        id: 'growth-d2-8', section: 'growth-d2-routines', questionNumber: 8, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Identify a next move from Embedding toward Extending.',
        scenario: 'Class routines work well in the normal room, but when the class moves to a different space students wait for the teacher to recreate every process.',
        question: 'Which next move best reflects Extending?',
        options: [
          { id: 'a', text: 'Give more detailed instructions every time the context changes.' },
          { id: 'b', text: 'Help students identify the purpose behind the routines so they can adapt and apply them in new situations.' },
          { id: 'c', text: 'Keep all learning in the same room.' },
          { id: 'd', text: 'Remove routines completely.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Extending includes students independently adapting and applying systems across different learning situations.',
        incorrectFeedback: 'The developmental move is transfer: students should increasingly understand and adapt the routine rather than wait for a context-specific script.',
        contentTags: ['2c', 'Extending', 'Transfer'],
      },
    ],
  },
  {
    id: 'growth-d2-environment',
    number: 5,
    title: '2d. Purposeful Use of Space, Time & Tools',
    summary: 'Design environments that support access and participation, then help learners choose and use space, time and tools strategically.',
    learn: [
      'The 2d continuum begins with inconsistent use of space, time or tools and heavy teacher direction. Building organises the environment so students can access resources and tools with guidance. Embedding goes further: the environment enhances access and participation, space supports collaboration, and students select tools to support thinking and creation.',
      'Extending is visible when students independently choose and use space, time and tools appropriately across learning situations. Transformational practice optimises environments, including digital tools, so learners strategically deepen thinking, creation, innovation and problem-solving. The important question is not whether a classroom has more tools, but whether students can use the environment purposefully and increasingly independently.',
    ],
    takeaways: [
      'Space, time and tools should support access, participation and thinking.',
      'Embedding includes students selecting tools to think, create and collaborate.',
      'Extending is visible through independent and appropriate choices across contexts.',
      'Transformational practice uses tools strategically to deepen thinking and creation.',
    ],
    questions: [
      {
        ...shared,
        id: 'growth-d2-9', section: 'growth-d2-environment', questionNumber: 9, assessmentLevel: 'Application',
        learningObjective: 'Recognise purposeful use of tools within Embedding practice.',
        scenario: 'Students have access to several digital and non-digital tools. The teacher always tells every student exactly which tool to use, even when several would support the learning equally well.',
        question: 'Which next move best aligns with 2d?',
        options: [
          { id: 'a', text: 'Add more tools to the room.' },
          { id: 'b', text: 'Where appropriate, help students select tools based on what will best support their thinking, creation or collaboration.' },
          { id: 'c', text: 'Require digital tools for every task.' },
          { id: 'd', text: 'Remove teacher modelling of tools completely.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Embedding 2d includes students selecting tools to support learning, while the teacher models and monitors effective use.',
        incorrectFeedback: 'The continuum values purposeful and increasingly independent selection, not simply more tools or less teacher support.',
        contentTags: ['2d', 'Tools', 'Purposeful Choice'],
      },
      {
        ...shared,
        id: 'growth-d2-10', section: 'growth-d2-environment', questionNumber: 10, assessmentLevel: 'Analysis',
        learningObjective: 'Distinguish access from strategic independence in the learning environment.',
        scenario: 'Students can access resources when prompted and use tools successfully with guidance, but they rarely decide independently how to use time, space or tools.',
        question: 'Which continuum interpretation is strongest?',
        options: [
          { id: 'a', text: 'This most closely reflects Building because access is improving but strategic independence is still developing.' },
          { id: 'b', text: 'This is Transformational because resources are available.' },
          { id: 'c', text: 'This is Exploring because students can use tools with guidance.' },
          { id: 'd', text: 'The continuum does not consider student independence.' },
        ],
        answer: 'a',
        correctFeedback: 'Correct. Building describes organised environments and guided use; later levels show increasingly independent and strategic use across contexts.',
        incorrectFeedback: 'The evidence shows useful structure and guided access, while independent selection and adaptation are not yet consistent.',
        contentTags: ['2d', 'Building', 'Independence'],
      },
      {
        ...shared,
        id: 'growth-d2-11', section: 'growth-d2-environment', questionNumber: 11, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Identify a Domain 2 next move grounded in student evidence.',
        scenario: 'Students collaborate respectfully and routines are smooth, but discussion participation remains uneven and quieter students say the room setup makes it difficult to enter conversations.',
        question: 'Which next move is best supported?',
        options: [
          { id: 'a', text: 'Keep the environment unchanged because behaviour is respectful.' },
          { id: 'b', text: 'Use the participation evidence to redesign space or discussion structures, then notice whether access and voice become more broadly distributed.' },
          { id: 'c', text: 'Tell quieter students to speak more often.' },
          { id: 'd', text: 'Replace collaborative learning with individual work.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Domain 2 asks educators to use the environment and structures to strengthen access, participation and student voice.',
        incorrectFeedback: 'The evidence points to an environmental participation barrier. A strong next move changes the conditions and then looks for a change in learner experience.',
        contentTags: ['Domain 2', 'Participation', 'Environment'],
      },
      {
        ...shared,
        id: 'growth-d2-12', section: 'growth-d2-environment', questionNumber: 12, assessmentLevel: 'Synthesis',
        learningObjective: 'Synthesize Domain 2 evidence across belonging, voice, routines and environment.',
        scenario: 'Students feel safe and participate respectfully. Routines are largely independent and students choose tools appropriately. However, student input rarely changes learning, and learners do not yet advocate for changes or inclusion without teacher prompts.',
        question: 'Which Domain 2 focus would most logically deepen the learner experience next?',
        options: [
          { id: 'a', text: 'Increase teacher control of routines.' },
          { id: 'b', text: 'Create more meaningful opportunities for student voice to influence learning and for learners to advocate for needs and inclusion.' },
          { id: 'c', text: 'Add more digital tools regardless of purpose.' },
          { id: 'd', text: 'Reduce discussion because participation is already respectful.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The evidence suggests belonging, routines and tool use are relatively strong, while meaningful student influence and advocacy are the clearest next developmental opportunity.',
        incorrectFeedback: 'A continuum-based reflection builds on existing strengths and targets the most visible next gap. Here, student voice and advocacy are the clearest opportunity.',
        contentTags: ['Domain 2', 'Synthesis', 'Student Voice'],
      },
    ],
  },
];

export const growthDomain1Questions: AiQuestion[] = growthDomain1Sections.flatMap((section) => section.questions);
export const growthDomain2Questions: AiQuestion[] = growthDomain2Sections.flatMap((section) => section.questions);
