import type { AiQuestion, AiSection } from '@/lib/ai-course';

// v2 expands the former Teams-only course into the required Employee Communication Guidelines course.
export const TEAMS_COURSE_VERSION = 'SY2026-27-communication-v2';

const q = (id: string, section: string, scenario: string, question: string, options: { id: string; text: string }[], answer: string, correctFeedback: string, incorrectFeedback: string): AiQuestion => ({ id, section, scenario, question, options, answer, correctFeedback, incorrectFeedback });

export const teamsSections: AiSection[] = [
  {
    id: 'communication-purpose', number: 1, title: 'Purpose, Audience and Professionalism',
    summary: 'Start with the reason for communicating, the people who need to act, and the information they need.',
    learn: ['Good communication begins before you open a channel or write a message. Ask: Why am I sharing this? Who needs this information? What do they need in order to act, support, understand or decide? Employment at AISG does not automatically create a need to know about every student or situation.', 'For student-related communication, the audience should have a legitimate role in understanding or supporting the situation. Use the simple check: right purpose + right people + right information. A convenient audience is not necessarily an appropriate audience, and a factually accurate message can still be too widely shared.'],
    takeaways: ['Name the educational purpose before communicating.', 'Include colleagues with a legitimate role.', 'Accuracy does not remove the need to consider audience.', 'Use professional, respectful language.'],
    questions: [
      q('communication-1', 'communication-purpose', 'A teacher wants to compare a student’s recent engagement and assignment-completion pattern. An existing Teams space contains 25 employees, but only five currently teach or directly support the student.', 'What is the strongest approach?', [{ id: 'a', text: 'Use the existing space because everyone in it works for AISG.' }, { id: 'b', text: 'Communicate with colleagues who work with or legitimately support the student and share only what is needed to explore the pattern.' }, { id: 'c', text: 'Post in the larger space but use the student’s initials.' }, { id: 'd', text: 'Wait until the next full faculty meeting rather than communicate digitally.' }], 'b', 'Correct. The response aligns purpose, audience and necessary information. A focused conversation can help colleagues identify a pattern without giving a wider group access.', 'Being employed by AISG or using initials does not create a legitimate need to know. The stronger response matches the audience to the educational purpose and shares only what colleagues need.'),
      q('communication-2', 'communication-purpose', 'You are about to send an update about a student to eight colleagues. Three teach the student, one counsellor supports the student, and four have no current role.', 'What should guide your decision about recipients?', [{ id: 'a', text: 'Include everyone because wider awareness may be useful later.' }, { id: 'b', text: 'Include only employees with a legitimate role in understanding or supporting the situation.' }, { id: 'c', text: 'Include everyone but remove the student’s surname.' }, { id: 'd', text: 'Send it to everyone if the information is factually correct.' }], 'b', 'Correct. Recipients should have a legitimate role in understanding or supporting the situation. The purpose and need to know matter as much as accuracy.', 'Wider awareness, initials and factual accuracy do not resolve an inappropriate audience. Include the employees who need the information for the educational purpose.'),
    ],
  },
  {
    id: 'communication-minimum', number: 2, title: 'Share What Is Needed',
    summary: 'Separate actionable support information from background that colleagues do not need.',
    learn: ['Appropriate student-support communication may include classroom observations, academic progress or concerns, general social, behavioural or learning observations, and information needed to coordinate known interventions, accommodations or classroom support. The question is not “Do I know this?” but “Does this person need it for the purpose?”', 'Share what colleagues need to know to support the student—not everything you know about the student. An appropriate audience does not justify unnecessary family background, detailed history or unrelated context. Keep the message useful, proportionate and connected to the next decision.'],
    takeaways: ['Use the minimum necessary information.', 'Share support strategies and relevant observations.', 'An appropriate audience can still receive too much information.', 'Keep messages connected to action or decision-making.'],
    questions: [
      q('communication-3', 'communication-minimum', 'A colleague asks whether anything has helped a student who struggles to begin independent work.', 'What is the strongest response?', [{ id: 'a', text: 'Share the student’s full background so the colleague understands why the behaviour may be occurring.' }, { id: 'b', text: 'Share the specific strategies you tried and what you observed about their effectiveness.' }, { id: 'c', text: 'Send all of your notes so the colleague can decide what is relevant.' }, { id: 'd', text: 'Avoid sharing anything because the conversation concerns an individual student.' }], 'b', 'Correct. Specific strategies and observed effects support the colleague’s next decision without adding unrelated or unnecessary information.', 'Full background and all notes exceed the purpose, while sharing nothing prevents useful support. The stronger response shares what helps the work.'),
      q('communication-4', 'communication-minimum', 'A draft message to relevant colleagues contains assignment information, two strategies tried, one classroom observation, detailed family information, and a request for effective strategies.', 'What should change?', [{ id: 'a', text: 'Nothing because everyone receiving the message works with the student.' }, { id: 'b', text: 'Remove the unnecessary family information and retain the relevant observations, strategies and purposeful request.' }, { id: 'c', text: 'Remove the student’s name but keep everything else.' }, { id: 'd', text: 'Remove all student information because Teams should never be used for student collaboration.' }], 'b', 'Correct. The audience may be appropriate while some information is still unnecessary. Retain what colleagues need to compare patterns and support the student.', 'The message needs editing for minimum necessary information. Removing a name does not make unrelated family information necessary, and avoiding all collaboration is not the expectation.'),
    ],
  },
  {
    id: 'communication-evidence', number: 3, title: 'Describe, Don’t Label',
    summary: 'Use observable evidence and specific examples instead of assumptions about motivation, character or home life.',
    learn: ['Communication about students should be professional, purposeful, respectful, objective and focused on student success. Describe what happened, when it happened, what you tried, what happened next and what support may help. Do not convert behaviour into a judgement about motivation, attitude, character, intent or family circumstances.', 'Compare “She is lazy and does not care” with “She has not submitted three assignments this week and has needed several prompts to begin independent work.” The second message gives colleagues evidence they can compare and act on. Ask focused questions about engagement, completion, attendance, peer interactions or strategies—not theories about why a student is different.'],
    takeaways: ['Describe observable facts and specific examples.', 'Include what you tried and what happened next.', 'Ask for evidence, not theories.', 'Describe what you see; do not label what you think it means.'],
    questions: [
      q('communication-5', 'communication-evidence', 'A student arrived late three times this week, did not complete two assignments and needed repeated prompts to begin independent work.', 'Which message most strongly follows AISG expectations?', [{ id: 'a', text: 'J. seems completely unmotivated at the moment. Does anyone know what is going on?' }, { id: 'b', text: 'I am worried J. does not care about school anymore. Are you seeing the same attitude?' }, { id: 'c', text: 'I have noticed J. arrived late three times, has not completed the last two assignments and has needed several prompts to begin independent work. Are you seeing similar patterns, and have any strategies been effective?' }, { id: 'd', text: 'J. is struggling again. I wonder if something is happening at home.' }], 'c', 'Correct. This message describes observable evidence, gives a timeframe, and asks colleagues for comparable observations and useful strategies.', 'The other options turn observations into labels, judgements or speculation. The stronger response describes what is known and asks for evidence that can support the next step.'),
      q('communication-6', 'communication-evidence', 'You have noticed a significant change in a student’s classroom engagement and want useful information from colleagues.', 'Which request is most likely to produce useful information?', [{ id: 'a', text: 'Has anyone heard anything about this student?' }, { id: 'b', text: 'Does anyone know why this student suddenly changed?' }, { id: 'c', text: 'Have you noticed changes in engagement, assignment completion or peer interaction this week, and are there strategies that seem to be helping?' }, { id: 'd', text: 'Is anyone else having problems with this student?' }], 'c', 'Correct. Specific questions invite observable evidence and strategies, helping the team compare patterns without inviting speculation.', 'Broad questions can invite theories or frustration. Ask colleagues for specific observations and what has helped.'),
    ],
  },
  {
    id: 'communication-teams', number: 4, title: 'Microsoft Teams for Communication',
    summary: 'Apply the communication guidelines in Teams: choose the right space, audience and purpose for collaboration.',
    learn: ['Teams is an internal communication and collaboration tool for AISG employees. It can support planning, day-to-day teamwork and appropriate conversations about student learning, wellbeing and success. Channels provide a shared communication space for team members; chats suit quick conversations with one person or a small group.', 'Student Support Services and Leadership may create appropriate groups or channels with educators who work with a student to gather observations, identify patterns, coordinate support and determine next steps. Teams can be used to collaborate about a student, but it should not become the student’s confidential record. Purpose and audience still apply in every Teams space.'],
    takeaways: ['Use Teams for a clear internal collaboration purpose.', 'Channels suit shared coordination; chats suit small groups.', 'A relevant group can gather patterns and coordinate support.', 'Teams is not the student’s confidential record.'],
    questions: [
      q('communication-7', 'communication-teams', 'Student Support Services wants six teachers who work with the same student to share observations over several weeks about engagement, assignment completion, strategies and next steps.', 'Which approach best fits AISG expectations?', [{ id: 'a', text: 'Create separate one-to-one chats so teachers cannot see one another’s observations.' }, { id: 'b', text: 'Use an appropriate shared Teams group or channel containing the relevant educators so observations and patterns can be coordinated.' }, { id: 'c', text: 'Post in the whole faculty Team because any employee may have useful information.' }, { id: 'd', text: 'Avoid Teams whenever a named student is involved.' }], 'b', 'Correct. An appropriately scoped shared group or channel supports purposeful collaboration among the educators who need to compare evidence and coordinate support.', 'The Teams guidance supports relevant student collaboration when purpose and audience are appropriate. A whole-faculty audience is too broad, while avoiding all named-student collaboration misses the current expectation.'),
      q('communication-8', 'communication-teams', 'A colleague says, “I thought we were not allowed to use student names in Teams at all.”', 'Which response reflects the current AISG expectation?', [{ id: 'a', text: 'Correct. Only initials may ever be used.' }, { id: 'b', text: 'Student names and relevant non-confidential information may be shared internally when necessary to support the student, provided purpose, audience, professionalism and confidentiality are appropriate.' }, { id: 'c', text: 'Names may only be used in one-to-one chats.' }, { id: 'd', text: 'Names may be used freely because Teams is internal.' }], 'b', 'Correct. The current guidance updates the previous blanket expectation. Consider purpose, audience, information, professionalism and confidentiality; privacy is more than removing a name.', 'AISG does not set a blanket ban or blanket permission. Initials do not fix an inappropriate purpose or audience, and an internal tool is not a free-sharing space.'),
      q('communication-9', 'communication-teams', 'Several relevant teachers need enough information to provide consistent classroom support. One employee suggests placing every note and document about the student into the Teams channel so everyone has “the full picture.”', 'What is the strongest response?', [{ id: 'a', text: 'That is appropriate because everyone in the group works with the student.' }, { id: 'b', text: 'Only upload documents that contain the student’s initials rather than full name.' }, { id: 'c', text: 'Use Teams to coordinate the relevant support and observations colleagues need, but do not turn the channel into a repository for the student’s confidential record.' }, { id: 'd', text: 'Avoid discussing support through Teams at all.' }], 'c', 'Correct. Teams can coordinate useful observations and support, but collaboration space is not the student’s confidential record.', 'The audience and purpose may be appropriate, but every note and document still exceeds the need. Initials do not change the record’s sensitivity, and avoiding useful collaboration is unnecessary.'),
    ],
  },
  {
    id: 'communication-confidentiality', number: 5, title: 'Confidentiality and Professional Records',
    summary: 'Keep confidential records in the appropriate secure process and remember that informal digital communication is still professional.',
    learn: ['Do not upload, attach, copy or distribute confidential student documents through Teams. Examples include counselling records or notes, psychological or psychoeducational evaluations, medical records or diagnoses, School Support Plans, ILPs, Accommodation Plans, Safety Plans, Student Profiles, safeguarding or investigation records, formal disciplinary records, confidential family information, legal documents and extensive personally identifiable information.', 'When confidential or highly sensitive information needs to be communicated, use the appropriate AISG confidential system or communication process and share it only with employees who need access as part of their role. Teams messages, posts and files may be retained or later reviewed as part of a legal process, investigation, audit, safeguarding matter or authorised external request. Informal does not mean private or off the record.'],
    takeaways: ['Keep confidential documents out of Teams.', 'Share the classroom support colleagues need, not the full record.', 'Informal messages can still be retained and reviewed.', 'Write factually, respectfully and for the educational purpose.'],
    questions: [
      q('communication-10', 'communication-confidentiality', 'Teachers need to consistently use accommodations contained in a student’s School Support Plan. Someone suggests uploading the complete plan to a Teams channel containing the teachers.', 'What is the strongest response?', [{ id: 'a', text: 'Upload the plan because everyone in the channel teaches the student.' }, { id: 'b', text: 'Upload the plan but tell teachers not to download it.' }, { id: 'c', text: 'Do not upload the confidential plan. Communicate the relevant classroom support while keeping the formal record in the appropriate confidential system or process.' }, { id: 'd', text: 'Share nothing about accommodations because anything connected to a support plan is confidential.' }], 'c', 'Correct. Share the actionable support colleagues need while keeping the confidential record in the appropriate secure process.', 'A legitimate audience does not make a confidential plan appropriate to upload, and restrictions on downloading do not change that. Share the support action without distributing the record.'),
      q('communication-11', 'communication-confidentiality', 'After a difficult lesson, a teacher privately messages a trusted colleague: “I honestly cannot deal with this student anymore. He is impossible and clearly does not care.” The teacher says it is acceptable because it is a private chat.', 'What is the strongest interpretation?', [{ id: 'a', text: 'It is acceptable because private chats are informal.' }, { id: 'b', text: 'It is acceptable if both employees teach the student.' }, { id: 'c', text: 'It is inappropriate. A Teams chat remains professional school communication, and the message labels the student and vents frustration rather than contributing useful support information.' }, { id: 'd', text: 'The only issue is that the student’s name was used.' }], 'c', 'Correct. Private chat does not mean private standard. Rewrite frustration as factual observations, what was tried and what support might help.', 'The problem is not only the audience or name. Teams records may be retained or reviewed, and the message labels and vents instead of supporting a professional decision.'),
    ],
  },
  {
    id: 'communication-practice', number: 6, title: 'Purposeful Communication in Practice',
    summary: 'Bring the course together with a seven-part check before you send, post or share.',
    learn: ['Purposeful student-related communication helps answer: What are we noticing? What patterns are emerging? What has already been tried? What is working? What support may be needed? Who needs to take the next step? Communication should not be used to speculate, vent, label, overshare or distribute information unrelated to the support purpose.', 'Use the seven-part check: Purpose (why share?), Audience (who needs to know?), Information (what is necessary?), Evidence (what do I actually observe?), Language (am I describing rather than labelling?), Confidentiality (does anything belong somewhere more secure?), and Professionalism (would I be comfortable if it were professionally reviewed?). This is a decision aid, not a compliance graphic.'],
    takeaways: ['Turn frustration into observation, evidence and support.', 'Notice, compare, try, support and decide next steps.', 'Use Purpose, Audience, Information, Evidence, Language, Confidentiality and Professionalism.', 'Share what colleagues need to support the student—not everything you know.'],
    questions: [
      q('communication-12', 'communication-practice', 'After a challenging lesson, you genuinely need advice from colleagues. During today’s independent task, a student left their seat repeatedly and needed four redirections. You tried moving closer and breaking the task into smaller steps, but neither helped.', 'Which message is strongest?', [{ id: 'a', text: 'I honestly cannot deal with M. anymore. He is impossible today.' }, { id: 'b', text: 'Is M. behaving like this for everyone at the moment?' }, { id: 'c', text: 'During today’s independent task, M. left his seat repeatedly and needed four redirections before returning to the task. I tried moving closer and breaking the task into smaller steps, but neither seemed to help. Have you noticed anything similar, and has anything been effective?' }, { id: 'd', text: 'M. clearly does not want to learn today. Any ideas?' }], 'c', 'Correct. The message turns frustration into observable evidence, records what was tried and asks colleagues for support-focused comparisons.', 'The stronger response names what happened, what was tried and what help is needed. Labels, broad questions and assumptions do not give colleagues useful evidence.'),
      q('communication-13', 'communication-practice', 'Several teachers have identified the same decline in a student’s engagement.', 'What should the communication focus on next?', [{ id: 'a', text: 'Theories about what may be happening outside school.' }, { id: 'b', text: 'Collecting increasingly detailed observations indefinitely.' }, { id: 'c', text: 'Comparing observations, identifying patterns, reviewing what has been tried, considering what is working and determining what support or next step may be appropriate.' }, { id: 'd', text: 'Ending the conversation because identifying a pattern automatically makes all further discussion confidential.' }], 'c', 'Correct. Purposeful collaboration moves from noticing to comparing evidence, reviewing actions, deciding support and identifying the next step.', 'Speculation, endless collection and ending useful collaboration do not answer the support purpose. Use evidence to decide what to try or escalate next.'),
      q('communication-14', 'communication-practice', 'A counsellor has told a small group of teachers that a student needs flexibility and regular check-ins. You know observable changes in engagement, strategies that helped, detailed family circumstances and information in a confidential support document. The teachers need enough information to coordinate support.', 'Which communication approach is strongest?', [{ id: 'a', text: 'Upload the confidential support document so everyone has complete context.' }, { id: 'b', text: 'Explain the detailed family circumstances without attaching the document so teachers understand the reason.' }, { id: 'c', text: 'In an appropriate space containing the relevant educators, share observable classroom information, useful strategies, what has been working and what is needed to coordinate support—without distributing the confidential record or unnecessary sensitive background.' }, { id: 'd', text: 'Share nothing digitally because involvement from a counsellor makes the whole situation automatically confidential.' }], 'c', 'Correct. This applies the complete framework: purpose, audience, minimum necessary information, observable evidence, professional language and confidentiality. Colleagues need to know what support to provide, not every confidential detail explaining why.', 'The strongest response enables coordinated support while protecting the confidential record. Complete documents and detailed background exceed the purpose, while sharing nothing prevents appropriate action.'),
    ],
  },
];

export const teamsQuestions: AiQuestion[] = teamsSections.flatMap((section) => section.questions);
