import type { AiQuestion, AiSection } from '@/lib/ai-course';

export const TECHNOLOGY_TLF_COURSE_VERSION = 'SY2026-27';

const shared = {
  courseVersion: TECHNOLOGY_TLF_COURSE_VERSION,
  contentOwner: 'Learning & Teaching',
  reviewStatus: 'draft_for_learning_and_teaching_review',
} as const;

export const technologyTlfSections: AiSection[] = [
  {
    id: 'tech-purpose',
    number: 1,
    title: 'Start with learning, not technology',
    summary: 'Use technology when it strengthens the learner experience described by the Transformative Learning Framework.',
    learn: [
      'AISG’s Transformative Learning Framework is a lens for designing, noticing, reflecting on and improving learning. Technology is not a seventh facet and it is not evidence of transformation by itself. Start with the intended learning and a small number of relevant indicators, then ask whether technology can make the experience more accessible, agentic, authentic, creative, collaborative or actionable.',
      'A useful technology decision begins with the learner experience rather than the feature list. Ask: What will students experience, do, connect or become? What thinking must remain with the learner? What becomes possible, stronger or more inclusive because of the technology? If the answer is only “the task is digital now,” the technology may have substituted a medium without amplifying the learning.',
      'Use a simple amplification test: learning first → relevant TLF indicator(s) → desired student experience → technology affordance → evidence to notice. The strongest technology choices are often quiet. They remove a barrier, widen an audience, enable meaningful choice, connect people who could not otherwise collaborate, make thinking visible or help students create and act in ways that were previously difficult.',
    ],
    takeaways: [
      'Technology is a means, not the learning goal.',
      'Select a few relevant TLF indicators before choosing a tool.',
      'Ask what technology makes meaningfully better or newly possible.',
      'Look for evidence in student talk, choices, work, relationships and action.',
    ],
    questions: [
      {
        ...shared,
        id: 'tech-tlf-1', section: 'tech-purpose', questionNumber: 1, assessmentLevel: 'Foundation',
        learningObjective: 'Distinguish purposeful technology integration from technology-first planning.',
        scenario: 'A teacher discovers an impressive new app and wants every class to use it next week. The learning goal and student need have not yet been identified.',
        question: 'What is the strongest first move?',
        options: [
          { id: 'a', text: 'Choose the most advanced feature so students experience innovation.' },
          { id: 'b', text: 'Start with the intended learning and relevant TLF indicators, then decide whether the technology strengthens that experience.' },
          { id: 'c', text: 'Require the tool in every class so implementation is consistent.' },
          { id: 'd', text: 'Avoid the tool because transformative learning should not depend on technology.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Purpose comes first. The TLF helps define the learner experience; technology is selected only when it meaningfully strengthens that experience.',
        incorrectFeedback: 'A tool is not transformative because it is new, consistent or digital. Begin with intended learning and the learner experience, then judge whether technology adds meaningful value.',
        contentTags: ['Purposeful Technology', 'TLF Lens', 'Learning Design'],
      },
      {
        ...shared,
        id: 'tech-tlf-2', section: 'tech-purpose', questionNumber: 2, assessmentLevel: 'Application',
        learningObjective: 'Identify when technology changes the medium without deepening engagement.',
        scenario: 'Students used to complete a worksheet on paper. The teacher now uploads the same worksheet as a locked PDF that students type into individually. Nothing else about the task changes.',
        question: 'Which interpretation is strongest?',
        options: [
          { id: 'a', text: 'The learning is transformed because students are using devices.' },
          { id: 'b', text: 'The technology may improve convenience, but there is little evidence yet that it amplifies a TLF learner experience.' },
          { id: 'c', text: 'The task demonstrates Agency because students control a keyboard.' },
          { id: 'd', text: 'The task demonstrates Authenticity because digital work is used outside school.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Digitising a task can be useful without being transformative. Look for a meaningful change in voice, access, purpose, creation, collaboration, action or another learner experience.',
        incorrectFeedback: 'Device use alone does not establish Agency, Authenticity or transformation. Ask what is different about what learners can experience, decide, create, connect or contribute.',
        contentTags: ['Purposeful Technology', 'Amplification', 'Learning Design'],
      },
      {
        ...shared,
        id: 'tech-tlf-3', section: 'tech-purpose', questionNumber: 3, assessmentLevel: 'Analysis',
        learningObjective: 'Use learner evidence to judge the value of a technology choice.',
        scenario: 'A team says its new platform has transformed learning because usage has doubled. Students spend more time online, but the team has not examined student decisions, work, relationships or action.',
        question: 'What evidence would most strengthen the team’s judgement?',
        options: [
          { id: 'a', text: 'The number of logins and minutes spent on the platform.' },
          { id: 'b', text: 'The number of digital tools teachers used during the unit.' },
          { id: 'c', text: 'Evidence of what students are experiencing, choosing, creating, connecting and doing in relation to selected TLF indicators.' },
          { id: 'd', text: 'A teacher survey asking whether the platform looks modern.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. The framework directs attention to learner experience and evidence. Usage data can inform implementation, but it does not by itself demonstrate deeper engagement.',
        incorrectFeedback: 'Technology metrics describe use, not necessarily learning. Stronger evidence connects the tool to observable student experience and the TLF indicators that guided the design.',
        contentTags: ['Evidence', 'TLF Indicators', 'Amplification'],
      },
    ],
  },
  {
    id: 'tech-being',
    number: 2,
    title: 'Being: amplify Personalisation and Agency',
    summary: 'Use technology to reduce barriers, widen expression and place meaningful decisions in learners’ hands.',
    learn: [
      'Technology can amplify Personalisation when it helps learning respond to linguistic, cognitive, social-emotional and cultural strengths and needs. Examples include multilingual or multimodal entry points, assistive and adaptive supports, flexible ways to access information, and multiple pathways for demonstrating understanding. The goal is not more options for their own sake; the options should remove barriers or make the learning more relevant and inclusive.',
      'Technology can amplify Agency when students use it to make meaningful decisions, set goals, reflect, choose how to approach or demonstrate learning, and shape what happens next. A useful design question from AISG’s transformative learning goal work is whether students are the primary users of technology rather than passive recipients of teacher-controlled technology.',
      'Choice is not automatically Agency. Choosing a font, background colour or one of three equivalent templates may be pleasant but does not necessarily shape learning. Stronger Agency appears when technology expands decisions that matter: which question to pursue, which evidence to gather, which medium best communicates understanding, which feedback to act on, or how to revise a learning pathway.',
    ],
    takeaways: [
      'Use technology to remove barriers and widen meaningful access.',
      'Multiple modes can strengthen Personalisation when they serve learner strengths and needs.',
      'Agency grows through decisions that genuinely shape learning.',
      'Students should increasingly be the primary users and decision-makers.',
    ],
    questions: [
      {
        ...shared,
        id: 'tech-tlf-4', section: 'tech-being', questionNumber: 4, assessmentLevel: 'Application',
        learningObjective: 'Connect multimodal and multilingual technology use to Personalisation.',
        scenario: 'Students can access a concept through text, audio, diagrams and translated supports, then choose from several appropriate modes to demonstrate understanding.',
        question: 'Which TLF facet is most directly amplified by this technology design?',
        options: [
          { id: 'a', text: 'Personalisation' },
          { id: 'b', text: 'Taking Action' },
          { id: 'c', text: 'Authenticity' },
          { id: 'd', text: 'Collaboration' },
        ],
        answer: 'a',
        correctFeedback: 'Correct. The technology is responding to learner strengths and needs while enabling multiple modes and pathways for understanding and expression.',
        incorrectFeedback: 'Other facets could appear in the wider learning experience, but the clearest evidence here is responsive access and multiple pathways—central to Personalisation.',
        contentTags: ['Personalisation', 'Multimodal Learning', 'Accessibility'],
      },
      {
        ...shared,
        id: 'tech-tlf-5', section: 'tech-being', questionNumber: 5, assessmentLevel: 'Analysis',
        learningObjective: 'Distinguish meaningful Agency from superficial digital choice.',
        scenario: 'Two teachers offer “choice” in a project. In Class A, students choose one of four slide themes. In Class B, students choose a question, select an appropriate digital or non-digital medium, seek feedback and explain how they revised their approach.',
        question: 'Why is Class B the stronger example of Agency?',
        options: [
          { id: 'a', text: 'Students use more technology.' },
          { id: 'b', text: 'Students make decisions that shape the direction, expression and improvement of their learning.' },
          { id: 'c', text: 'Students are allowed to work without teacher expectations.' },
          { id: 'd', text: 'Students can make the final product look more attractive.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Agency is strengthened when students make consequential decisions, reflect and act on their learning—not when they only customise presentation.',
        incorrectFeedback: 'The difference is not the amount of technology or visual customisation. The stronger experience gives students ownership of meaningful decisions and next steps.',
        contentTags: ['Agency', 'Voice and Choice', 'Student Ownership'],
      },
      {
        ...shared,
        id: 'tech-tlf-6', section: 'tech-being', questionNumber: 6, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Select technology support that preserves learner ownership.',
        scenario: 'A learner finds extended writing difficult. The learning intention is to develop and communicate the learner’s own explanation of a scientific process. Several digital supports are available.',
        question: 'Which use best balances Personalisation and Agency?',
        options: [
          { id: 'a', text: 'Use a tool to generate the complete explanation so the writing barrier disappears.' },
          { id: 'b', text: 'Require handwritten writing because support would make the task unfair.' },
          { id: 'c', text: 'Offer appropriate supports such as speech-to-text, planning tools or multimodal expression while keeping the scientific reasoning and decisions with the learner.' },
          { id: 'd', text: 'Let the learner select any technology without considering the learning intention.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. Purposeful technology can reduce an access barrier while preserving the intellectual work, voice and decision-making the learner needs to own.',
        incorrectFeedback: 'Removing the barrier should not automatically remove the intended thinking. Choose supports that increase access while keeping the learner responsible for the reasoning and key decisions.',
        contentTags: ['Personalisation', 'Agency', 'Accessibility', 'Learner Ownership'],
      },
    ],
  },
  {
    id: 'tech-connecting',
    number: 3,
    title: 'Connecting: amplify Authenticity and Creativity',
    summary: 'Use technology to connect learning with meaningful contexts, audiences, perspectives, inquiry and original expression.',
    learn: [
      'Technology can amplify Authenticity by connecting students with real questions, current information, experts, communities and audiences beyond the classroom. It can help students investigate authentic questions using research and information-literacy skills, experience diverse perspectives and apply learning in roles that resemble the practices of people beyond school.',
      'Publishing online does not automatically make a task authentic. Ask: Who is the audience? Why would they care? What role are students taking? How does the audience or context change the decisions students make? An authentic audience should influence the quality, purpose or form of the work rather than simply exist as a place to upload it.',
      'Technology can amplify Creativity when it expands opportunities to generate, prototype, remix, simulate, compose, code, design, test and communicate original ideas. The strongest creative use is not the tool with the most effects. It is the experience that gives students room to experiment, take thoughtful risks, refine ideas and express understanding in ways that deepen meaning.',
    ],
    takeaways: [
      'Authenticity comes from meaningful roles, questions, contexts, audiences and purposes.',
      'Technology can widen access to people, perspectives and information beyond the classroom.',
      'Creativity is about generating, experimenting and expressing—not digital decoration.',
      'A real audience should change how students think about the work.',
    ],
    questions: [
      {
        ...shared,
        id: 'tech-tlf-7', section: 'tech-connecting', questionNumber: 7, assessmentLevel: 'Application',
        learningObjective: 'Recognise technology that amplifies authentic audience and purpose.',
        scenario: 'Students investigate accessibility around Guangzhou, interview community members remotely, map findings and present evidence-based recommendations to a local organisation that has agreed to respond.',
        question: 'What makes the technology use most strongly connected to Authenticity?',
        options: [
          { id: 'a', text: 'The presentation contains multimedia.' },
          { id: 'b', text: 'Students use several different apps.' },
          { id: 'c', text: 'Technology connects inquiry, community perspectives, a meaningful role and an audience whose response matters.' },
          { id: 'd', text: 'The work is completed outside normal class time.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. The technology strengthens access to authentic perspectives, context, role and audience. Those features—not the number of apps—make the learning more authentic.',
        incorrectFeedback: 'Multimedia and multiple tools may support the experience, but authenticity depends on meaningful purpose, context, role and audience.',
        contentTags: ['Authenticity', 'Authentic Audience', 'Community Connection'],
      },
      {
        ...shared,
        id: 'tech-tlf-8', section: 'tech-connecting', questionNumber: 8, assessmentLevel: 'Analysis',
        learningObjective: 'Distinguish creative technology use from polished reproduction.',
        scenario: 'In one class students copy a teacher-made video format exactly. In another, students generate several approaches, prototype, test with peers, revise and choose the medium that best communicates their idea.',
        question: 'Which evidence most strongly indicates Creativity?',
        options: [
          { id: 'a', text: 'The final product uses professional-looking transitions.' },
          { id: 'b', text: 'Students generate, test and refine original ideas and make purposeful choices about expression.' },
          { id: 'c', text: 'Every student uses the same digital template.' },
          { id: 'd', text: 'Students finish the task quickly because the software automates production.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Creativity is visible in idea generation, experimentation, thoughtful risk, refinement and original expression.',
        incorrectFeedback: 'A polished digital product can still be reproduction. Look for evidence of original thinking, experimentation and purposeful expression.',
        contentTags: ['Creativity', 'Prototyping', 'Original Expression'],
      },
      {
        ...shared,
        id: 'tech-tlf-9', section: 'tech-connecting', questionNumber: 9, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Choose technology that strengthens both Authenticity and Creativity without over-engineering the task.',
        scenario: 'A Grade 6 team wants students to communicate local environmental learning. The current task is a teacher-assigned slideshow presented only to classmates.',
        question: 'Which redesign is strongest?',
        options: [
          { id: 'a', text: 'Require animation on every slide so the product is more creative.' },
          { id: 'b', text: 'Let students select any app but keep the same audience and purpose.' },
          { id: 'c', text: 'Identify a meaningful audience or community purpose, let students choose an appropriate medium, and build in opportunities to prototype, receive feedback and revise.' },
          { id: 'd', text: 'Replace the task with a teacher-created video so students receive higher-quality information.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. The redesign strengthens authentic purpose and audience while creating space for student decision-making, experimentation and original expression.',
        incorrectFeedback: 'More effects or more app choice alone do not deepen Authenticity or Creativity. Strengthen the purpose, audience, student decisions and creative process.',
        contentTags: ['Authenticity', 'Creativity', 'Learning Design'],
      },
    ],
  },
  {
    id: 'tech-doing',
    number: 4,
    title: 'Doing: amplify Taking Action and Collaboration',
    summary: 'Use technology to support purposeful contribution, shared goals, diverse perspectives and collective learning.',
    learn: [
      'Technology can amplify Taking Action when students use learning to address authentic opportunities or challenges, create meaningful products or solutions, share cultural histories, strengthen communities or contribute to change. The important question is not whether the action is online. Ask who benefits, what need or opportunity the action responds to, and how students’ learning informs the contribution.',
      'Collaboration is the facet where the TLF explicitly names digital technologies. Students may use digital tools to collaborate across languages, cultures and communities, and they are expected to use technology responsibly, ethically and purposefully to strengthen collective learning. A shared document is not automatically collaboration; the learning should require shared purpose, interdependence, perspective-taking and equitable contribution.',
      'Technology can broaden whose voices enter a collaboration, but educators still need to design for inclusion. Consider access, language, time zones, roles, turn-taking, attribution, consent and how disagreement will be handled. The aim is not simply to connect people—it is to strengthen the quality of what they learn and build together.',
    ],
    takeaways: [
      'Taking Action connects learning to purposeful contribution and change.',
      'Digital collaboration should deepen collective learning, not just divide tasks.',
      'Design for equitable contribution, diverse perspectives and ethical participation.',
      'Ask who benefits and what shared purpose genuinely requires collaboration.',
    ],
    questions: [
      {
        ...shared,
        id: 'tech-tlf-10', section: 'tech-doing', questionNumber: 10, assessmentLevel: 'Application',
        learningObjective: 'Recognise purposeful digital collaboration across communities.',
        scenario: 'AISG students work online with students in another country to compare local water-use challenges, discuss different perspectives and jointly create recommendations that reflect both contexts.',
        question: 'Which feature most strongly demonstrates TLF Collaboration?',
        options: [
          { id: 'a', text: 'Both groups use the same video-conferencing platform.' },
          { id: 'b', text: 'The technology enables purposeful cross-cultural collaboration, shared decisions and learning from different perspectives.' },
          { id: 'c', text: 'The teacher records the meeting for later.' },
          { id: 'd', text: 'Students have individual devices.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The technology enables purposeful collaboration across communities while students learn from diverse perspectives and build something together.',
        incorrectFeedback: 'The platform or device is only infrastructure. The stronger evidence is purposeful shared work, perspective-taking and collective learning.',
        contentTags: ['Collaboration', 'Digital Collaboration', 'Cultural Responsiveness'],
      },
      {
        ...shared,
        id: 'tech-tlf-11', section: 'tech-doing', questionNumber: 11, assessmentLevel: 'Analysis',
        learningObjective: 'Distinguish true collaboration from parallel digital work.',
        scenario: 'Four students share one online document. Each writes a separate section, no one reads another section, and one student combines the parts at the end.',
        question: 'What is the strongest next design move if the goal is to deepen Collaboration?',
        options: [
          { id: 'a', text: 'Add more students to the document.' },
          { id: 'b', text: 'Require each student to use a different text colour.' },
          { id: 'c', text: 'Design shared decisions, peer response and interdependent roles so students must learn from and build on one another’s contributions.' },
          { id: 'd', text: 'Replace the shared document with four individual files.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. Collaboration is strengthened when the task requires interdependence, shared thinking, equitable contribution and response to others—not simply a shared digital location.',
        incorrectFeedback: 'More people or a shared file does not guarantee collaboration. Redesign the work so students genuinely depend on, respond to and build with one another.',
        contentTags: ['Collaboration', 'Interdependence', 'Equitable Contribution'],
      },
      {
        ...shared,
        id: 'tech-tlf-12', section: 'tech-doing', questionNumber: 12, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Use technology to support purposeful student action rather than performative publication.',
        scenario: 'Students create a digital campaign about an issue they care about. The teacher wants the project to demonstrate Taking Action rather than simply online publishing.',
        question: 'Which addition would most strengthen the design?',
        options: [
          { id: 'a', text: 'Require every campaign to have a logo and hashtag.' },
          { id: 'b', text: 'Increase the number of social-style posts students create.' },
          { id: 'c', text: 'Require students to investigate the need, listen to affected perspectives, identify who the action serves, choose an ethical contribution and evaluate its effect.' },
          { id: 'd', text: 'Give the campaign a public URL regardless of whether anyone needs it.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. Purposeful action grows from authentic need, listening, ethical contribution and reflection on impact. Technology can amplify the reach, but it does not create the purpose.',
        incorrectFeedback: 'Visibility is not the same as meaningful action. Strengthen the connection between learning, authentic need, community perspectives, ethical contribution and impact.',
        contentTags: ['Taking Action', 'Authentic Contribution', 'Ethical Technology'],
      },
    ],
  },
  {
    id: 'tech-design',
    number: 5,
    title: 'Design for amplification, not substitution',
    summary: 'Choose technology by the learning affordance it adds, then preserve the thinking students need to own.',
    learn: [
      'A practical planning sequence is: 1) name the intended learning; 2) select the few TLF indicators that matter most; 3) describe what students should experience, do, connect or become; 4) identify the barrier or opportunity; 5) choose technology only if its affordance strengthens that experience; 6) decide what learner evidence you will notice; 7) reflect on the next design move.',
      'Useful technology affordances include access, translation, multimodal expression, simulation, rapid feedback, data visualisation, creation, documentation, connection across distance, authentic publishing and collaboration. The same tool can support very different learning depending on the design. Begin with the affordance you need, not the brand or platform you happen to know.',
      'Technology can also weaken transformative learning when it centralises the teacher, automates the thinking students need to practise, narrows everyone into one pathway, distracts from relationships or adds complexity without benefit. Sometimes the most purposeful choice is to put the device away. A transformative learning environment is not one in which technology is always visible; it is one in which technology is used intentionally when it strengthens learning.',
    ],
    takeaways: [
      'Name the learning affordance before naming the tool.',
      'Preserve the intellectual work students need to own.',
      'More technology is not automatically better technology use.',
      'Choosing not to use technology can be a purposeful design decision.',
    ],
    questions: [
      {
        ...shared,
        id: 'tech-tlf-13', section: 'tech-design', questionNumber: 13, assessmentLevel: 'Analysis',
        learningObjective: 'Evaluate whether a technology affordance justifies its use.',
        scenario: 'A teacher is choosing between a simple discussion around student artefacts and a complex platform that would require 20 minutes of setup but adds no new audience, access, feedback, creation or collaboration.',
        question: 'What is the strongest decision?',
        options: [
          { id: 'a', text: 'Use the platform because transformative learning should look technologically advanced.' },
          { id: 'b', text: 'Use the simpler approach unless the platform adds a clear learning affordance connected to the intended TLF experience.' },
          { id: 'c', text: 'Use both so students experience maximum variety.' },
          { id: 'd', text: 'Avoid all digital tools in future because this one is unnecessary.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Technology earns its place when it adds a meaningful affordance. Complexity without learning value can reduce rather than amplify engagement.',
        incorrectFeedback: 'The goal is not to maximise technology use. Choose the least complex approach that best supports the intended learner experience.',
        contentTags: ['Purposeful Technology', 'Affordances', 'Learning Design'],
      },
      {
        ...shared,
        id: 'tech-tlf-14', section: 'tech-design', questionNumber: 14, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Preserve student thinking when using automation and digital support.',
        scenario: 'A tool can instantly generate a polished data interpretation for students. The unit’s learning goal is for students to identify patterns, justify interpretations and explain uncertainty.',
        question: 'Which use is most aligned with transformative learning?',
        options: [
          { id: 'a', text: 'Let the tool generate the interpretation, then ask students to format it.' },
          { id: 'b', text: 'Ban the tool without considering whether it could support another part of the process.' },
          { id: 'c', text: 'Use technology for an appropriate support—such as visualising data or testing student-generated interpretations—while students retain responsibility for pattern-finding and justification.' },
          { id: 'd', text: 'Ask the tool for three interpretations and let students select their favourite.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. The technology supports the process without outsourcing the thinking named in the learning goal. Students remain the primary sense-makers.',
        incorrectFeedback: 'The key is to preserve the intended intellectual work. Technology can assist with access, visualisation or feedback without completing the reasoning students are meant to develop.',
        contentTags: ['Learner Ownership', 'Purposeful Technology', 'Thinking'],
      },
      {
        ...shared,
        id: 'tech-tlf-15', section: 'tech-design', questionNumber: 15, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Select evidence that shows whether technology amplified learning.',
        scenario: 'A teacher uses a digital reflection tool to strengthen Agency. Students set goals, record evidence and choose next steps over several weeks.',
        question: 'Which evidence would best show whether the technology is amplifying Agency?',
        options: [
          { id: 'a', text: 'Students logged in every week.' },
          { id: 'b', text: 'Students can explain how their evidence shaped goals, decisions and next steps, and their choices become more intentional over time.' },
          { id: 'c', text: 'The dashboard contains colourful charts.' },
          { id: 'd', text: 'The teacher can export a report.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Evidence of ownership, reflection and increasingly intentional decisions connects the technology directly to Agency.',
        incorrectFeedback: 'Usage and dashboard features show implementation, not Agency. Look for evidence that students are reflecting, deciding and shaping what happens next.',
        contentTags: ['Agency', 'Evidence', 'Reflection'],
      },
    ],
  },
  {
    id: 'tech-evidence',
    number: 6,
    title: 'From indicator to evidence: make the next design move',
    summary: 'Use the TLF planning cycle to evaluate technology through the learner experience and improve what comes next.',
    learn: [
      'The Faculty Field Guide moves from context and intended learning to selected indicators, then to what students will experience, do, connect or become, the evidence educators will notice, and finally reflection and the next design move. Technology fits inside this process; it does not replace it. A strong plan can explain exactly which learner experience the technology is intended to amplify.',
      'When reviewing a technology-rich experience, notice student talk, choices, work, relationships and action. Ask learners what the technology enabled, what it made harder, where they had meaningful control, whose perspectives were included, who the audience was, how collaboration worked and what contribution or change resulted. Student experience is evidence—not an assumption we make because a device was present.',
      'Finish with one useful next move. You might widen expression for a multilingual learner, move a teacher-created product into student hands, connect students to a real audience, make group roles more interdependent, build in prototyping, or remove a tool that is distracting from the intended learning. Transformative technology use is iterative: design, notice, reflect, improve.',
    ],
    takeaways: [
      'Technology sits inside the TLF design-and-reflection cycle.',
      'Notice learner evidence rather than assuming impact from device use.',
      'Ask students what the technology enabled and constrained.',
      'Use evidence to choose one practical next design move.',
    ],
    questions: [
      {
        ...shared,
        id: 'tech-tlf-16', section: 'tech-evidence', questionNumber: 16, assessmentLevel: 'Analysis',
        learningObjective: 'Apply the Field Guide planning sequence to technology integration.',
        scenario: 'A PLC is redesigning a unit and wants to “add more technology.” They have not yet agreed what student experience they want to deepen.',
        question: 'Which sequence best reflects the TLF approach?',
        options: [
          { id: 'a', text: 'Choose tool → train students → count usage → select a TLF facet afterwards.' },
          { id: 'b', text: 'Intended learning → selected indicators → desired learner experience → useful technology affordance → evidence to notice → next design move.' },
          { id: 'c', text: 'List all available tools → assign one to each facet → require all six.' },
          { id: 'd', text: 'Choose the tool students enjoy most → build the unit around its features.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The design starts with learning and selected indicators, then places technology in service of the learner experience and evidence.',
        incorrectFeedback: 'The TLF is a design lens, not a technology inventory. Start with intended learning and learner experience, then choose an affordance and identify evidence.',
        contentTags: ['TLF Lens', 'Design Cycle', 'Evidence'],
      },
      {
        ...shared,
        id: 'tech-tlf-17', section: 'tech-evidence', questionNumber: 17, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Use learner evidence to revise a technology-rich lesson.',
        scenario: 'During a technology-rich project, the teacher notices students are highly active on devices but rarely talk about their ideas, one student makes most decisions, and the final audience is only the teacher.',
        question: 'Which next design move is strongest?',
        options: [
          { id: 'a', text: 'Add another digital platform to increase engagement.' },
          { id: 'b', text: 'Increase screen time so students become more fluent with the tools.' },
          { id: 'c', text: 'Redesign the experience around selected Agency, Collaboration and Authenticity indicators—for example shared decisions, equitable roles and a meaningful audience—then choose only the technology needed to support those moves.' },
          { id: 'd', text: 'Keep the design because high device activity already demonstrates engagement.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. The learner evidence points to weak ownership, collaboration and purpose. The next move should improve those experiences rather than simply add more technology.',
        incorrectFeedback: 'High device activity is not enough. Use the evidence to identify the missing learner experience, then redesign the task and technology around it.',
        contentTags: ['Agency', 'Collaboration', 'Authenticity', 'Next Design Move'],
      },
      {
        ...shared,
        id: 'tech-tlf-18', section: 'tech-evidence', questionNumber: 18, assessmentLevel: 'Synthesis',
        learningObjective: 'Synthesize the TLF facets into a purposeful technology design.',
        scenario: 'A team is planning a unit on a local issue. Students include multilingual learners with varied strengths. The team wants students to investigate different perspectives, make meaningful choices, collaborate beyond the classroom, create an original response and contribute something useful to the community.',
        question: 'Which technology plan is strongest?',
        options: [
          { id: 'a', text: 'Choose one powerful platform and require every student to complete the same digital sequence so the technology experience is consistent.' },
          { id: 'b', text: 'Use technology only for the final presentation so it does not interfere with learning.' },
          { id: 'c', text: 'Select a few relevant TLF indicators, use technology where it reduces barriers or enables meaningful choice, inquiry, community connection, creation and collaboration, preserve the thinking students must own, and gather evidence from student talk, choices, work, relationships and action.' },
          { id: 'd', text: 'Let students use any technology they want without constraints because maximum choice creates maximum Agency.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. This plan keeps the TLF at the centre: purposeful indicators, responsive access, meaningful student decisions, authentic connection, creation, collaboration, action and evidence for reflection.',
        incorrectFeedback: 'Transformative technology use is neither one-size-fits-all nor unlimited tool choice. The strongest plan connects selected TLF indicators to specific technology affordances while preserving learner ownership and gathering evidence of the experience.',
        contentTags: ['Synthesis', 'TLF', 'Purposeful Technology', 'Evidence'],
      },
    ],
  },
];

export const technologyTlfQuestions: AiQuestion[] = technologyTlfSections.flatMap((section) => section.questions);
