import type { AiQuestion, AiSection } from '@/lib/ai-course';

export const TLF_COURSE_VERSION = 'SY2026-27';

export const tlfSections: AiSection[] = [
  {
    id: 'tlf-promise', number: 1, title: 'The shared promise: Engagement for All',
    summary: 'Understand the four layers of the AISG Transformative Learning Framework and why it is a lens, not a checklist.',
    learn: [
      'Engagement for All is the shared centre and promise of the AISG Transformative Learning Framework. It describes the learning experiences AISG wants every student to encounter so that learners become engaged, empowered and compassionate. The framework gives educators shared language for designing learning, noticing learner experience, reflecting on evidence and improving the next design move.',
      'Read the framework in four layers: Engagement for All; the three paired dimensions Being, Connecting and Doing; six facets (Personalisation, Agency, Authenticity, Creativity, Taking Action and Collaboration); and 38 Learning Engagement Indicators. The indicators describe observable student learning experiences. They are not a list that every lesson must display, and the Faculty Field Guide asks us to use the framework as a lens, not a checklist.',
    ],
    takeaways: ['Engagement for All is the shared AISG promise.', 'Being, Connecting and Doing organise the six facets.', 'The 38 indicators describe what students experience.', 'Use a few relevant indicators to design, notice, reflect and improve.'],
    questions: [
      { id: 'tlf-1', section: 'tlf-promise', scenario: 'A new colleague wants to explain the AISG Transformative Learning Framework to a team and sketches four nested layers.', question: 'Which sequence is accurate?', options: [{ id: 'a', text: '38 indicators → six facets → Being, Connecting and Doing → Engagement for All' }, { id: 'b', text: 'Engagement for All → Being, Connecting and Doing → six facets → 38 Learning Engagement Indicators' }, { id: 'c', text: 'Engagement for All → six isolated teaching strategies → 38 teacher requirements' }, { id: 'd', text: 'Being → Connecting → Doing → three assessment scores' }], answer: 'b', correctFeedback: 'Correct. The framework moves from the shared promise, through the three dimensions and six facets, to 38 observable Learning Engagement Indicators.', incorrectFeedback: 'The framework is organised from the shared promise (Engagement for All), through Being, Connecting and Doing, to six facets and then the 38 indicators. The indicators are about student experience, not teacher compliance.' },
      { id: 'tlf-2', section: 'tlf-promise', scenario: 'A team is planning a Grade 7 inquiry and worries that a strong framework lesson must include all 38 indicators.', question: 'Which response best reflects the Faculty Field Guide?', options: [{ id: 'a', text: 'Choose the six facets with the highest number of indicators so coverage is maximised.' }, { id: 'b', text: 'Select the few indicators most relevant to the intended learning, then identify evidence and a next design move.' }, { id: 'c', text: 'Use the indicators as an observation scorecard for each teacher.' }, { id: 'd', text: 'Ask students to memorise the indicator codes before beginning.' }], answer: 'b', correctFeedback: 'Correct. The framework is a lens: select what is relevant, notice what students experience, use evidence to reflect, and improve the design.', incorrectFeedback: 'The framework is explicitly not a checklist, scorecard or memorisation exercise. A focused selection of relevant indicators supports thoughtful design and reflection.' },
    ],
  },
  {
    id: 'tlf-being', number: 2, title: 'Being: Personalisation and Agency',
    summary: 'Notice how learning responds to who students are and how they own, shape and reflect on learning.',
    learn: [
      'Personalisation recognises every learner as unique. The official indicators describe learning that responds to linguistic, cognitive, social-emotional and cultural strengths and needs, and learning connected to students’ interests, identities and aspirations. Voice, choice, multiple modes and belonging are part of the learner experience—not extras added after planning.',
      'Agency is about ownership, meaningful decisions, reflection, confidence and influence. For example, the official indicator 2.3 says: “Students reflect on their thinking, learning, and progress to improve future learning.” Personalisation asks whether learning fits and includes the learner; Agency asks how the learner owns and shapes the learning. Both can be present in one experience without becoming interchangeable.',
    ],
    takeaways: ['Personalisation responds to strengths, needs, identities and aspirations.', 'Agency grows through meaningful decisions, reflection and ownership.', 'Ask what students are experiencing and choosing.', 'Belonging and learner identity are part of engagement.'],
    questions: [
      { id: 'tlf-3', section: 'tlf-being', scenario: 'A Grade 5 science task offers audio, visual and bilingual entry points because students have varied language strengths and ways of demonstrating understanding.', question: 'Which facet is most directly evidenced?', options: [{ id: 'a', text: 'Personalisation' }, { id: 'b', text: 'Agency' }, { id: 'c', text: 'Taking Action' }, { id: 'd', text: 'Collaboration' }], answer: 'a', correctFeedback: 'Correct. The design responds to linguistic strengths and offers multiple modes and pathways—central features of Personalisation.', incorrectFeedback: 'The strongest fit is Personalisation because the evidence is about responding to learner strengths, needs and languages through multiple modes. Agency would be more central if the evidence focused on students owning decisions or reflecting on progress.' },
      { id: 'tlf-4', section: 'tlf-being', scenario: 'In a social studies project, students set a goal, choose a question, reflect on feedback and decide how to revise their work for a community audience.', question: 'Which facet is the clearest primary lens for this evidence?', options: [{ id: 'a', text: 'Personalisation, because every student receives the same task' }, { id: 'b', text: 'Agency, because students own decisions, reflection and next steps' }, { id: 'c', text: 'Authenticity, because any group work is automatically authentic' }, { id: 'd', text: 'Creativity, because revision always means an original product' }], answer: 'b', correctFeedback: 'Correct. Students are recognising strengths, making meaningful decisions, reflecting and shaping what happens next—evidence of Agency.', incorrectFeedback: 'The primary evidence is student ownership, decisions and reflection, which points to Agency. An authentic audience or original product could also be present, but those are not the clearest lens for the evidence described.' },
    ],
  },
  {
    id: 'tlf-connecting', number: 3, title: 'Connecting: Authenticity and Creativity',
    summary: 'Connect learning to meaningful contexts and create conditions for original ideas, expression and thoughtful risk.',
    learn: [
      'Authenticity connects learning to meaningful real-world contexts, challenges, audiences and purposes. Students may investigate authentic questions, work in meaningful roles, learn through diverse perspectives, connect with communities and transfer learning across contexts. “Real-world” is not a decorative theme; the work has a purpose or audience beyond completing a school exercise.',
      'Creativity invites learners to generate ideas, experiment, innovate, solve problems and express understanding in original ways. The official indicator 4.2 says: “Students experiment, innovate, and take thoughtful risks as part of the learning process.” Creativity can strengthen empathy, confidence, wellbeing and appreciation of diverse perspectives. Authenticity and Creativity often reinforce each other, but they answer different questions.',
    ],
    takeaways: ['Authenticity gives learning a meaningful context, role, audience or purpose.', 'Creativity includes generating, experimenting, expressing and thoughtful risk.', 'Ask who benefits from the work and what students are trying.', 'A polished product alone does not prove either facet.'],
    questions: [
      { id: 'tlf-5', section: 'tlf-connecting', scenario: 'Students use local water-quality data to brief a community partner, revising their recommendations after questions from that partner.', question: 'Which facet should the team use first to examine this experience?', options: [{ id: 'a', text: 'Authenticity, because the inquiry has a meaningful role, audience and purpose beyond school' }, { id: 'b', text: 'Creativity, because any recommendation is automatically original' }, { id: 'c', text: 'Personalisation, because local issues are identical to student identity' }, { id: 'd', text: 'Agency, because an adult asked students to revise' }], answer: 'a', correctFeedback: 'Correct. The meaningful community role, authentic audience and purpose are direct evidence for Authenticity.', incorrectFeedback: 'The clearest first lens is Authenticity: students are investigating and applying learning for a real audience and purpose. Creativity or Agency might also be explored if evidence supports them, but they are not automatic.' },
      { id: 'tlf-6', section: 'tlf-connecting', scenario: 'A design studio gives students time to generate several solutions, test a prototype, learn from failure and explain how their thinking changed.', question: 'Which evidence most strongly signals Creativity?', options: [{ id: 'a', text: 'Students reproduce the teacher’s model accurately.' }, { id: 'b', text: 'Students experiment, take thoughtful risks and refine original ideas.' }, { id: 'c', text: 'Students work quietly and finish on time.' }, { id: 'd', text: 'Students receive the same grade using one fixed pathway.' }], answer: 'b', correctFeedback: 'Correct. Generating, experimenting, taking thoughtful risks and refining ideas align directly with Creativity.', incorrectFeedback: 'Creativity is not simply neat presentation, speed or compliance. The evidence needs to show original idea generation, experimentation, expression or thoughtful risk in the learning process.' },
    ],
  },
  {
    id: 'tlf-doing', number: 4, title: 'Doing: Taking Action and Collaboration',
    summary: 'Move from learning toward purposeful contribution, shared goals, relationships and collective action.',
    learn: [
      'Taking Action empowers students to apply learning to informed, purposeful and ethical contributions. It includes addressing authentic opportunities and challenges, creating for authentic audiences, preserving and sharing diverse cultural histories, strengthening communities and recognising capacity to create change. Action is purposeful when students can explain what it responds to and who it serves.',
      'Collaboration develops the capacity to work purposefully and respectfully with others. The indicators attend to shared goals, diverse perspectives, digital and ethical collaboration, self-regulation, equitable contribution and navigating disagreement with empathy. A group sitting together is not enough: look for what students contribute, learn from one another and build together.',
    ],
    takeaways: ['Taking Action connects learning to ethical contribution and meaningful change.', 'Collaboration requires shared purpose, equitable contribution and trust.', 'Look for what students contribute and who benefits.', 'Group work is not automatically collaboration.'],
    questions: [
      { id: 'tlf-7', section: 'tlf-doing', scenario: 'Students research family migration stories, work with a local archive and create a public exhibit that preserves and celebrates the community’s diverse histories.', question: 'Which facet is most directly evidenced by the intended contribution?', options: [{ id: 'a', text: 'Taking Action' }, { id: 'b', text: 'Personalisation' }, { id: 'c', text: 'Agency' }, { id: 'd', text: 'Creativity only' }], answer: 'a', correctFeedback: 'Correct. Students are applying learning to preserve and share diverse cultural histories for an authentic audience—a clear Taking Action connection.', incorrectFeedback: 'The strongest lens is Taking Action because the work creates a purposeful contribution that preserves and celebrates cultural histories. Other facets may be relevant, but “creative” or “personal” alone misses the action and community purpose.' },
      { id: 'tlf-8', section: 'tlf-doing', scenario: 'A multilingual team uses a shared digital workspace to compare perspectives, divide responsibilities fairly, resolve disagreement and produce one agreed recommendation.', question: 'What evidence would make Collaboration the strongest interpretation?', options: [{ id: 'a', text: 'The teacher assigns each student a separate paragraph with no shared decision.' }, { id: 'b', text: 'Students use technology, value different perspectives, contribute equitably and navigate disagreement respectfully.' }, { id: 'c', text: 'One confident student completes the product while others watch.' }, { id: 'd', text: 'Students submit identical individual answers.' }], answer: 'b', correctFeedback: 'Correct. Purposeful shared work, digital and ethical collaboration, diverse perspectives and equitable relationship-building are all visible.', incorrectFeedback: 'Collaboration is more than dividing tasks or producing identical answers. Look for shared purpose, interdependence, diverse perspectives, responsible tools, equitable contribution and respectful disagreement.' },
    ],
  },
  {
    id: 'tlf-design-lens', number: 5, title: 'Use the framework as a design lens',
    summary: 'Turn learner evidence into a focused reflection and a practical next design move.',
    learn: [
      'The field guide’s planning page moves from context and intended learning, to selected indicators, to what students will experience, do, connect or become, then to evidence and a next design move. Start with the learner and the intended learning—not with a hunt for every code. A useful selection is small enough to guide attention and specific enough to shape a decision.',
      'Evidence can come from student talk, choices, work, relationships and action. Ask: What are students experiencing? What are they doing and connecting? What choices are they making? What evidence tells us this? What might deepen the experience for more learners? The framework supports coaching, reflection and continuous improvement; it is not an observation scorecard or a compliance exercise.',
    ],
    takeaways: ['Start with context and intended learning.', 'Select a few relevant indicators, not all 38.', 'Notice student talk, choices, work, relationships and action.', 'Use evidence to choose one useful next design move.'],
    questions: [
      { id: 'tlf-9', section: 'tlf-design-lens', scenario: 'During a learning walk, students explain their choices, compare work, listen to peers and describe how they will use the learning outside class.', question: 'Which evidence set best follows the field guide?', options: [{ id: 'a', text: 'Student talk, choices, work, relationships and action' }, { id: 'b', text: 'Teacher compliance with all 38 indicator codes' }, { id: 'c', text: 'The number of resources displayed on the wall' }, { id: 'd', text: 'A single observation score with no student perspective' }], answer: 'a', correctFeedback: 'Correct. The field guide names student talk, choices, work, relationships and action as evidence to notice.', incorrectFeedback: 'The framework asks educators to notice the learner experience through talk, choices, work, relationships and action. It is not a teacher compliance score or a count of visible resources.' },
      { id: 'tlf-10', section: 'tlf-design-lens', scenario: 'A team wants students to have more ownership in a Grade 8 exhibition. Students currently make attractive products, but they have little choice and cannot explain the audience or purpose.', question: 'Which next design move is most aligned with Engagement for All?', options: [{ id: 'a', text: 'Require every student to use all 38 indicators in the exhibition.' }, { id: 'b', text: 'Add more decoration so the products look more authentic.' }, { id: 'c', text: 'Select a small set of relevant indicators, co-design meaningful choices and audience/purpose, then gather evidence of student experience.' }, { id: 'd', text: 'Replace the exhibition with a teacher-scored compliance checklist.' }], answer: 'c', correctFeedback: 'Correct. A focused selection of indicators can guide meaningful choice, authentic purpose and evidence gathering without turning the framework into a checklist.', incorrectFeedback: 'The framework supports a focused design decision: choose relevant indicators, improve the learner experience and notice evidence. More decoration, all 38 codes or a compliance checklist would miss the lens principle.' },
    ],
  },
];

export const tlfQuestions: AiQuestion[] = tlfSections.flatMap((section) => section.questions);
