import type { AiQuestion, AiSection } from '@/lib/ai-course';

export const UDL_COURSE_VERSION = 'SY2026-27';

const shared = {
  courseVersion: UDL_COURSE_VERSION,
  contentOwner: 'Learning & Teaching',
  reviewStatus: 'draft_for_learning_and_teaching_review',
} as const;

export const udlSections: AiSection[] = [
  {
    id: 'udl-variability',
    number: 1,
    title: 'Learner Variability: design for the range from the start',
    summary: 'Understand UDL as proactive design for predictable learner variability rather than a way to fix individual learners after barriers appear.',
    learn: [
      'Universal Design for Learning (UDL) is a framework for designing learning experiences that anticipate learner variability and reduce barriers so more learners can access, participate in and make progress through meaningful, challenging learning. CAST emphasises that there is no single “average” learner: variability exists between learners and within the same learner across contexts, tasks and time.',
      'UDL shifts the design question. Instead of asking “What is wrong with this learner?” or waiting for a learner to fail before making changes, ask “Where might the goal, environment, materials, methods, assessment or routines create unnecessary barriers?” The learner is not the barrier. A barrier emerges in the interaction between a learner and the design of the learning experience.',
      'UDL is proactive and intentional. It does not mean making every possible option available all the time, nor does it remove appropriate challenge. The aim is to preserve worthwhile learning goals while building flexible pathways that recognise variability, accessibility, identity, strengths and context from the beginning.',
    ],
    takeaways: [
      'Learner variability is expected, not an exception.',
      'Look for barriers in the design and environment rather than locating the problem only in the learner.',
      'UDL is proactive: anticipate variability before barriers become failure points.',
      'Flexibility should protect meaningful challenge, not remove it.',
    ],
    questions: [
      {
        ...shared,
        id: 'udl-1', section: 'udl-variability', questionNumber: 1, assessmentLevel: 'Foundation',
        learningObjective: 'Recognise learner variability as a normal design condition.',
        scenario: 'A teacher plans one explanation, one text and one written response because “most students usually manage it.” Several learners later struggle to access the task.',
        question: 'What is the strongest UDL interpretation?',
        options: [
          { id: 'a', text: 'The learners who struggle should be identified as the problem and given a separate lesson.' },
          { id: 'b', text: 'The design assumed an average learner; the teacher should anticipate variability and consider where access or participation barriers can be reduced.' },
          { id: 'c', text: 'UDL requires every learner to receive a different lesson.' },
          { id: 'd', text: 'The task should be made easier for the whole class.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. UDL treats variability as expected and asks designers to anticipate barriers in the learning experience rather than waiting for individual learners to fail.',
        incorrectFeedback: 'UDL is neither a separate lesson for every learner nor a lowering of challenge. It begins by anticipating variability and reducing unnecessary barriers in the design.',
        contentTags: ['UDL', 'Learner Variability', 'Proactive Design'],
      },
      {
        ...shared,
        id: 'udl-2', section: 'udl-variability', questionNumber: 2, assessmentLevel: 'Foundation',
        learningObjective: 'Distinguish a learner characteristic from a design barrier.',
        scenario: 'A multilingual learner understands a science concept during discussion but cannot independently decode the dense academic wording of the only resource provided.',
        question: 'Which statement best reflects UDL thinking?',
        options: [
          { id: 'a', text: 'The learner’s multilingualism is the barrier.' },
          { id: 'b', text: 'The science concept should be removed from the task.' },
          { id: 'c', text: 'The interaction between the learner and the single language-heavy representation is creating a barrier that can be redesigned.' },
          { id: 'd', text: 'The learner should wait until their English is stronger before studying the concept.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. UDL locates barriers in the interaction between the learner and the design. The concept can remain rigorous while access to language and representation becomes more flexible.',
        incorrectFeedback: 'A learner characteristic is not automatically a barrier. UDL asks how the design can preserve the goal while reducing unnecessary obstacles to access and meaning-making.',
        contentTags: ['UDL', 'Barrier Analysis', 'Multilingual Learners'],
      },
    ],
  },
  {
    id: 'udl-goals-barriers',
    number: 2,
    title: 'Start with the Goal, Then Find the Barriers',
    summary: 'Separate the learning goal from unnecessary means so flexibility can increase without weakening what learners are expected to know or do.',
    learn: [
      'A clear goal is one of the most important anchors for UDL design. When the purpose of the learning is explicit, educators can distinguish what is essential from the particular method, material or product that happens to be traditional. CAST guidance emphasises clear, meaningful goals and flexible means for reaching them.',
      'Whenever possible, separate the goal from the means. If the goal is to analyse the causes of a historical event, “write a five-paragraph essay” may be one way to show the analysis, but writing is not necessarily the goal. If writing itself is the intended learning, however, changing the response to a video could remove the very skill being assessed. Flexibility must remain aligned to the goal.',
      'Barrier analysis asks designers to examine goals, assessments, methods, materials and environments. A useful sequence is: clarify the goal → anticipate learner variability → identify likely barriers → select flexible options or supports → gather evidence about whether learners can access the goal and demonstrate progress.',
    ],
    takeaways: [
      'Make the learning goal clear and meaningful.',
      'Separate the goal from the means when the means are not essential to the learning.',
      'Do not create flexibility that accidentally removes the skill being learned.',
      'Analyse barriers across goals, assessments, methods, materials and environments.',
    ],
    questions: [
      {
        ...shared,
        id: 'udl-3', section: 'udl-goals-barriers', questionNumber: 3, assessmentLevel: 'Application',
        learningObjective: 'Distinguish a learning goal from a non-essential means.',
        scenario: 'Students are learning to explain how evidence supports a scientific claim. The teacher has traditionally required every student to present the explanation live to the whole class.',
        question: 'What is the strongest first UDL design question?',
        options: [
          { id: 'a', text: 'How can every student be trained to feel comfortable with public speaking?' },
          { id: 'b', text: 'Is live public speaking part of the intended learning goal, or is it one possible means of demonstrating the evidence-based explanation?' },
          { id: 'c', text: 'Which students should be excused from the assessment?' },
          { id: 'd', text: 'How can the teacher make the scientific claim easier?' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. UDL begins with the goal. If public speaking is not essential to the goal, alternative ways to communicate the explanation may reduce an unnecessary barrier without lowering expectations.',
        incorrectFeedback: 'The first question is about alignment: what is actually being learned and assessed? Flexibility is strongest when it protects the goal while changing non-essential means.',
        contentTags: ['UDL', 'Goals', 'Flexible Means'],
      },
      {
        ...shared,
        id: 'udl-4', section: 'udl-goals-barriers', questionNumber: 4, assessmentLevel: 'Application',
        learningObjective: 'Protect the intended skill when designing flexible pathways.',
        scenario: 'In a writing unit, the explicit goal is to craft a coherent written argument using evidence, organisation and sentence-level control. A student asks to submit an oral recording instead of writing.',
        question: 'What is the most UDL-aligned response?',
        options: [
          { id: 'a', text: 'Accept the recording because UDL always requires choice of output format.' },
          { id: 'b', text: 'Refuse any support because all students must complete the task in exactly the same way.' },
          { id: 'c', text: 'Keep written argument as the required evidence because writing is the goal, while offering access tools, scaffolds, models or assistive supports that do not replace the writing skill.' },
          { id: 'd', text: 'Lower the writing criteria so the student can finish more quickly.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. UDL is goal-driven. When the mode is part of the intended learning, the mode should remain while barriers around access, planning, practice or production are reduced.',
        incorrectFeedback: 'Choice is not an end in itself. UDL flexibility must stay aligned with the goal; when writing is the goal, supports should help the learner write rather than replace the target skill.',
        contentTags: ['UDL', 'Goals', 'Assessment Alignment'],
      },
    ],
  },
  {
    id: 'udl-engagement',
    number: 3,
    title: 'Multiple Means of Engagement: the why of learning',
    summary: 'Design options that welcome learner interests and identities, sustain effort and persistence, and strengthen emotional capacity.',
    learn: [
      'The first UDL principle is Multiple Means of Engagement. CAST Guidelines 3.0 asks designers to consider how learners are welcomed into learning through interests and identities, how effort and persistence are sustained, and how emotional capacity is supported. Engagement is variable: what motivates, reassures or challenges one learner may work differently for another, and those patterns can change by context.',
      'Engagement is more than “making learning fun.” Strong design can optimise meaningful choice and autonomy, relevance and authenticity, joy and play, and can address bias, threat and distraction. It can clarify the meaning and purpose of goals, calibrate challenge and support, foster collaboration and interdependence, build belonging and community, and offer action-oriented feedback.',
      'Multiple means of Engagement should not become unlimited choice or entertainment. Meaningful options connect to the goal and give learners authentic ways to enter, persist, collaborate, reflect and recover from challenge. The aim is learner agency that becomes increasingly purposeful and reflective.',
    ],
    takeaways: [
      'Engagement varies across learners, identities, contexts and time.',
      'Meaningful choice, belonging, purpose, challenge, collaboration and feedback can reduce engagement barriers.',
      'Choice should be consequential and connected to the goal.',
      'UDL aims to build purposeful and reflective learner agency.',
    ],
    questions: [
      {
        ...shared,
        id: 'udl-5', section: 'udl-engagement', questionNumber: 5, assessmentLevel: 'Application',
        learningObjective: 'Recognise meaningful engagement options rather than cosmetic choice.',
        scenario: 'A teacher wants to increase student agency and offers a choice of six slide themes for the same teacher-selected question, sources and final response.',
        question: 'How should this be interpreted through UDL?',
        options: [
          { id: 'a', text: 'This is strong engagement because any choice automatically creates agency.' },
          { id: 'b', text: 'The choice is mostly cosmetic; stronger engagement would connect options to purpose, relevance, identity, challenge, collaboration or meaningful decisions in the learning.' },
          { id: 'c', text: 'UDL requires at least ten choices.' },
          { id: 'd', text: 'Choice should never be used because it creates inconsistency.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. UDL values meaningful options, not choice for its own sake. The option should change how learners connect with, persist in or take purposeful ownership of the learning.',
        incorrectFeedback: 'Cosmetic choice can feel flexible without changing the learner experience. UDL asks whether the option meaningfully supports engagement and the learning goal.',
        contentTags: ['UDL', 'Engagement', 'Agency'],
      },
      {
        ...shared,
        id: 'udl-6', section: 'udl-engagement', questionNumber: 6, assessmentLevel: 'Application',
        learningObjective: 'Identify design that supports effort, belonging and appropriate challenge.',
        scenario: 'A complex inquiry is important but several students disengage when the task feels too large. The teacher wants to preserve the challenge.',
        question: 'Which redesign is strongest?',
        options: [
          { id: 'a', text: 'Reduce the inquiry to a simple worksheet for students who hesitate.' },
          { id: 'b', text: 'Clarify the purpose and success criteria, chunk planning, provide graduated support, build peer interdependence and use feedback that helps learners act on the next step.' },
          { id: 'c', text: 'Give students a reward for finishing quickly.' },
          { id: 'd', text: 'Remove collaboration so everyone works independently.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. UDL can preserve ambitious goals while strengthening purpose, challenge-and-support balance, collaboration, belonging and action-oriented feedback.',
        incorrectFeedback: 'The aim is not to remove productive challenge. UDL designs supports that help learners sustain effort and participate meaningfully in the same worthwhile learning.',
        contentTags: ['UDL', 'Engagement', 'Persistence', 'Belonging'],
      },
    ],
  },
  {
    id: 'udl-representation',
    number: 4,
    title: 'Multiple Means of Representation: the what of learning',
    summary: 'Design flexible ways to perceive information, work with language and symbols, and build knowledge from diverse perspectives and ways of knowing.',
    learn: [
      'The second UDL principle is Multiple Means of Representation. Learners differ in how they perceive and make meaning from information. CAST Guidelines 3.0 organises this principle around options for Perception, Language & Symbols, and Building Knowledge. A single representation can create barriers even when the underlying concept is appropriate and rigorous.',
      'Representation can include adjustable display, accessible formats, captions or transcripts, descriptions of visual information, clarification of vocabulary and symbols, support for decoding notation, multiple languages where appropriate, and illustration through multiple media. These options should make the important information more perceptible and comprehensible without changing the intended goal.',
      'Representation also concerns whose knowledge is visible. UDL 3.0 emphasises authentic representation of diverse identities, perspectives and narratives, multiple ways of knowing and making meaning, connections to prior knowledge, attention to patterns and big ideas, and transfer across contexts. More media is not automatically better; each representation should serve meaning and reduce a real barrier.',
    ],
    takeaways: [
      'Representation is about access to meaning, not simply adding media.',
      'Support perception, language and symbols, and the building of knowledge.',
      'Represent diverse identities, perspectives and ways of knowing authentically.',
      'Choose representations because they serve the goal and reduce barriers.',
    ],
    questions: [
      {
        ...shared,
        id: 'udl-7', section: 'udl-representation', questionNumber: 7, assessmentLevel: 'Analysis',
        learningObjective: 'Evaluate whether multiple representations improve access to meaning.',
        scenario: 'A teacher adds a decorative video, an infographic and an animation to a dense reading, but none explains the central concept differently and all use the same unfamiliar vocabulary.',
        question: 'What is the strongest UDL critique?',
        options: [
          { id: 'a', text: 'The lesson now meets UDL because it contains multiple media.' },
          { id: 'b', text: 'The added media may increase volume without reducing the actual language or meaning-making barrier.' },
          { id: 'c', text: 'Videos and graphics should never be used.' },
          { id: 'd', text: 'Every representation should contain identical wording.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Multiple means are purposeful when they increase access to the concept, clarify language or patterns, and support meaning. More formats alone do not guarantee accessibility.',
        incorrectFeedback: 'UDL is not a media-counting exercise. Ask whether each representation helps learners perceive, interpret or connect with the intended learning.',
        contentTags: ['UDL', 'Representation', 'Accessibility'],
      },
      {
        ...shared,
        id: 'udl-8', section: 'udl-representation', questionNumber: 8, assessmentLevel: 'Analysis',
        learningObjective: 'Recognise representation that values perspective and knowledge-building.',
        scenario: 'Students are studying migration. All examples, texts and images present the experience through one dominant national perspective.',
        question: 'Which redesign is most aligned with UDL 3.0?',
        options: [
          { id: 'a', text: 'Keep the materials unchanged so all learners receive the same information.' },
          { id: 'b', text: 'Add authentic perspectives, identities and narratives; support key language; connect prior knowledge; and help learners compare patterns and relationships across sources.' },
          { id: 'c', text: 'Let students skip the topic if it feels unfamiliar.' },
          { id: 'd', text: 'Replace all written sources with one video.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. Representation includes both accessibility and the knowledge represented. UDL 3.0 explicitly values diverse identities, perspectives, narratives and multiple ways of making meaning.',
        incorrectFeedback: 'A single dominant perspective can itself create a barrier to connection and knowledge-building. Stronger representation expands access and meaning without abandoning the learning goal.',
        contentTags: ['UDL', 'Representation', 'Identity', 'Perspective'],
      },
    ],
  },
  {
    id: 'udl-action-expression',
    number: 5,
    title: 'Multiple Means of Action & Expression: the how of learning',
    summary: 'Design options for interaction, communication and strategy development while keeping the evidence aligned to the intended learning.',
    learn: [
      'The third UDL principle is Multiple Means of Action & Expression. Learners vary in how they navigate a learning environment, interact with materials, organise themselves and communicate what they know. CAST Guidelines 3.0 organises this principle around Interaction, Expression & Communication, and Strategy Development.',
      'Design options can vary and honour methods for response, navigation and movement; optimise access to accessible materials and assistive technologies; use multiple media and tools for communication and creation; and build fluency with graduated support for practice and performance. UDL 3.0 also asks designers to address biases related to modes of expression and communication.',
      'Strategy development is part of Action & Expression: set meaningful goals, anticipate and plan for challenges, organise information and resources, monitor progress and challenge exclusionary practices. The aim is not merely to let learners pick a product. It is to help them become increasingly strategic and action-oriented while the evidence still matches the goal.',
    ],
    takeaways: [
      'Action & Expression includes interaction, communication and strategic learning.',
      'Accessible and assistive technologies are legitimate pathways, not unfair advantages.',
      'Different response modes can be valid when they still demonstrate the intended learning.',
      'Build learners’ capacity to plan, organise, practise and monitor progress.',
    ],
    questions: [
      {
        ...shared,
        id: 'udl-9', section: 'udl-action-expression', questionNumber: 9, assessmentLevel: 'Analysis',
        learningObjective: 'Choose flexible expression options that preserve assessment validity.',
        scenario: 'The goal is to explain a mathematical relationship using evidence and reasoning. The teacher can assess the same reasoning through a written explanation, annotated visual, recorded explanation or live conference.',
        question: 'Why can these options be UDL-aligned?',
        options: [
          { id: 'a', text: 'Because UDL requires every task to offer at least four products.' },
          { id: 'b', text: 'Because the response modes can vary while the same reasoning goal and success criteria remain visible.' },
          { id: 'c', text: 'Because written communication is never a valid assessment.' },
          { id: 'd', text: 'Because each learner should be graded with different criteria.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. When the mode is not the target skill, varied expression can reduce barriers while preserving common evidence of the intended reasoning.',
        incorrectFeedback: 'UDL flexibility is anchored to the same clear goal. The point is not a required number of formats or different standards, but valid ways to demonstrate the intended learning.',
        contentTags: ['UDL', 'Action and Expression', 'Assessment'],
      },
      {
        ...shared,
        id: 'udl-10', section: 'udl-action-expression', questionNumber: 10, assessmentLevel: 'Analysis',
        learningObjective: 'Recognise strategy development as part of UDL.',
        scenario: 'A student repeatedly loses track of a long project. The teacher currently gives reminders only after deadlines are missed.',
        question: 'Which response best reflects UDL?',
        options: [
          { id: 'a', text: 'Continue reminders because organisation is entirely the learner’s responsibility.' },
          { id: 'b', text: 'Design supports for planning, checkpoints, organising resources and monitoring progress, then gradually build learner ownership of those strategies.' },
          { id: 'c', text: 'Shorten every project for the student.' },
          { id: 'd', text: 'Complete the planning for the student permanently.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. UDL includes strategy development: anticipating challenges, planning, organising and monitoring progress with support that can build greater independence over time.',
        incorrectFeedback: 'UDL does not mean rescuing learners or waiting for failure. Proactive scaffolds can support strategic capacity while responsibility grows.',
        contentTags: ['UDL', 'Action and Expression', 'Strategy Development'],
      },
    ],
  },
  {
    id: 'udl-access-challenge',
    number: 6,
    title: 'Accessibility, Support and Productive Challenge',
    summary: 'Use accessibility and scaffolding to open the pathway to ambitious learning rather than lowering expectations or creating unnecessary dependence.',
    learn: [
      'Accessibility is a cornerstone of UDL. If learners cannot perceive, navigate or interact with the materials or environment, they cannot meaningfully engage with the intended learning. Accessible formats, captions, keyboard access, readable layouts, assistive technologies and flexible interaction can remove barriers before individual accommodations are needed.',
      'Access is not the same as reducing intellectual demand. UDL distinguishes the challenge that belongs to the goal from difficulty created by inaccessible materials, unclear directions, unnecessary time pressure, hidden expectations or a single mode of participation. Remove the unnecessary difficulty; preserve the productive challenge.',
      'Supports should also avoid creating dependence. Graduated scaffolds, models, worked examples, rehearsal, feedback, strategic tools and accessible technologies can be available when needed and faded, adapted or chosen as learners build fluency. Equality of materials is not the same as equity of access.',
    ],
    takeaways: [
      'Accessibility is foundational to participation in rigorous learning.',
      'Remove unnecessary difficulty while preserving the challenge that belongs to the goal.',
      'Assistive and accessible technologies can be normal pathways to access.',
      'Use graduated support that builds fluency and learner ownership over time.',
    ],
    questions: [
      {
        ...shared,
        id: 'udl-11', section: 'udl-access-challenge', questionNumber: 11, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Distinguish access support from lowered expectations.',
        scenario: 'A learner uses text-to-speech to access a complex history source because decoding is not the learning goal. They then analyse the same ideas and evidence as peers.',
        question: 'What is the strongest interpretation?',
        options: [
          { id: 'a', text: 'The learner has received an unfair advantage because everyone should access the source identically.' },
          { id: 'b', text: 'The tool removes an access barrier while preserving the intended analytical challenge.' },
          { id: 'c', text: 'The learner should receive an easier source instead.' },
          { id: 'd', text: 'Assistive technology should only be used after repeated failure.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. When decoding is not the target, text-to-speech can provide equitable access while the same analytical goal and challenge remain intact.',
        incorrectFeedback: 'Equal access does not require identical means. UDL supports legitimate pathways that preserve the intended challenge and evidence.',
        contentTags: ['UDL', 'Accessibility', 'Assistive Technology'],
      },
      {
        ...shared,
        id: 'udl-12', section: 'udl-access-challenge', questionNumber: 12, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Use graduated support without creating dependence.',
        scenario: 'A teacher provides a planning scaffold for a complex task. Some students no longer need it, while others still use parts of it productively.',
        question: 'What is the strongest UDL next move?',
        options: [
          { id: 'a', text: 'Require everyone to keep using the full scaffold for consistency.' },
          { id: 'b', text: 'Remove the scaffold from everyone immediately so students become independent.' },
          { id: 'c', text: 'Keep the scaffold available and help learners choose, adapt or fade supports as they build fluency and self-monitoring.' },
          { id: 'd', text: 'Complete the scaffold for students who find planning difficult.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. UDL supports graduated assistance and increasing agency. The support can remain available while learners build capacity to select and use it strategically.',
        incorrectFeedback: 'A fixed all-or-nothing scaffold does not respond well to variability. Strong design allows support to be used and faded in ways that build independence.',
        contentTags: ['UDL', 'Scaffolding', 'Fluency', 'Agency'],
      },
    ],
  },
  {
    id: 'udl-identity-belonging',
    number: 7,
    title: 'Identity, Belonging and Barriers in the System',
    summary: 'Use UDL 3.0 to notice how identity, bias, belonging, culture and systems shape access, participation and whose ways of learning are valued.',
    learn: [
      'CAST UDL Guidelines 3.0 expands the framework’s attention to identity, bias and systems of exclusion. Learners bring multiple and intersecting identities to learning, and the “who” of learning is woven across Engagement, Representation and Action & Expression. UDL is therefore not only about individual preference or cognitive access.',
      'Designers can examine who is represented, whose knowledge and communication practices are valued, what assumptions are embedded in tasks, whether learners experience belonging, and whether routines create threat or exclusion. Collaboration is also framed through interdependence and collective learning rather than simply putting students into groups.',
      'This does not mean assuming that learners with a shared identity need the same thing. UDL resists stereotypes by designing options, listening to learner experience and looking at patterns in participation and outcomes. The question is not “What does this type of learner prefer?” but “What barriers might this design create, for whom, in this context, and what evidence are learners giving us?”',
    ],
    takeaways: [
      'Identity is part of learner variability and is woven across all three UDL principles.',
      'Notice bias, threat, exclusion, belonging and whose perspectives or communication practices are valued.',
      'Do not turn learner variability into stereotypes or fixed learning styles.',
      'Use learner experience and participation evidence to find barriers in the system.',
    ],
    questions: [
      {
        ...shared,
        id: 'udl-13', section: 'udl-identity-belonging', questionNumber: 13, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Apply UDL 3.0 attention to identity and belonging without stereotyping.',
        scenario: 'A teacher learns that several students share the same cultural background and decides they will all prefer collaborative oral tasks rather than written work.',
        question: 'What is the strongest UDL response?',
        options: [
          { id: 'a', text: 'The assumption is appropriate because culture reliably predicts learning preference.' },
          { id: 'b', text: 'Avoid fixed assumptions; design meaningful options, represent identities authentically and learn from individual learner experience and evidence.' },
          { id: 'c', text: 'Ignore culture and identity completely because UDL is only about disability.' },
          { id: 'd', text: 'Assign each cultural group a different learning style.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. UDL 3.0 values identity while resisting stereotypes. Variability exists within groups as well as between them, so design options and learner evidence matter.',
        incorrectFeedback: 'UDL does not convert identity into fixed learning preferences. It asks designers to honour identities, reduce bias and barriers, and remain responsive to actual learners in context.',
        contentTags: ['UDL', 'Identity', 'Belonging', 'Bias'],
      },
      {
        ...shared,
        id: 'udl-14', section: 'udl-identity-belonging', questionNumber: 14, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Recognise systemic barriers from participation patterns.',
        scenario: 'In whole-class discussions, the same small group speaks most often. Other students contribute sophisticated thinking in smaller groups and written reflection.',
        question: 'What is the strongest UDL design response?',
        options: [
          { id: 'a', text: 'Conclude that quieter students are less engaged.' },
          { id: 'b', text: 'Keep the routine unchanged because speaking quickly in a whole group is an important life skill.' },
          { id: 'c', text: 'Examine the participation routine as a possible barrier and design varied, valued ways to prepare, contribute, respond and build collective learning.' },
          { id: 'd', text: 'Stop all whole-class discussion permanently.' },
        ],
        answer: 'c',
        correctFeedback: 'Correct. UDL uses evidence of participation to question the design. Varied contribution structures can increase access, belonging and collective learning without eliminating discussion.',
        incorrectFeedback: 'Participation patterns may reveal a design barrier rather than a learner deficit. The stronger move is to redesign how contribution is invited and valued.',
        contentTags: ['UDL', 'Participation', 'Belonging', 'System Barriers'],
      },
      {
        ...shared,
        id: 'udl-15', section: 'udl-identity-belonging', questionNumber: 15, assessmentLevel: 'Professional Judgement',
        learningObjective: 'Distinguish UDL from learning-styles matching.',
        scenario: 'A colleague says, “UDL means identifying whether each child is a visual, auditory or kinaesthetic learner and teaching them in that style.”',
        question: 'What is the best correction?',
        options: [
          { id: 'a', text: 'Yes. UDL assigns each learner a preferred sensory style.' },
          { id: 'b', text: 'UDL recognises dynamic variability across engagement, representation and action/expression; it does not sort learners into fixed learning-style categories.' },
          { id: 'c', text: 'UDL requires all learners to use every modality in every lesson.' },
          { id: 'd', text: 'UDL only applies when a learner has a diagnosed disability.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. UDL is based on variability, not fixed learning-style labels. Options are designed around barriers, goals and context rather than assigning learners to one style.',
        incorrectFeedback: 'UDL should not be reduced to learning styles. Learners vary dynamically, and the design responds through flexible options connected to the goal and context.',
        contentTags: ['UDL', 'Learner Variability', 'Learning Styles'],
      },
    ],
  },
  {
    id: 'udl-design-cycle',
    number: 8,
    title: 'Design, Notice, Learn and Redesign',
    summary: 'Bring the UDL principles together in an intentional, iterative design cycle that uses learner evidence rather than a checklist.',
    learn: [
      'UDL is best treated as a design framework, not a checklist of features. Begin with a meaningful goal, anticipate variability and barriers, then use the three principles—Engagement, Representation, and Action & Expression—to select the few design options most likely to improve access, participation, challenge and agency in that context.',
      'After teaching, notice what learners actually experienced. Who accessed the core ideas? Who participated and persisted? What choices were meaningful? Where did learners still need unnecessary help? Could they demonstrate the intended learning in valid ways? Which supports were useful, ignored or overused? Evidence can come from student work, talk, choices, observation, reflection, assessment and learner voice.',
      'Then redesign. UDL implementation is iterative: keep what reduced barriers, adapt what did not, and look for patterns that suggest a wider curriculum or system issue. At AISG, this complements the Transformative Learning Framework and MTSS: UDL contributes proactive inclusive design, while TLF helps us notice the quality of learner experience and MTSS helps teams respond when additional support or system improvement is needed. UDL remains a distinct framework with its own principles and goal of learner agency.',
    ],
    takeaways: [
      'Use UDL as a design lens, not a feature checklist.',
      'Select options because they address a barrier and serve the goal.',
      'Use learner evidence to evaluate whether the design actually improved access, participation and agency.',
      'Redesign iteratively; UDL, TLF and MTSS can complement one another without becoming the same framework.',
    ],
    questions: [
      {
        ...shared,
        id: 'udl-16', section: 'udl-design-cycle', questionNumber: 16, assessmentLevel: 'Synthesis',
        learningObjective: 'Prioritise a coherent UDL redesign rather than adding disconnected options.',
        scenario: 'A teacher wants to “make a lesson more UDL” and lists 15 possible tools, formats and choices before clarifying the learning goal or the barriers students currently experience.',
        question: 'What should happen first?',
        options: [
          { id: 'a', text: 'Use all 15 options so the lesson covers UDL comprehensively.' },
          { id: 'b', text: 'Clarify the goal, examine learner variability and likely barriers, then choose the smallest set of purposeful options that improves access and agency.' },
          { id: 'c', text: 'Choose the newest technology because flexibility depends on digital tools.' },
          { id: 'd', text: 'Wait until students fail, then add individual modifications.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. UDL is intentional design. Start with the goal and barriers, then select purposeful options rather than accumulating features.',
        incorrectFeedback: 'A long list of UDL-looking features can become disconnected from the learning. Coherent design begins with purpose, variability and barriers.',
        contentTags: ['UDL', 'Design Cycle', 'Barrier Analysis'],
      },
      {
        ...shared,
        id: 'udl-17', section: 'udl-design-cycle', questionNumber: 17, assessmentLevel: 'Synthesis',
        learningObjective: 'Use learner evidence to evaluate a UDL design.',
        scenario: 'After a redesigned unit, the teacher wants to know whether the UDL changes helped. The unit included captions, vocabulary supports, meaningful topic choices and varied ways to demonstrate understanding.',
        question: 'Which evidence is most useful?',
        options: [
          { id: 'a', text: 'The number of UDL features the teacher added.' },
          { id: 'b', text: 'Whether learners accessed key ideas, participated and persisted, made purposeful choices, demonstrated the goal validly and needed fewer unnecessary workarounds.' },
          { id: 'c', text: 'Whether every learner used every support.' },
          { id: 'd', text: 'Whether the lesson looked more colourful than before.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. UDL is evaluated through learner experience and evidence: access, participation, progress, valid demonstration and growing agency—not by counting features.',
        incorrectFeedback: 'The presence of options does not prove they improved learning. Look at how learners accessed, engaged with and demonstrated the intended goal.',
        contentTags: ['UDL', 'Evidence', 'Learner Agency'],
      },
      {
        ...shared,
        id: 'udl-18', section: 'udl-design-cycle', questionNumber: 18, assessmentLevel: 'Synthesis',
        learningObjective: 'Synthesize goal, barrier analysis and the three UDL principles in one design decision.',
        scenario: 'A multilingual class is preparing recommendations about a local environmental issue. Students need to interpret technical evidence, collaborate and communicate defensible recommendations to an authentic audience. Current barriers include dense vocabulary, uneven confidence in discussion and one required written product.',
        question: 'Which redesign best demonstrates coherent UDL thinking?',
        options: [
          { id: 'a', text: 'Lower the technical content and give everyone the same simplified worksheet.' },
          { id: 'b', text: 'Keep the evidence-based recommendation goal; clarify key language through multiple representations; provide accessible source supports; structure varied, equitable ways to contribute to collaboration; and allow valid communication formats where format is not the target skill.' },
          { id: 'c', text: 'Let each student choose any topic and any product, even if the evidence goal is no longer visible.' },
          { id: 'd', text: 'Keep the original design and provide individual fixes only to students who cannot complete it.' },
        ],
        answer: 'b',
        correctFeedback: 'Correct. The redesign preserves the ambitious goal while anticipating barriers across Engagement, Representation and Action & Expression. It increases access and agency without removing the intended thinking.',
        incorrectFeedback: 'Coherent UDL keeps the goal visible, anticipates barriers and uses flexible means purposefully. Neither lowering the goal nor unlimited choice is required.',
        contentTags: ['UDL', 'Synthesis', 'Engagement', 'Representation', 'Action and Expression'],
      },
    ],
  },
];

export const udlQuestions: AiQuestion[] = udlSections.flatMap((section) => section.questions);
